// Code generated by tags_gen.go; DO NOT EDIT.
package live

import (
	"fmt"
	"github.com/eleven-am/pondlive/go/internal/dom"
	internalhtml "github.com/eleven-am/pondlive/go/internal/html"
	"github.com/eleven-am/pondlive/go/internal/runtime"
)

func init() {
	dom.InstallElementRefFactory(func(ctx any, descriptor dom.ElementDescriptor) any {
		liveCtx, ok := ctx.(Ctx)
		if !ok {
			panic("live: invalid element hook context")
		}
		switch descriptor.(type) {
		case internalhtml.HTMLAElement:
			ref := runtime.UseElement[internalhtml.HTMLAElement](liveCtx)
			return internalhtml.NewARef(ref)
		case internalhtml.HTMLAbbrElement:
			ref := runtime.UseElement[internalhtml.HTMLAbbrElement](liveCtx)
			return internalhtml.NewAbbrRef(ref)
		case internalhtml.HTMLAddressElement:
			ref := runtime.UseElement[internalhtml.HTMLAddressElement](liveCtx)
			return internalhtml.NewAddressRef(ref)
		case internalhtml.HTMLAreaElement:
			ref := runtime.UseElement[internalhtml.HTMLAreaElement](liveCtx)
			return internalhtml.NewAreaRef(ref)
		case internalhtml.HTMLArticleElement:
			ref := runtime.UseElement[internalhtml.HTMLArticleElement](liveCtx)
			return internalhtml.NewArticleRef(ref)
		case internalhtml.HTMLAsideElement:
			ref := runtime.UseElement[internalhtml.HTMLAsideElement](liveCtx)
			return internalhtml.NewAsideRef(ref)
		case internalhtml.HTMLAudioElement:
			ref := runtime.UseElement[internalhtml.HTMLAudioElement](liveCtx)
			return internalhtml.NewAudioRef(ref)
		case internalhtml.HTMLBElement:
			ref := runtime.UseElement[internalhtml.HTMLBElement](liveCtx)
			return internalhtml.NewBRef(ref)
		case internalhtml.HTMLBaseElement:
			ref := runtime.UseElement[internalhtml.HTMLBaseElement](liveCtx)
			return internalhtml.NewBaseRef(ref)
		case internalhtml.HTMLBdiElement:
			ref := runtime.UseElement[internalhtml.HTMLBdiElement](liveCtx)
			return internalhtml.NewBdiRef(ref)
		case internalhtml.HTMLBdoElement:
			ref := runtime.UseElement[internalhtml.HTMLBdoElement](liveCtx)
			return internalhtml.NewBdoRef(ref)
		case internalhtml.HTMLBlockquoteElement:
			ref := runtime.UseElement[internalhtml.HTMLBlockquoteElement](liveCtx)
			return internalhtml.NewBlockquoteRef(ref)
		case internalhtml.HTMLBodyElement:
			ref := runtime.UseElement[internalhtml.HTMLBodyElement](liveCtx)
			return internalhtml.NewBodyRef(ref)
		case internalhtml.HTMLBrElement:
			ref := runtime.UseElement[internalhtml.HTMLBrElement](liveCtx)
			return internalhtml.NewBrRef(ref)
		case internalhtml.HTMLButtonElement:
			ref := runtime.UseElement[internalhtml.HTMLButtonElement](liveCtx)
			return internalhtml.NewButtonRef(ref)
		case internalhtml.HTMLCanvasElement:
			ref := runtime.UseElement[internalhtml.HTMLCanvasElement](liveCtx)
			return internalhtml.NewCanvasRef(ref)
		case internalhtml.HTMLCaptionElement:
			ref := runtime.UseElement[internalhtml.HTMLCaptionElement](liveCtx)
			return internalhtml.NewCaptionRef(ref)
		case internalhtml.SVGCircleElement:
			ref := runtime.UseElement[internalhtml.SVGCircleElement](liveCtx)
			return internalhtml.NewCircleRef(ref)
		case internalhtml.HTMLCiteElement:
			ref := runtime.UseElement[internalhtml.HTMLCiteElement](liveCtx)
			return internalhtml.NewCiteRef(ref)
		case internalhtml.SVGClipPathElement:
			ref := runtime.UseElement[internalhtml.SVGClipPathElement](liveCtx)
			return internalhtml.NewClipPathRef(ref)
		case internalhtml.HTMLCodeElement:
			ref := runtime.UseElement[internalhtml.HTMLCodeElement](liveCtx)
			return internalhtml.NewCodeRef(ref)
		case internalhtml.HTMLColElement:
			ref := runtime.UseElement[internalhtml.HTMLColElement](liveCtx)
			return internalhtml.NewColRef(ref)
		case internalhtml.HTMLColgroupElement:
			ref := runtime.UseElement[internalhtml.HTMLColgroupElement](liveCtx)
			return internalhtml.NewColgroupRef(ref)
		case internalhtml.HTMLDataElement:
			ref := runtime.UseElement[internalhtml.HTMLDataElement](liveCtx)
			return internalhtml.NewDataElRef(ref)
		case internalhtml.HTMLDatalistElement:
			ref := runtime.UseElement[internalhtml.HTMLDatalistElement](liveCtx)
			return internalhtml.NewDatalistRef(ref)
		case internalhtml.HTMLDdElement:
			ref := runtime.UseElement[internalhtml.HTMLDdElement](liveCtx)
			return internalhtml.NewDdRef(ref)
		case internalhtml.SVGDefsElement:
			ref := runtime.UseElement[internalhtml.SVGDefsElement](liveCtx)
			return internalhtml.NewDefsRef(ref)
		case internalhtml.HTMLDelElement:
			ref := runtime.UseElement[internalhtml.HTMLDelElement](liveCtx)
			return internalhtml.NewDelElRef(ref)
		case internalhtml.HTMLDetailsElement:
			ref := runtime.UseElement[internalhtml.HTMLDetailsElement](liveCtx)
			return internalhtml.NewDetailsRef(ref)
		case internalhtml.HTMLDfnElement:
			ref := runtime.UseElement[internalhtml.HTMLDfnElement](liveCtx)
			return internalhtml.NewDfnRef(ref)
		case internalhtml.HTMLDialogElement:
			ref := runtime.UseElement[internalhtml.HTMLDialogElement](liveCtx)
			return internalhtml.NewDialogRef(ref)
		case internalhtml.HTMLDivElement:
			ref := runtime.UseElement[internalhtml.HTMLDivElement](liveCtx)
			return internalhtml.NewDivRef(ref)
		case internalhtml.HTMLDlElement:
			ref := runtime.UseElement[internalhtml.HTMLDlElement](liveCtx)
			return internalhtml.NewDlRef(ref)
		case internalhtml.HTMLDtElement:
			ref := runtime.UseElement[internalhtml.HTMLDtElement](liveCtx)
			return internalhtml.NewDtRef(ref)
		case internalhtml.SVGEllipseElement:
			ref := runtime.UseElement[internalhtml.SVGEllipseElement](liveCtx)
			return internalhtml.NewEllipseRef(ref)
		case internalhtml.HTMLEmElement:
			ref := runtime.UseElement[internalhtml.HTMLEmElement](liveCtx)
			return internalhtml.NewEmRef(ref)
		case internalhtml.HTMLEmbedElement:
			ref := runtime.UseElement[internalhtml.HTMLEmbedElement](liveCtx)
			return internalhtml.NewEmbedRef(ref)
		case internalhtml.HTMLFieldsetElement:
			ref := runtime.UseElement[internalhtml.HTMLFieldsetElement](liveCtx)
			return internalhtml.NewFieldsetRef(ref)
		case internalhtml.HTMLFigcaptionElement:
			ref := runtime.UseElement[internalhtml.HTMLFigcaptionElement](liveCtx)
			return internalhtml.NewFigcaptionRef(ref)
		case internalhtml.HTMLFigureElement:
			ref := runtime.UseElement[internalhtml.HTMLFigureElement](liveCtx)
			return internalhtml.NewFigureRef(ref)
		case internalhtml.HTMLFooterElement:
			ref := runtime.UseElement[internalhtml.HTMLFooterElement](liveCtx)
			return internalhtml.NewFooterRef(ref)
		case internalhtml.SVGForeignObjectElement:
			ref := runtime.UseElement[internalhtml.SVGForeignObjectElement](liveCtx)
			return internalhtml.NewForeignObjectRef(ref)
		case internalhtml.HTMLFormElement:
			ref := runtime.UseElement[internalhtml.HTMLFormElement](liveCtx)
			return internalhtml.NewFormRef(ref)
		case internalhtml.SVGGElement:
			ref := runtime.UseElement[internalhtml.SVGGElement](liveCtx)
			return internalhtml.NewGRef(ref)
		case internalhtml.HTMLH1Element:
			ref := runtime.UseElement[internalhtml.HTMLH1Element](liveCtx)
			return internalhtml.NewH1Ref(ref)
		case internalhtml.HTMLH2Element:
			ref := runtime.UseElement[internalhtml.HTMLH2Element](liveCtx)
			return internalhtml.NewH2Ref(ref)
		case internalhtml.HTMLH3Element:
			ref := runtime.UseElement[internalhtml.HTMLH3Element](liveCtx)
			return internalhtml.NewH3Ref(ref)
		case internalhtml.HTMLH4Element:
			ref := runtime.UseElement[internalhtml.HTMLH4Element](liveCtx)
			return internalhtml.NewH4Ref(ref)
		case internalhtml.HTMLH5Element:
			ref := runtime.UseElement[internalhtml.HTMLH5Element](liveCtx)
			return internalhtml.NewH5Ref(ref)
		case internalhtml.HTMLH6Element:
			ref := runtime.UseElement[internalhtml.HTMLH6Element](liveCtx)
			return internalhtml.NewH6Ref(ref)
		case internalhtml.HTMLHeadElement:
			ref := runtime.UseElement[internalhtml.HTMLHeadElement](liveCtx)
			return internalhtml.NewHeadRef(ref)
		case internalhtml.HTMLHeaderElement:
			ref := runtime.UseElement[internalhtml.HTMLHeaderElement](liveCtx)
			return internalhtml.NewHeaderRef(ref)
		case internalhtml.HTMLHgroupElement:
			ref := runtime.UseElement[internalhtml.HTMLHgroupElement](liveCtx)
			return internalhtml.NewHgroupRef(ref)
		case internalhtml.HTMLHrElement:
			ref := runtime.UseElement[internalhtml.HTMLHrElement](liveCtx)
			return internalhtml.NewHrRef(ref)
		case internalhtml.HTMLHtmlElement:
			ref := runtime.UseElement[internalhtml.HTMLHtmlElement](liveCtx)
			return internalhtml.NewHtmlRef(ref)
		case internalhtml.HTMLIElement:
			ref := runtime.UseElement[internalhtml.HTMLIElement](liveCtx)
			return internalhtml.NewIRef(ref)
		case internalhtml.HTMLIframeElement:
			ref := runtime.UseElement[internalhtml.HTMLIframeElement](liveCtx)
			return internalhtml.NewIframeRef(ref)
		case internalhtml.SVGImageElement:
			ref := runtime.UseElement[internalhtml.SVGImageElement](liveCtx)
			return internalhtml.NewImageRef(ref)
		case internalhtml.HTMLImgElement:
			ref := runtime.UseElement[internalhtml.HTMLImgElement](liveCtx)
			return internalhtml.NewImgRef(ref)
		case internalhtml.HTMLInputElement:
			ref := runtime.UseElement[internalhtml.HTMLInputElement](liveCtx)
			return internalhtml.NewInputRef(ref)
		case internalhtml.HTMLInsElement:
			ref := runtime.UseElement[internalhtml.HTMLInsElement](liveCtx)
			return internalhtml.NewInsElRef(ref)
		case internalhtml.HTMLKbdElement:
			ref := runtime.UseElement[internalhtml.HTMLKbdElement](liveCtx)
			return internalhtml.NewKbdRef(ref)
		case internalhtml.HTMLLabelElement:
			ref := runtime.UseElement[internalhtml.HTMLLabelElement](liveCtx)
			return internalhtml.NewLabelRef(ref)
		case internalhtml.HTMLLegendElement:
			ref := runtime.UseElement[internalhtml.HTMLLegendElement](liveCtx)
			return internalhtml.NewLegendRef(ref)
		case internalhtml.HTMLLiElement:
			ref := runtime.UseElement[internalhtml.HTMLLiElement](liveCtx)
			return internalhtml.NewLiRef(ref)
		case internalhtml.SVGLineElement:
			ref := runtime.UseElement[internalhtml.SVGLineElement](liveCtx)
			return internalhtml.NewLineRef(ref)
		case internalhtml.SVGLinearGradientElement:
			ref := runtime.UseElement[internalhtml.SVGLinearGradientElement](liveCtx)
			return internalhtml.NewLinearGradientRef(ref)
		case internalhtml.HTMLLinkElement:
			ref := runtime.UseElement[internalhtml.HTMLLinkElement](liveCtx)
			return internalhtml.NewLinkRef(ref)
		case internalhtml.HTMLMainElement:
			ref := runtime.UseElement[internalhtml.HTMLMainElement](liveCtx)
			return internalhtml.NewMainRef(ref)
		case internalhtml.HTMLMapElement:
			ref := runtime.UseElement[internalhtml.HTMLMapElement](liveCtx)
			return internalhtml.NewMapElRef(ref)
		case internalhtml.HTMLMarkElement:
			ref := runtime.UseElement[internalhtml.HTMLMarkElement](liveCtx)
			return internalhtml.NewMarkRef(ref)
		case internalhtml.SVGMarkerElement:
			ref := runtime.UseElement[internalhtml.SVGMarkerElement](liveCtx)
			return internalhtml.NewMarkerRef(ref)
		case internalhtml.SVGMaskElement:
			ref := runtime.UseElement[internalhtml.SVGMaskElement](liveCtx)
			return internalhtml.NewMaskRef(ref)
		case internalhtml.HTMLMenuElement:
			ref := runtime.UseElement[internalhtml.HTMLMenuElement](liveCtx)
			return internalhtml.NewMenuRef(ref)
		case internalhtml.HTMLMenuItemElement:
			ref := runtime.UseElement[internalhtml.HTMLMenuItemElement](liveCtx)
			return internalhtml.NewMenuItemRef(ref)
		case internalhtml.HTMLMetaElement:
			ref := runtime.UseElement[internalhtml.HTMLMetaElement](liveCtx)
			return internalhtml.NewMetaRef(ref)
		case internalhtml.HTMLMeterElement:
			ref := runtime.UseElement[internalhtml.HTMLMeterElement](liveCtx)
			return internalhtml.NewMeterRef(ref)
		case internalhtml.HTMLNavElement:
			ref := runtime.UseElement[internalhtml.HTMLNavElement](liveCtx)
			return internalhtml.NewNavRef(ref)
		case internalhtml.HTMLNoscriptElement:
			ref := runtime.UseElement[internalhtml.HTMLNoscriptElement](liveCtx)
			return internalhtml.NewNoscriptRef(ref)
		case internalhtml.HTMLObjectElement:
			ref := runtime.UseElement[internalhtml.HTMLObjectElement](liveCtx)
			return internalhtml.NewObjectRef(ref)
		case internalhtml.HTMLOlElement:
			ref := runtime.UseElement[internalhtml.HTMLOlElement](liveCtx)
			return internalhtml.NewOlRef(ref)
		case internalhtml.HTMLOptgroupElement:
			ref := runtime.UseElement[internalhtml.HTMLOptgroupElement](liveCtx)
			return internalhtml.NewOptgroupRef(ref)
		case internalhtml.HTMLOptionElement:
			ref := runtime.UseElement[internalhtml.HTMLOptionElement](liveCtx)
			return internalhtml.NewOptionRef(ref)
		case internalhtml.HTMLOutputElement:
			ref := runtime.UseElement[internalhtml.HTMLOutputElement](liveCtx)
			return internalhtml.NewOutputRef(ref)
		case internalhtml.HTMLPElement:
			ref := runtime.UseElement[internalhtml.HTMLPElement](liveCtx)
			return internalhtml.NewPRef(ref)
		case internalhtml.HTMLParamElement:
			ref := runtime.UseElement[internalhtml.HTMLParamElement](liveCtx)
			return internalhtml.NewParamRef(ref)
		case internalhtml.SVGPathElement:
			ref := runtime.UseElement[internalhtml.SVGPathElement](liveCtx)
			return internalhtml.NewPathRef(ref)
		case internalhtml.SVGPatternElement:
			ref := runtime.UseElement[internalhtml.SVGPatternElement](liveCtx)
			return internalhtml.NewPatternRef(ref)
		case internalhtml.HTMLPictureElement:
			ref := runtime.UseElement[internalhtml.HTMLPictureElement](liveCtx)
			return internalhtml.NewPictureRef(ref)
		case internalhtml.SVGPolygonElement:
			ref := runtime.UseElement[internalhtml.SVGPolygonElement](liveCtx)
			return internalhtml.NewPolygonRef(ref)
		case internalhtml.SVGPolylineElement:
			ref := runtime.UseElement[internalhtml.SVGPolylineElement](liveCtx)
			return internalhtml.NewPolylineRef(ref)
		case internalhtml.HTMLPortalElement:
			ref := runtime.UseElement[internalhtml.HTMLPortalElement](liveCtx)
			return internalhtml.NewPortalRef(ref)
		case internalhtml.HTMLPreElement:
			ref := runtime.UseElement[internalhtml.HTMLPreElement](liveCtx)
			return internalhtml.NewPreRef(ref)
		case internalhtml.HTMLProgressElement:
			ref := runtime.UseElement[internalhtml.HTMLProgressElement](liveCtx)
			return internalhtml.NewProgressRef(ref)
		case internalhtml.HTMLQElement:
			ref := runtime.UseElement[internalhtml.HTMLQElement](liveCtx)
			return internalhtml.NewQRef(ref)
		case internalhtml.SVGRadialGradientElement:
			ref := runtime.UseElement[internalhtml.SVGRadialGradientElement](liveCtx)
			return internalhtml.NewRadialGradientRef(ref)
		case internalhtml.HTMLRbElement:
			ref := runtime.UseElement[internalhtml.HTMLRbElement](liveCtx)
			return internalhtml.NewRbRef(ref)
		case internalhtml.SVGRectElement:
			ref := runtime.UseElement[internalhtml.SVGRectElement](liveCtx)
			return internalhtml.NewRectRef(ref)
		case internalhtml.HTMLRpElement:
			ref := runtime.UseElement[internalhtml.HTMLRpElement](liveCtx)
			return internalhtml.NewRpRef(ref)
		case internalhtml.HTMLRtElement:
			ref := runtime.UseElement[internalhtml.HTMLRtElement](liveCtx)
			return internalhtml.NewRtRef(ref)
		case internalhtml.HTMLRtcElement:
			ref := runtime.UseElement[internalhtml.HTMLRtcElement](liveCtx)
			return internalhtml.NewRtcRef(ref)
		case internalhtml.HTMLRubyElement:
			ref := runtime.UseElement[internalhtml.HTMLRubyElement](liveCtx)
			return internalhtml.NewRubyRef(ref)
		case internalhtml.HTMLSElement:
			ref := runtime.UseElement[internalhtml.HTMLSElement](liveCtx)
			return internalhtml.NewSRef(ref)
		case internalhtml.HTMLSampElement:
			ref := runtime.UseElement[internalhtml.HTMLSampElement](liveCtx)
			return internalhtml.NewSampRef(ref)
		case internalhtml.HTMLScriptElement:
			ref := runtime.UseElement[internalhtml.HTMLScriptElement](liveCtx)
			return internalhtml.NewScriptRef(ref)
		case internalhtml.HTMLSectionElement:
			ref := runtime.UseElement[internalhtml.HTMLSectionElement](liveCtx)
			return internalhtml.NewSectionRef(ref)
		case internalhtml.HTMLSelectElement:
			ref := runtime.UseElement[internalhtml.HTMLSelectElement](liveCtx)
			return internalhtml.NewSelectRef(ref)
		case internalhtml.HTMLSlotElement:
			ref := runtime.UseElement[internalhtml.HTMLSlotElement](liveCtx)
			return internalhtml.NewSlotRef(ref)
		case internalhtml.HTMLSmallElement:
			ref := runtime.UseElement[internalhtml.HTMLSmallElement](liveCtx)
			return internalhtml.NewSmallRef(ref)
		case internalhtml.HTMLSourceElement:
			ref := runtime.UseElement[internalhtml.HTMLSourceElement](liveCtx)
			return internalhtml.NewSourceRef(ref)
		case internalhtml.HTMLSpanElement:
			ref := runtime.UseElement[internalhtml.HTMLSpanElement](liveCtx)
			return internalhtml.NewSpanRef(ref)
		case internalhtml.SVGStopElement:
			ref := runtime.UseElement[internalhtml.SVGStopElement](liveCtx)
			return internalhtml.NewStopRef(ref)
		case internalhtml.HTMLStrongElement:
			ref := runtime.UseElement[internalhtml.HTMLStrongElement](liveCtx)
			return internalhtml.NewStrongRef(ref)
		case internalhtml.HTMLStyleElement:
			ref := runtime.UseElement[internalhtml.HTMLStyleElement](liveCtx)
			return internalhtml.NewStyleElRef(ref)
		case internalhtml.HTMLSubElement:
			ref := runtime.UseElement[internalhtml.HTMLSubElement](liveCtx)
			return internalhtml.NewSubRef(ref)
		case internalhtml.HTMLSummaryElement:
			ref := runtime.UseElement[internalhtml.HTMLSummaryElement](liveCtx)
			return internalhtml.NewSummaryRef(ref)
		case internalhtml.HTMLSupElement:
			ref := runtime.UseElement[internalhtml.HTMLSupElement](liveCtx)
			return internalhtml.NewSupRef(ref)
		case internalhtml.SVGSvgElement:
			ref := runtime.UseElement[internalhtml.SVGSvgElement](liveCtx)
			return internalhtml.NewSvgRef(ref)
		case internalhtml.SVGSvgTextElement:
			ref := runtime.UseElement[internalhtml.SVGSvgTextElement](liveCtx)
			return internalhtml.NewSvgTextRef(ref)
		case internalhtml.SVGTSpanElement:
			ref := runtime.UseElement[internalhtml.SVGTSpanElement](liveCtx)
			return internalhtml.NewTSpanRef(ref)
		case internalhtml.HTMLTableElement:
			ref := runtime.UseElement[internalhtml.HTMLTableElement](liveCtx)
			return internalhtml.NewTableRef(ref)
		case internalhtml.HTMLTbodyElement:
			ref := runtime.UseElement[internalhtml.HTMLTbodyElement](liveCtx)
			return internalhtml.NewTbodyRef(ref)
		case internalhtml.HTMLTdElement:
			ref := runtime.UseElement[internalhtml.HTMLTdElement](liveCtx)
			return internalhtml.NewTdRef(ref)
		case internalhtml.HTMLTemplateElement:
			ref := runtime.UseElement[internalhtml.HTMLTemplateElement](liveCtx)
			return internalhtml.NewTemplateRef(ref)
		case internalhtml.HTMLTextareaElement:
			ref := runtime.UseElement[internalhtml.HTMLTextareaElement](liveCtx)
			return internalhtml.NewTextareaRef(ref)
		case internalhtml.HTMLTfootElement:
			ref := runtime.UseElement[internalhtml.HTMLTfootElement](liveCtx)
			return internalhtml.NewTfootRef(ref)
		case internalhtml.HTMLThElement:
			ref := runtime.UseElement[internalhtml.HTMLThElement](liveCtx)
			return internalhtml.NewThRef(ref)
		case internalhtml.HTMLTheadElement:
			ref := runtime.UseElement[internalhtml.HTMLTheadElement](liveCtx)
			return internalhtml.NewTheadRef(ref)
		case internalhtml.HTMLTimeElement:
			ref := runtime.UseElement[internalhtml.HTMLTimeElement](liveCtx)
			return internalhtml.NewTimeRef(ref)
		case internalhtml.HTMLTitleElement:
			ref := runtime.UseElement[internalhtml.HTMLTitleElement](liveCtx)
			return internalhtml.NewTitleElRef(ref)
		case internalhtml.HTMLTrElement:
			ref := runtime.UseElement[internalhtml.HTMLTrElement](liveCtx)
			return internalhtml.NewTrRef(ref)
		case internalhtml.HTMLTrackElement:
			ref := runtime.UseElement[internalhtml.HTMLTrackElement](liveCtx)
			return internalhtml.NewTrackRef(ref)
		case internalhtml.HTMLUElement:
			ref := runtime.UseElement[internalhtml.HTMLUElement](liveCtx)
			return internalhtml.NewURef(ref)
		case internalhtml.HTMLUlElement:
			ref := runtime.UseElement[internalhtml.HTMLUlElement](liveCtx)
			return internalhtml.NewUlRef(ref)
		case internalhtml.SVGUseElement:
			ref := runtime.UseElement[internalhtml.SVGUseElement](liveCtx)
			return internalhtml.NewUseRef(ref)
		case internalhtml.HTMLVarElement:
			ref := runtime.UseElement[internalhtml.HTMLVarElement](liveCtx)
			return internalhtml.NewVarRef(ref)
		case internalhtml.HTMLVideoElement:
			ref := runtime.UseElement[internalhtml.HTMLVideoElement](liveCtx)
			return internalhtml.NewVideoRef(ref)
		case internalhtml.HTMLWbrElement:
			ref := runtime.UseElement[internalhtml.HTMLWbrElement](liveCtx)
			return internalhtml.NewWbrRef(ref)
		default:
			panic(fmt.Sprintf("live: unsupported element descriptor %T", descriptor))
		}
	})
}
