// Code generated by tags_gen.go; DO NOT EDIT.
// Package html provides public re-exports from internal/html.
package html

import internalhtml "github.com/eleven-am/pondlive/go/internal/html"

// Element descriptor types
type (
	HTMLAElement             = internalhtml.HTMLAElement
	HTMLAbbrElement          = internalhtml.HTMLAbbrElement
	HTMLAddressElement       = internalhtml.HTMLAddressElement
	HTMLAreaElement          = internalhtml.HTMLAreaElement
	HTMLArticleElement       = internalhtml.HTMLArticleElement
	HTMLAsideElement         = internalhtml.HTMLAsideElement
	HTMLAudioElement         = internalhtml.HTMLAudioElement
	HTMLBElement             = internalhtml.HTMLBElement
	HTMLBaseElement          = internalhtml.HTMLBaseElement
	HTMLBdiElement           = internalhtml.HTMLBdiElement
	HTMLBdoElement           = internalhtml.HTMLBdoElement
	HTMLBlockquoteElement    = internalhtml.HTMLBlockquoteElement
	HTMLBodyElement          = internalhtml.HTMLBodyElement
	HTMLBrElement            = internalhtml.HTMLBrElement
	HTMLButtonElement        = internalhtml.HTMLButtonElement
	HTMLCanvasElement        = internalhtml.HTMLCanvasElement
	HTMLCaptionElement       = internalhtml.HTMLCaptionElement
	SVGCircleElement         = internalhtml.SVGCircleElement
	HTMLCiteElement          = internalhtml.HTMLCiteElement
	SVGClipPathElement       = internalhtml.SVGClipPathElement
	HTMLCodeElement          = internalhtml.HTMLCodeElement
	HTMLColElement           = internalhtml.HTMLColElement
	HTMLColgroupElement      = internalhtml.HTMLColgroupElement
	HTMLDataElement          = internalhtml.HTMLDataElement
	HTMLDatalistElement      = internalhtml.HTMLDatalistElement
	HTMLDdElement            = internalhtml.HTMLDdElement
	SVGDefsElement           = internalhtml.SVGDefsElement
	HTMLDelElement           = internalhtml.HTMLDelElement
	HTMLDetailsElement       = internalhtml.HTMLDetailsElement
	HTMLDfnElement           = internalhtml.HTMLDfnElement
	HTMLDialogElement        = internalhtml.HTMLDialogElement
	HTMLDivElement           = internalhtml.HTMLDivElement
	HTMLDlElement            = internalhtml.HTMLDlElement
	HTMLDtElement            = internalhtml.HTMLDtElement
	SVGEllipseElement        = internalhtml.SVGEllipseElement
	HTMLEmElement            = internalhtml.HTMLEmElement
	HTMLEmbedElement         = internalhtml.HTMLEmbedElement
	HTMLFieldsetElement      = internalhtml.HTMLFieldsetElement
	HTMLFigcaptionElement    = internalhtml.HTMLFigcaptionElement
	HTMLFigureElement        = internalhtml.HTMLFigureElement
	HTMLFooterElement        = internalhtml.HTMLFooterElement
	SVGForeignObjectElement  = internalhtml.SVGForeignObjectElement
	HTMLFormElement          = internalhtml.HTMLFormElement
	SVGGElement              = internalhtml.SVGGElement
	HTMLH1Element            = internalhtml.HTMLH1Element
	HTMLH2Element            = internalhtml.HTMLH2Element
	HTMLH3Element            = internalhtml.HTMLH3Element
	HTMLH4Element            = internalhtml.HTMLH4Element
	HTMLH5Element            = internalhtml.HTMLH5Element
	HTMLH6Element            = internalhtml.HTMLH6Element
	HTMLHeadElement          = internalhtml.HTMLHeadElement
	HTMLHeaderElement        = internalhtml.HTMLHeaderElement
	HTMLHgroupElement        = internalhtml.HTMLHgroupElement
	HTMLHrElement            = internalhtml.HTMLHrElement
	HTMLHtmlElement          = internalhtml.HTMLHtmlElement
	HTMLIElement             = internalhtml.HTMLIElement
	HTMLIframeElement        = internalhtml.HTMLIframeElement
	SVGImageElement          = internalhtml.SVGImageElement
	HTMLImgElement           = internalhtml.HTMLImgElement
	HTMLInputElement         = internalhtml.HTMLInputElement
	HTMLInsElement           = internalhtml.HTMLInsElement
	HTMLKbdElement           = internalhtml.HTMLKbdElement
	HTMLLabelElement         = internalhtml.HTMLLabelElement
	HTMLLegendElement        = internalhtml.HTMLLegendElement
	HTMLLiElement            = internalhtml.HTMLLiElement
	SVGLineElement           = internalhtml.SVGLineElement
	SVGLinearGradientElement = internalhtml.SVGLinearGradientElement
	HTMLLinkElement          = internalhtml.HTMLLinkElement
	HTMLMainElement          = internalhtml.HTMLMainElement
	HTMLMapElement           = internalhtml.HTMLMapElement
	HTMLMarkElement          = internalhtml.HTMLMarkElement
	SVGMarkerElement         = internalhtml.SVGMarkerElement
	SVGMaskElement           = internalhtml.SVGMaskElement
	HTMLMenuElement          = internalhtml.HTMLMenuElement
	HTMLMenuItemElement      = internalhtml.HTMLMenuItemElement
	HTMLMetaElement          = internalhtml.HTMLMetaElement
	HTMLMeterElement         = internalhtml.HTMLMeterElement
	HTMLNavElement           = internalhtml.HTMLNavElement
	HTMLNoscriptElement      = internalhtml.HTMLNoscriptElement
	HTMLObjectElement        = internalhtml.HTMLObjectElement
	HTMLOlElement            = internalhtml.HTMLOlElement
	HTMLOptgroupElement      = internalhtml.HTMLOptgroupElement
	HTMLOptionElement        = internalhtml.HTMLOptionElement
	HTMLOutputElement        = internalhtml.HTMLOutputElement
	HTMLPElement             = internalhtml.HTMLPElement
	HTMLParamElement         = internalhtml.HTMLParamElement
	SVGPathElement           = internalhtml.SVGPathElement
	SVGPatternElement        = internalhtml.SVGPatternElement
	HTMLPictureElement       = internalhtml.HTMLPictureElement
	SVGPolygonElement        = internalhtml.SVGPolygonElement
	SVGPolylineElement       = internalhtml.SVGPolylineElement
	HTMLPortalElement        = internalhtml.HTMLPortalElement
	HTMLPreElement           = internalhtml.HTMLPreElement
	HTMLProgressElement      = internalhtml.HTMLProgressElement
	HTMLQElement             = internalhtml.HTMLQElement
	SVGRadialGradientElement = internalhtml.SVGRadialGradientElement
	HTMLRbElement            = internalhtml.HTMLRbElement
	SVGRectElement           = internalhtml.SVGRectElement
	HTMLRpElement            = internalhtml.HTMLRpElement
	HTMLRtElement            = internalhtml.HTMLRtElement
	HTMLRtcElement           = internalhtml.HTMLRtcElement
	HTMLRubyElement          = internalhtml.HTMLRubyElement
	HTMLSElement             = internalhtml.HTMLSElement
	HTMLSampElement          = internalhtml.HTMLSampElement
	HTMLScriptElement        = internalhtml.HTMLScriptElement
	HTMLSectionElement       = internalhtml.HTMLSectionElement
	HTMLSelectElement        = internalhtml.HTMLSelectElement
	HTMLSlotElement          = internalhtml.HTMLSlotElement
	HTMLSmallElement         = internalhtml.HTMLSmallElement
	HTMLSourceElement        = internalhtml.HTMLSourceElement
	HTMLSpanElement          = internalhtml.HTMLSpanElement
	SVGStopElement           = internalhtml.SVGStopElement
	HTMLStrongElement        = internalhtml.HTMLStrongElement
	HTMLStyleElement         = internalhtml.HTMLStyleElement
	HTMLSubElement           = internalhtml.HTMLSubElement
	HTMLSummaryElement       = internalhtml.HTMLSummaryElement
	HTMLSupElement           = internalhtml.HTMLSupElement
	SVGSvgElement            = internalhtml.SVGSvgElement
	SVGSvgTextElement        = internalhtml.SVGSvgTextElement
	SVGTSpanElement          = internalhtml.SVGTSpanElement
	HTMLTableElement         = internalhtml.HTMLTableElement
	HTMLTbodyElement         = internalhtml.HTMLTbodyElement
	HTMLTdElement            = internalhtml.HTMLTdElement
	HTMLTemplateElement      = internalhtml.HTMLTemplateElement
	HTMLTextareaElement      = internalhtml.HTMLTextareaElement
	HTMLTfootElement         = internalhtml.HTMLTfootElement
	HTMLThElement            = internalhtml.HTMLThElement
	HTMLTheadElement         = internalhtml.HTMLTheadElement
	HTMLTimeElement          = internalhtml.HTMLTimeElement
	HTMLTitleElement         = internalhtml.HTMLTitleElement
	HTMLTrElement            = internalhtml.HTMLTrElement
	HTMLTrackElement         = internalhtml.HTMLTrackElement
	HTMLUElement             = internalhtml.HTMLUElement
	HTMLUlElement            = internalhtml.HTMLUlElement
	SVGUseElement            = internalhtml.SVGUseElement
	HTMLVarElement           = internalhtml.HTMLVarElement
	HTMLVideoElement         = internalhtml.HTMLVideoElement
	HTMLWbrElement           = internalhtml.HTMLWbrElement
)

// Element builder functions
var (
	A              = internalhtml.A
	Abbr           = internalhtml.Abbr
	Address        = internalhtml.Address
	Area           = internalhtml.Area
	Article        = internalhtml.Article
	Aside          = internalhtml.Aside
	Audio          = internalhtml.Audio
	B              = internalhtml.B
	Base           = internalhtml.Base
	Bdi            = internalhtml.Bdi
	Bdo            = internalhtml.Bdo
	Blockquote     = internalhtml.Blockquote
	Body           = internalhtml.Body
	Br             = internalhtml.Br
	Button         = internalhtml.Button
	Canvas         = internalhtml.Canvas
	Caption        = internalhtml.Caption
	Circle         = internalhtml.Circle
	Cite           = internalhtml.Cite
	ClipPath       = internalhtml.ClipPath
	Code           = internalhtml.Code
	Col            = internalhtml.Col
	Colgroup       = internalhtml.Colgroup
	DataEl         = internalhtml.DataEl
	Datalist       = internalhtml.Datalist
	Dd             = internalhtml.Dd
	Defs           = internalhtml.Defs
	DelEl          = internalhtml.DelEl
	Details        = internalhtml.Details
	Dfn            = internalhtml.Dfn
	Dialog         = internalhtml.Dialog
	Div            = internalhtml.Div
	Dl             = internalhtml.Dl
	Dt             = internalhtml.Dt
	Ellipse        = internalhtml.Ellipse
	Em             = internalhtml.Em
	Embed          = internalhtml.Embed
	Fieldset       = internalhtml.Fieldset
	Figcaption     = internalhtml.Figcaption
	Figure         = internalhtml.Figure
	Footer         = internalhtml.Footer
	ForeignObject  = internalhtml.ForeignObject
	Form           = internalhtml.Form
	G              = internalhtml.G
	H1             = internalhtml.H1
	H2             = internalhtml.H2
	H3             = internalhtml.H3
	H4             = internalhtml.H4
	H5             = internalhtml.H5
	H6             = internalhtml.H6
	Head           = internalhtml.Head
	Header         = internalhtml.Header
	Hgroup         = internalhtml.Hgroup
	Hr             = internalhtml.Hr
	Html           = internalhtml.Html
	I              = internalhtml.I
	Iframe         = internalhtml.Iframe
	Image          = internalhtml.Image
	Img            = internalhtml.Img
	Input          = internalhtml.Input
	InsEl          = internalhtml.InsEl
	Kbd            = internalhtml.Kbd
	Label          = internalhtml.Label
	Legend         = internalhtml.Legend
	Li             = internalhtml.Li
	Line           = internalhtml.Line
	LinearGradient = internalhtml.LinearGradient
	Link           = internalhtml.Link
	Main           = internalhtml.Main
	MapEl          = internalhtml.MapEl
	Mark           = internalhtml.Mark
	Marker         = internalhtml.Marker
	Mask           = internalhtml.Mask
	Menu           = internalhtml.Menu
	MenuItem       = internalhtml.MenuItem
	Meta           = internalhtml.Meta
	Meter          = internalhtml.Meter
	Nav            = internalhtml.Nav
	Noscript       = internalhtml.Noscript
	Object         = internalhtml.Object
	Ol             = internalhtml.Ol
	Optgroup       = internalhtml.Optgroup
	Option         = internalhtml.Option
	Output         = internalhtml.Output
	P              = internalhtml.P
	Param          = internalhtml.Param
	Path           = internalhtml.Path
	Pattern        = internalhtml.Pattern
	Picture        = internalhtml.Picture
	Polygon        = internalhtml.Polygon
	Polyline       = internalhtml.Polyline
	Portal         = internalhtml.Portal
	Pre            = internalhtml.Pre
	Progress       = internalhtml.Progress
	Q              = internalhtml.Q
	RadialGradient = internalhtml.RadialGradient
	Rb             = internalhtml.Rb
	Rect           = internalhtml.Rect
	Rp             = internalhtml.Rp
	Rt             = internalhtml.Rt
	Rtc            = internalhtml.Rtc
	Ruby           = internalhtml.Ruby
	S              = internalhtml.S
	Samp           = internalhtml.Samp
	Script         = internalhtml.Script
	Section        = internalhtml.Section
	Select         = internalhtml.Select
	Slot           = internalhtml.Slot
	Small          = internalhtml.Small
	Source         = internalhtml.Source
	Span           = internalhtml.Span
	Stop           = internalhtml.Stop
	Strong         = internalhtml.Strong
	StyleEl        = internalhtml.StyleEl
	Sub            = internalhtml.Sub
	Summary        = internalhtml.Summary
	Sup            = internalhtml.Sup
	Svg            = internalhtml.Svg
	SvgText        = internalhtml.SvgText
	TSpan          = internalhtml.TSpan
	Table          = internalhtml.Table
	Tbody          = internalhtml.Tbody
	Td             = internalhtml.Td
	Template       = internalhtml.Template
	Textarea       = internalhtml.Textarea
	Tfoot          = internalhtml.Tfoot
	Th             = internalhtml.Th
	Thead          = internalhtml.Thead
	Time           = internalhtml.Time
	TitleEl        = internalhtml.TitleEl
	Tr             = internalhtml.Tr
	Track          = internalhtml.Track
	U              = internalhtml.U
	Ul             = internalhtml.Ul
	Use            = internalhtml.Use
	Var            = internalhtml.Var
	Video          = internalhtml.Video
	Wbr            = internalhtml.Wbr
)

// Element ref types
type (
	ARef              = internalhtml.ARef
	AbbrRef           = internalhtml.AbbrRef
	AddressRef        = internalhtml.AddressRef
	AreaRef           = internalhtml.AreaRef
	ArticleRef        = internalhtml.ArticleRef
	AsideRef          = internalhtml.AsideRef
	AudioRef          = internalhtml.AudioRef
	BRef              = internalhtml.BRef
	BaseRef           = internalhtml.BaseRef
	BdiRef            = internalhtml.BdiRef
	BdoRef            = internalhtml.BdoRef
	BlockquoteRef     = internalhtml.BlockquoteRef
	BodyRef           = internalhtml.BodyRef
	BrRef             = internalhtml.BrRef
	ButtonRef         = internalhtml.ButtonRef
	CanvasRef         = internalhtml.CanvasRef
	CaptionRef        = internalhtml.CaptionRef
	CircleRef         = internalhtml.CircleRef
	CiteRef           = internalhtml.CiteRef
	ClipPathRef       = internalhtml.ClipPathRef
	CodeRef           = internalhtml.CodeRef
	ColRef            = internalhtml.ColRef
	ColgroupRef       = internalhtml.ColgroupRef
	DataElRef         = internalhtml.DataElRef
	DatalistRef       = internalhtml.DatalistRef
	DdRef             = internalhtml.DdRef
	DefsRef           = internalhtml.DefsRef
	DelElRef          = internalhtml.DelElRef
	DetailsRef        = internalhtml.DetailsRef
	DfnRef            = internalhtml.DfnRef
	DialogRef         = internalhtml.DialogRef
	DivRef            = internalhtml.DivRef
	DlRef             = internalhtml.DlRef
	DtRef             = internalhtml.DtRef
	EllipseRef        = internalhtml.EllipseRef
	EmRef             = internalhtml.EmRef
	EmbedRef          = internalhtml.EmbedRef
	FieldsetRef       = internalhtml.FieldsetRef
	FigcaptionRef     = internalhtml.FigcaptionRef
	FigureRef         = internalhtml.FigureRef
	FooterRef         = internalhtml.FooterRef
	ForeignObjectRef  = internalhtml.ForeignObjectRef
	FormRef           = internalhtml.FormRef
	GRef              = internalhtml.GRef
	H1Ref             = internalhtml.H1Ref
	H2Ref             = internalhtml.H2Ref
	H3Ref             = internalhtml.H3Ref
	H4Ref             = internalhtml.H4Ref
	H5Ref             = internalhtml.H5Ref
	H6Ref             = internalhtml.H6Ref
	HeadRef           = internalhtml.HeadRef
	HeaderRef         = internalhtml.HeaderRef
	HgroupRef         = internalhtml.HgroupRef
	HrRef             = internalhtml.HrRef
	HtmlRef           = internalhtml.HtmlRef
	IRef              = internalhtml.IRef
	IframeRef         = internalhtml.IframeRef
	ImageRef          = internalhtml.ImageRef
	ImgRef            = internalhtml.ImgRef
	InputRef          = internalhtml.InputRef
	InsElRef          = internalhtml.InsElRef
	KbdRef            = internalhtml.KbdRef
	LabelRef          = internalhtml.LabelRef
	LegendRef         = internalhtml.LegendRef
	LiRef             = internalhtml.LiRef
	LineRef           = internalhtml.LineRef
	LinearGradientRef = internalhtml.LinearGradientRef
	LinkRef           = internalhtml.LinkRef
	MainRef           = internalhtml.MainRef
	MapElRef          = internalhtml.MapElRef
	MarkRef           = internalhtml.MarkRef
	MarkerRef         = internalhtml.MarkerRef
	MaskRef           = internalhtml.MaskRef
	MenuRef           = internalhtml.MenuRef
	MenuItemRef       = internalhtml.MenuItemRef
	MetaRef           = internalhtml.MetaRef
	MeterRef          = internalhtml.MeterRef
	NavRef            = internalhtml.NavRef
	NoscriptRef       = internalhtml.NoscriptRef
	ObjectRef         = internalhtml.ObjectRef
	OlRef             = internalhtml.OlRef
	OptgroupRef       = internalhtml.OptgroupRef
	OptionRef         = internalhtml.OptionRef
	OutputRef         = internalhtml.OutputRef
	PRef              = internalhtml.PRef
	ParamRef          = internalhtml.ParamRef
	PathRef           = internalhtml.PathRef
	PatternRef        = internalhtml.PatternRef
	PictureRef        = internalhtml.PictureRef
	PolygonRef        = internalhtml.PolygonRef
	PolylineRef       = internalhtml.PolylineRef
	PortalRef         = internalhtml.PortalRef
	PreRef            = internalhtml.PreRef
	ProgressRef       = internalhtml.ProgressRef
	QRef              = internalhtml.QRef
	RadialGradientRef = internalhtml.RadialGradientRef
	RbRef             = internalhtml.RbRef
	RectRef           = internalhtml.RectRef
	RpRef             = internalhtml.RpRef
	RtRef             = internalhtml.RtRef
	RtcRef            = internalhtml.RtcRef
	RubyRef           = internalhtml.RubyRef
	SRef              = internalhtml.SRef
	SampRef           = internalhtml.SampRef
	ScriptRef         = internalhtml.ScriptRef
	SectionRef        = internalhtml.SectionRef
	SelectRef         = internalhtml.SelectRef
	SlotRef           = internalhtml.SlotRef
	SmallRef          = internalhtml.SmallRef
	SourceRef         = internalhtml.SourceRef
	SpanRef           = internalhtml.SpanRef
	StopRef           = internalhtml.StopRef
	StrongRef         = internalhtml.StrongRef
	StyleElRef        = internalhtml.StyleElRef
	SubRef            = internalhtml.SubRef
	SummaryRef        = internalhtml.SummaryRef
	SupRef            = internalhtml.SupRef
	SvgRef            = internalhtml.SvgRef
	SvgTextRef        = internalhtml.SvgTextRef
	TSpanRef          = internalhtml.TSpanRef
	TableRef          = internalhtml.TableRef
	TbodyRef          = internalhtml.TbodyRef
	TdRef             = internalhtml.TdRef
	TemplateRef       = internalhtml.TemplateRef
	TextareaRef       = internalhtml.TextareaRef
	TfootRef          = internalhtml.TfootRef
	ThRef             = internalhtml.ThRef
	TheadRef          = internalhtml.TheadRef
	TimeRef           = internalhtml.TimeRef
	TitleElRef        = internalhtml.TitleElRef
	TrRef             = internalhtml.TrRef
	TrackRef          = internalhtml.TrackRef
	URef              = internalhtml.URef
	UlRef             = internalhtml.UlRef
	UseRef            = internalhtml.UseRef
	VarRef            = internalhtml.VarRef
	VideoRef          = internalhtml.VideoRef
	WbrRef            = internalhtml.WbrRef
)

func UseA(ctx Ctx) *ARef {
	return internalhtml.UseA(ctx)
}

func UseAbbr(ctx Ctx) *AbbrRef {
	return internalhtml.UseAbbr(ctx)
}

func UseAddress(ctx Ctx) *AddressRef {
	return internalhtml.UseAddress(ctx)
}

func UseArea(ctx Ctx) *AreaRef {
	return internalhtml.UseArea(ctx)
}

func UseArticle(ctx Ctx) *ArticleRef {
	return internalhtml.UseArticle(ctx)
}

func UseAside(ctx Ctx) *AsideRef {
	return internalhtml.UseAside(ctx)
}

func UseAudio(ctx Ctx) *AudioRef {
	return internalhtml.UseAudio(ctx)
}

func UseB(ctx Ctx) *BRef {
	return internalhtml.UseB(ctx)
}

func UseBase(ctx Ctx) *BaseRef {
	return internalhtml.UseBase(ctx)
}

func UseBdi(ctx Ctx) *BdiRef {
	return internalhtml.UseBdi(ctx)
}

func UseBdo(ctx Ctx) *BdoRef {
	return internalhtml.UseBdo(ctx)
}

func UseBlockquote(ctx Ctx) *BlockquoteRef {
	return internalhtml.UseBlockquote(ctx)
}

func UseBody(ctx Ctx) *BodyRef {
	return internalhtml.UseBody(ctx)
}

func UseBr(ctx Ctx) *BrRef {
	return internalhtml.UseBr(ctx)
}

func UseButton(ctx Ctx) *ButtonRef {
	return internalhtml.UseButton(ctx)
}

func UseCanvas(ctx Ctx) *CanvasRef {
	return internalhtml.UseCanvas(ctx)
}

func UseCaption(ctx Ctx) *CaptionRef {
	return internalhtml.UseCaption(ctx)
}

func UseCircle(ctx Ctx) *CircleRef {
	return internalhtml.UseCircle(ctx)
}

func UseCite(ctx Ctx) *CiteRef {
	return internalhtml.UseCite(ctx)
}

func UseClipPath(ctx Ctx) *ClipPathRef {
	return internalhtml.UseClipPath(ctx)
}

func UseCode(ctx Ctx) *CodeRef {
	return internalhtml.UseCode(ctx)
}

func UseCol(ctx Ctx) *ColRef {
	return internalhtml.UseCol(ctx)
}

func UseColgroup(ctx Ctx) *ColgroupRef {
	return internalhtml.UseColgroup(ctx)
}

func UseDataEl(ctx Ctx) *DataElRef {
	return internalhtml.UseDataEl(ctx)
}

func UseDatalist(ctx Ctx) *DatalistRef {
	return internalhtml.UseDatalist(ctx)
}

func UseDd(ctx Ctx) *DdRef {
	return internalhtml.UseDd(ctx)
}

func UseDefs(ctx Ctx) *DefsRef {
	return internalhtml.UseDefs(ctx)
}

func UseDelEl(ctx Ctx) *DelElRef {
	return internalhtml.UseDelEl(ctx)
}

func UseDetails(ctx Ctx) *DetailsRef {
	return internalhtml.UseDetails(ctx)
}

func UseDfn(ctx Ctx) *DfnRef {
	return internalhtml.UseDfn(ctx)
}

func UseDialog(ctx Ctx) *DialogRef {
	return internalhtml.UseDialog(ctx)
}

func UseDiv(ctx Ctx) *DivRef {
	return internalhtml.UseDiv(ctx)
}

func UseDl(ctx Ctx) *DlRef {
	return internalhtml.UseDl(ctx)
}

func UseDt(ctx Ctx) *DtRef {
	return internalhtml.UseDt(ctx)
}

func UseEllipse(ctx Ctx) *EllipseRef {
	return internalhtml.UseEllipse(ctx)
}

func UseEm(ctx Ctx) *EmRef {
	return internalhtml.UseEm(ctx)
}

func UseEmbed(ctx Ctx) *EmbedRef {
	return internalhtml.UseEmbed(ctx)
}

func UseFieldset(ctx Ctx) *FieldsetRef {
	return internalhtml.UseFieldset(ctx)
}

func UseFigcaption(ctx Ctx) *FigcaptionRef {
	return internalhtml.UseFigcaption(ctx)
}

func UseFigure(ctx Ctx) *FigureRef {
	return internalhtml.UseFigure(ctx)
}

func UseFooter(ctx Ctx) *FooterRef {
	return internalhtml.UseFooter(ctx)
}

func UseForeignObject(ctx Ctx) *ForeignObjectRef {
	return internalhtml.UseForeignObject(ctx)
}

func UseForm(ctx Ctx) *FormRef {
	return internalhtml.UseForm(ctx)
}

func UseG(ctx Ctx) *GRef {
	return internalhtml.UseG(ctx)
}

func UseH1(ctx Ctx) *H1Ref {
	return internalhtml.UseH1(ctx)
}

func UseH2(ctx Ctx) *H2Ref {
	return internalhtml.UseH2(ctx)
}

func UseH3(ctx Ctx) *H3Ref {
	return internalhtml.UseH3(ctx)
}

func UseH4(ctx Ctx) *H4Ref {
	return internalhtml.UseH4(ctx)
}

func UseH5(ctx Ctx) *H5Ref {
	return internalhtml.UseH5(ctx)
}

func UseH6(ctx Ctx) *H6Ref {
	return internalhtml.UseH6(ctx)
}

func UseHead(ctx Ctx) *HeadRef {
	return internalhtml.UseHead(ctx)
}

func UseHeader(ctx Ctx) *HeaderRef {
	return internalhtml.UseHeader(ctx)
}

func UseHgroup(ctx Ctx) *HgroupRef {
	return internalhtml.UseHgroup(ctx)
}

func UseHr(ctx Ctx) *HrRef {
	return internalhtml.UseHr(ctx)
}

func UseHtml(ctx Ctx) *HtmlRef {
	return internalhtml.UseHtml(ctx)
}

func UseI(ctx Ctx) *IRef {
	return internalhtml.UseI(ctx)
}

func UseIframe(ctx Ctx) *IframeRef {
	return internalhtml.UseIframe(ctx)
}

func UseImage(ctx Ctx) *ImageRef {
	return internalhtml.UseImage(ctx)
}

func UseImg(ctx Ctx) *ImgRef {
	return internalhtml.UseImg(ctx)
}

func UseInput(ctx Ctx) *InputRef {
	return internalhtml.UseInput(ctx)
}

func UseInsEl(ctx Ctx) *InsElRef {
	return internalhtml.UseInsEl(ctx)
}

func UseKbd(ctx Ctx) *KbdRef {
	return internalhtml.UseKbd(ctx)
}

func UseLabel(ctx Ctx) *LabelRef {
	return internalhtml.UseLabel(ctx)
}

func UseLegend(ctx Ctx) *LegendRef {
	return internalhtml.UseLegend(ctx)
}

func UseLi(ctx Ctx) *LiRef {
	return internalhtml.UseLi(ctx)
}

func UseLine(ctx Ctx) *LineRef {
	return internalhtml.UseLine(ctx)
}

func UseLinearGradient(ctx Ctx) *LinearGradientRef {
	return internalhtml.UseLinearGradient(ctx)
}

func UseLink(ctx Ctx) *LinkRef {
	return internalhtml.UseLink(ctx)
}

func UseMain(ctx Ctx) *MainRef {
	return internalhtml.UseMain(ctx)
}

func UseMapEl(ctx Ctx) *MapElRef {
	return internalhtml.UseMapEl(ctx)
}

func UseMark(ctx Ctx) *MarkRef {
	return internalhtml.UseMark(ctx)
}

func UseMarker(ctx Ctx) *MarkerRef {
	return internalhtml.UseMarker(ctx)
}

func UseMask(ctx Ctx) *MaskRef {
	return internalhtml.UseMask(ctx)
}

func UseMenu(ctx Ctx) *MenuRef {
	return internalhtml.UseMenu(ctx)
}

func UseMenuItem(ctx Ctx) *MenuItemRef {
	return internalhtml.UseMenuItem(ctx)
}

func UseMeta(ctx Ctx) *MetaRef {
	return internalhtml.UseMeta(ctx)
}

func UseMeter(ctx Ctx) *MeterRef {
	return internalhtml.UseMeter(ctx)
}

func UseNav(ctx Ctx) *NavRef {
	return internalhtml.UseNav(ctx)
}

func UseNoscript(ctx Ctx) *NoscriptRef {
	return internalhtml.UseNoscript(ctx)
}

func UseObject(ctx Ctx) *ObjectRef {
	return internalhtml.UseObject(ctx)
}

func UseOl(ctx Ctx) *OlRef {
	return internalhtml.UseOl(ctx)
}

func UseOptgroup(ctx Ctx) *OptgroupRef {
	return internalhtml.UseOptgroup(ctx)
}

func UseOption(ctx Ctx) *OptionRef {
	return internalhtml.UseOption(ctx)
}

func UseOutput(ctx Ctx) *OutputRef {
	return internalhtml.UseOutput(ctx)
}

func UseP(ctx Ctx) *PRef {
	return internalhtml.UseP(ctx)
}

func UseParam(ctx Ctx) *ParamRef {
	return internalhtml.UseParam(ctx)
}

func UsePath(ctx Ctx) *PathRef {
	return internalhtml.UsePath(ctx)
}

func UsePattern(ctx Ctx) *PatternRef {
	return internalhtml.UsePattern(ctx)
}

func UsePicture(ctx Ctx) *PictureRef {
	return internalhtml.UsePicture(ctx)
}

func UsePolygon(ctx Ctx) *PolygonRef {
	return internalhtml.UsePolygon(ctx)
}

func UsePolyline(ctx Ctx) *PolylineRef {
	return internalhtml.UsePolyline(ctx)
}

func UsePortal(ctx Ctx) *PortalRef {
	return internalhtml.UsePortal(ctx)
}

func UsePre(ctx Ctx) *PreRef {
	return internalhtml.UsePre(ctx)
}

func UseProgress(ctx Ctx) *ProgressRef {
	return internalhtml.UseProgress(ctx)
}

func UseQ(ctx Ctx) *QRef {
	return internalhtml.UseQ(ctx)
}

func UseRadialGradient(ctx Ctx) *RadialGradientRef {
	return internalhtml.UseRadialGradient(ctx)
}

func UseRb(ctx Ctx) *RbRef {
	return internalhtml.UseRb(ctx)
}

func UseRect(ctx Ctx) *RectRef {
	return internalhtml.UseRect(ctx)
}

func UseRp(ctx Ctx) *RpRef {
	return internalhtml.UseRp(ctx)
}

func UseRt(ctx Ctx) *RtRef {
	return internalhtml.UseRt(ctx)
}

func UseRtc(ctx Ctx) *RtcRef {
	return internalhtml.UseRtc(ctx)
}

func UseRuby(ctx Ctx) *RubyRef {
	return internalhtml.UseRuby(ctx)
}

func UseS(ctx Ctx) *SRef {
	return internalhtml.UseS(ctx)
}

func UseSamp(ctx Ctx) *SampRef {
	return internalhtml.UseSamp(ctx)
}

func UseScript(ctx Ctx) *ScriptRef {
	return internalhtml.UseScript(ctx)
}

func UseSection(ctx Ctx) *SectionRef {
	return internalhtml.UseSection(ctx)
}

func UseSelect(ctx Ctx) *SelectRef {
	return internalhtml.UseSelect(ctx)
}

func UseSlot(ctx Ctx) *SlotRef {
	return internalhtml.UseSlot(ctx)
}

func UseSmall(ctx Ctx) *SmallRef {
	return internalhtml.UseSmall(ctx)
}

func UseSource(ctx Ctx) *SourceRef {
	return internalhtml.UseSource(ctx)
}

func UseSpan(ctx Ctx) *SpanRef {
	return internalhtml.UseSpan(ctx)
}

func UseStop(ctx Ctx) *StopRef {
	return internalhtml.UseStop(ctx)
}

func UseStrong(ctx Ctx) *StrongRef {
	return internalhtml.UseStrong(ctx)
}

func UseStyleEl(ctx Ctx) *StyleElRef {
	return internalhtml.UseStyleEl(ctx)
}

func UseSub(ctx Ctx) *SubRef {
	return internalhtml.UseSub(ctx)
}

func UseSummary(ctx Ctx) *SummaryRef {
	return internalhtml.UseSummary(ctx)
}

func UseSup(ctx Ctx) *SupRef {
	return internalhtml.UseSup(ctx)
}

func UseSvg(ctx Ctx) *SvgRef {
	return internalhtml.UseSvg(ctx)
}

func UseSvgText(ctx Ctx) *SvgTextRef {
	return internalhtml.UseSvgText(ctx)
}

func UseTSpan(ctx Ctx) *TSpanRef {
	return internalhtml.UseTSpan(ctx)
}

func UseTable(ctx Ctx) *TableRef {
	return internalhtml.UseTable(ctx)
}

func UseTbody(ctx Ctx) *TbodyRef {
	return internalhtml.UseTbody(ctx)
}

func UseTd(ctx Ctx) *TdRef {
	return internalhtml.UseTd(ctx)
}

func UseTemplate(ctx Ctx) *TemplateRef {
	return internalhtml.UseTemplate(ctx)
}

func UseTextarea(ctx Ctx) *TextareaRef {
	return internalhtml.UseTextarea(ctx)
}

func UseTfoot(ctx Ctx) *TfootRef {
	return internalhtml.UseTfoot(ctx)
}

func UseTh(ctx Ctx) *ThRef {
	return internalhtml.UseTh(ctx)
}

func UseThead(ctx Ctx) *TheadRef {
	return internalhtml.UseThead(ctx)
}

func UseTime(ctx Ctx) *TimeRef {
	return internalhtml.UseTime(ctx)
}

func UseTitleEl(ctx Ctx) *TitleElRef {
	return internalhtml.UseTitleEl(ctx)
}

func UseTr(ctx Ctx) *TrRef {
	return internalhtml.UseTr(ctx)
}

func UseTrack(ctx Ctx) *TrackRef {
	return internalhtml.UseTrack(ctx)
}

func UseU(ctx Ctx) *URef {
	return internalhtml.UseU(ctx)
}

func UseUl(ctx Ctx) *UlRef {
	return internalhtml.UseUl(ctx)
}

func UseUse(ctx Ctx) *UseRef {
	return internalhtml.UseUse(ctx)
}

func UseVar(ctx Ctx) *VarRef {
	return internalhtml.UseVar(ctx)
}

func UseVideo(ctx Ctx) *VideoRef {
	return internalhtml.UseVideo(ctx)
}

func UseWbr(ctx Ctx) *WbrRef {
	return internalhtml.UseWbr(ctx)
}
