// Code generated by tags_gen.go; DO NOT EDIT.
// Package html provides public re-exports from internal/html.
package html

import internalhtml "github.com/eleven-am/pondlive/go/internal/html"

// Element descriptor types
type (
	HTMLAElement             = internalhtml.HTMLAElement
	HTMLAbbrElement          = internalhtml.HTMLAbbrElement
	HTMLAddressElement       = internalhtml.HTMLAddressElement
	HTMLAreaElement          = internalhtml.HTMLAreaElement
	HTMLArticleElement       = internalhtml.HTMLArticleElement
	HTMLAsideElement         = internalhtml.HTMLAsideElement
	HTMLAudioElement         = internalhtml.HTMLAudioElement
	HTMLBElement             = internalhtml.HTMLBElement
	HTMLBaseElement          = internalhtml.HTMLBaseElement
	HTMLBdiElement           = internalhtml.HTMLBdiElement
	HTMLBdoElement           = internalhtml.HTMLBdoElement
	HTMLBlockquoteElement    = internalhtml.HTMLBlockquoteElement
	HTMLBodyElement          = internalhtml.HTMLBodyElement
	HTMLBrElement            = internalhtml.HTMLBrElement
	HTMLButtonElement        = internalhtml.HTMLButtonElement
	HTMLCanvasElement        = internalhtml.HTMLCanvasElement
	HTMLCaptionElement       = internalhtml.HTMLCaptionElement
	SVGCircleElement         = internalhtml.SVGCircleElement
	HTMLCiteElement          = internalhtml.HTMLCiteElement
	SVGClipPathElement       = internalhtml.SVGClipPathElement
	HTMLCodeElement          = internalhtml.HTMLCodeElement
	HTMLColElement           = internalhtml.HTMLColElement
	HTMLColgroupElement      = internalhtml.HTMLColgroupElement
	HTMLDataElement          = internalhtml.HTMLDataElement
	HTMLDatalistElement      = internalhtml.HTMLDatalistElement
	HTMLDdElement            = internalhtml.HTMLDdElement
	SVGDefsElement           = internalhtml.SVGDefsElement
	HTMLDelElement           = internalhtml.HTMLDelElement
	HTMLDetailsElement       = internalhtml.HTMLDetailsElement
	HTMLDfnElement           = internalhtml.HTMLDfnElement
	HTMLDialogElement        = internalhtml.HTMLDialogElement
	HTMLDivElement           = internalhtml.HTMLDivElement
	HTMLDlElement            = internalhtml.HTMLDlElement
	HTMLDtElement            = internalhtml.HTMLDtElement
	SVGEllipseElement        = internalhtml.SVGEllipseElement
	HTMLEmElement            = internalhtml.HTMLEmElement
	HTMLEmbedElement         = internalhtml.HTMLEmbedElement
	HTMLFieldsetElement      = internalhtml.HTMLFieldsetElement
	HTMLFigcaptionElement    = internalhtml.HTMLFigcaptionElement
	HTMLFigureElement        = internalhtml.HTMLFigureElement
	HTMLFooterElement        = internalhtml.HTMLFooterElement
	SVGForeignObjectElement  = internalhtml.SVGForeignObjectElement
	HTMLFormElement          = internalhtml.HTMLFormElement
	SVGGElement              = internalhtml.SVGGElement
	HTMLH1Element            = internalhtml.HTMLH1Element
	HTMLH2Element            = internalhtml.HTMLH2Element
	HTMLH3Element            = internalhtml.HTMLH3Element
	HTMLH4Element            = internalhtml.HTMLH4Element
	HTMLH5Element            = internalhtml.HTMLH5Element
	HTMLH6Element            = internalhtml.HTMLH6Element
	HTMLHeadElement          = internalhtml.HTMLHeadElement
	HTMLHeaderElement        = internalhtml.HTMLHeaderElement
	HTMLHgroupElement        = internalhtml.HTMLHgroupElement
	HTMLHrElement            = internalhtml.HTMLHrElement
	HTMLHtmlElement          = internalhtml.HTMLHtmlElement
	HTMLIElement             = internalhtml.HTMLIElement
	HTMLIframeElement        = internalhtml.HTMLIframeElement
	SVGImageElement          = internalhtml.SVGImageElement
	HTMLImgElement           = internalhtml.HTMLImgElement
	HTMLInputElement         = internalhtml.HTMLInputElement
	HTMLInsElement           = internalhtml.HTMLInsElement
	HTMLKbdElement           = internalhtml.HTMLKbdElement
	HTMLLabelElement         = internalhtml.HTMLLabelElement
	HTMLLegendElement        = internalhtml.HTMLLegendElement
	HTMLLiElement            = internalhtml.HTMLLiElement
	SVGLineElement           = internalhtml.SVGLineElement
	SVGLinearGradientElement = internalhtml.SVGLinearGradientElement
	HTMLLinkElement          = internalhtml.HTMLLinkElement
	HTMLMainElement          = internalhtml.HTMLMainElement
	HTMLMapElement           = internalhtml.HTMLMapElement
	HTMLMarkElement          = internalhtml.HTMLMarkElement
	SVGMarkerElement         = internalhtml.SVGMarkerElement
	SVGMaskElement           = internalhtml.SVGMaskElement
	HTMLMenuElement          = internalhtml.HTMLMenuElement
	HTMLMenuItemElement      = internalhtml.HTMLMenuItemElement
	HTMLMetaElement          = internalhtml.HTMLMetaElement
	HTMLMeterElement         = internalhtml.HTMLMeterElement
	HTMLNavElement           = internalhtml.HTMLNavElement
	HTMLNoscriptElement      = internalhtml.HTMLNoscriptElement
	HTMLObjectElement        = internalhtml.HTMLObjectElement
	HTMLOlElement            = internalhtml.HTMLOlElement
	HTMLOptgroupElement      = internalhtml.HTMLOptgroupElement
	HTMLOptionElement        = internalhtml.HTMLOptionElement
	HTMLOutputElement        = internalhtml.HTMLOutputElement
	HTMLPElement             = internalhtml.HTMLPElement
	HTMLParamElement         = internalhtml.HTMLParamElement
	SVGPathElement           = internalhtml.SVGPathElement
	SVGPatternElement        = internalhtml.SVGPatternElement
	HTMLPictureElement       = internalhtml.HTMLPictureElement
	SVGPolygonElement        = internalhtml.SVGPolygonElement
	SVGPolylineElement       = internalhtml.SVGPolylineElement
	HTMLPortalElement        = internalhtml.HTMLPortalElement
	HTMLPreElement           = internalhtml.HTMLPreElement
	HTMLProgressElement      = internalhtml.HTMLProgressElement
	HTMLQElement             = internalhtml.HTMLQElement
	SVGRadialGradientElement = internalhtml.SVGRadialGradientElement
	HTMLRbElement            = internalhtml.HTMLRbElement
	SVGRectElement           = internalhtml.SVGRectElement
	HTMLRpElement            = internalhtml.HTMLRpElement
	HTMLRtElement            = internalhtml.HTMLRtElement
	HTMLRtcElement           = internalhtml.HTMLRtcElement
	HTMLRubyElement          = internalhtml.HTMLRubyElement
	HTMLSElement             = internalhtml.HTMLSElement
	HTMLSampElement          = internalhtml.HTMLSampElement
	HTMLScriptElement        = internalhtml.HTMLScriptElement
	HTMLSectionElement       = internalhtml.HTMLSectionElement
	HTMLSelectElement        = internalhtml.HTMLSelectElement
	HTMLSlotElement          = internalhtml.HTMLSlotElement
	HTMLSmallElement         = internalhtml.HTMLSmallElement
	HTMLSourceElement        = internalhtml.HTMLSourceElement
	HTMLSpanElement          = internalhtml.HTMLSpanElement
	SVGStopElement           = internalhtml.SVGStopElement
	HTMLStrongElement        = internalhtml.HTMLStrongElement
	HTMLStyleElement         = internalhtml.HTMLStyleElement
	HTMLSubElement           = internalhtml.HTMLSubElement
	HTMLSummaryElement       = internalhtml.HTMLSummaryElement
	HTMLSupElement           = internalhtml.HTMLSupElement
	SVGSvgElement            = internalhtml.SVGSvgElement
	SVGSvgTextElement        = internalhtml.SVGSvgTextElement
	SVGTSpanElement          = internalhtml.SVGTSpanElement
	HTMLTableElement         = internalhtml.HTMLTableElement
	HTMLTbodyElement         = internalhtml.HTMLTbodyElement
	HTMLTdElement            = internalhtml.HTMLTdElement
	HTMLTemplateElement      = internalhtml.HTMLTemplateElement
	HTMLTextareaElement      = internalhtml.HTMLTextareaElement
	HTMLTfootElement         = internalhtml.HTMLTfootElement
	HTMLThElement            = internalhtml.HTMLThElement
	HTMLTheadElement         = internalhtml.HTMLTheadElement
	HTMLTimeElement          = internalhtml.HTMLTimeElement
	HTMLTitleElement         = internalhtml.HTMLTitleElement
	HTMLTrElement            = internalhtml.HTMLTrElement
	HTMLTrackElement         = internalhtml.HTMLTrackElement
	HTMLUElement             = internalhtml.HTMLUElement
	HTMLUlElement            = internalhtml.HTMLUlElement
	SVGUseElement            = internalhtml.SVGUseElement
	HTMLVarElement           = internalhtml.HTMLVarElement
	HTMLVideoElement         = internalhtml.HTMLVideoElement
	HTMLWbrElement           = internalhtml.HTMLWbrElement
)

// A creates an <a> element.
func A(items ...Item) *Element {
	return internalhtml.El(HTMLAElement{}, "a", items...)
}

// Abbr creates an <abbr> element.
func Abbr(items ...Item) *Element {
	return internalhtml.El(HTMLAbbrElement{}, "abbr", items...)
}

// Address creates an <address> element.
func Address(items ...Item) *Element {
	return internalhtml.El(HTMLAddressElement{}, "address", items...)
}

// Area creates an <area> element.
func Area(items ...Item) *Element {
	return internalhtml.El(HTMLAreaElement{}, "area", items...)
}

// Article creates an <article> element.
func Article(items ...Item) *Element {
	return internalhtml.El(HTMLArticleElement{}, "article", items...)
}

// Aside creates an <aside> element.
func Aside(items ...Item) *Element {
	return internalhtml.El(HTMLAsideElement{}, "aside", items...)
}

// Audio creates an <audio> element.
func Audio(items ...Item) *Element {
	return internalhtml.El(HTMLAudioElement{}, "audio", items...)
}

// B creates a <b> element.
func B(items ...Item) *Element {
	return internalhtml.El(HTMLBElement{}, "b", items...)
}

// Base creates a <base> element.
func Base(items ...Item) *Element {
	return internalhtml.El(HTMLBaseElement{}, "base", items...)
}

// Bdi creates a <bdi> element.
func Bdi(items ...Item) *Element {
	return internalhtml.El(HTMLBdiElement{}, "bdi", items...)
}

// Bdo creates a <bdo> element.
func Bdo(items ...Item) *Element {
	return internalhtml.El(HTMLBdoElement{}, "bdo", items...)
}

// Blockquote creates a <blockquote> element.
func Blockquote(items ...Item) *Element {
	return internalhtml.El(HTMLBlockquoteElement{}, "blockquote", items...)
}

// Body creates a <body> element.
func Body(items ...Item) *Element {
	return internalhtml.El(HTMLBodyElement{}, "body", items...)
}

// Br creates a <br> element.
func Br(items ...Item) *Element {
	return internalhtml.El(HTMLBrElement{}, "br", items...)
}

// Button creates a <button> element.
func Button(items ...Item) *Element {
	return internalhtml.El(HTMLButtonElement{}, "button", items...)
}

// Canvas creates a <canvas> element.
func Canvas(items ...Item) *Element {
	return internalhtml.El(HTMLCanvasElement{}, "canvas", items...)
}

// Caption creates a <caption> element.
func Caption(items ...Item) *Element {
	return internalhtml.El(HTMLCaptionElement{}, "caption", items...)
}

// Circle creates a <circle> element.
func Circle(items ...Item) *Element {
	return internalhtml.El(SVGCircleElement{}, "circle", items...)
}

// Cite creates a <cite> element.
func Cite(items ...Item) *Element {
	return internalhtml.El(HTMLCiteElement{}, "cite", items...)
}

// ClipPath creates a <clipPath> element.
func ClipPath(items ...Item) *Element {
	return internalhtml.El(SVGClipPathElement{}, "clipPath", items...)
}

// Code creates a <code> element.
func Code(items ...Item) *Element {
	return internalhtml.El(HTMLCodeElement{}, "code", items...)
}

// Col creates a <col> element.
func Col(items ...Item) *Element {
	return internalhtml.El(HTMLColElement{}, "col", items...)
}

// Colgroup creates a <colgroup> element.
func Colgroup(items ...Item) *Element {
	return internalhtml.El(HTMLColgroupElement{}, "colgroup", items...)
}

// DataEl creates a <data> element.
func DataEl(items ...Item) *Element {
	return internalhtml.El(HTMLDataElement{}, "data", items...)
}

// Datalist creates a <datalist> element.
func Datalist(items ...Item) *Element {
	return internalhtml.El(HTMLDatalistElement{}, "datalist", items...)
}

// Dd creates a <dd> element.
func Dd(items ...Item) *Element {
	return internalhtml.El(HTMLDdElement{}, "dd", items...)
}

// Defs creates a <defs> element.
func Defs(items ...Item) *Element {
	return internalhtml.El(SVGDefsElement{}, "defs", items...)
}

// DelEl creates a <del> element.
func DelEl(items ...Item) *Element {
	return internalhtml.El(HTMLDelElement{}, "del", items...)
}

// Details creates a <details> element.
func Details(items ...Item) *Element {
	return internalhtml.El(HTMLDetailsElement{}, "details", items...)
}

// Dfn creates a <dfn> element.
func Dfn(items ...Item) *Element {
	return internalhtml.El(HTMLDfnElement{}, "dfn", items...)
}

// Dialog creates a <dialog> element.
func Dialog(items ...Item) *Element {
	return internalhtml.El(HTMLDialogElement{}, "dialog", items...)
}

// Div creates a <div> element.
func Div(items ...Item) *Element {
	return internalhtml.El(HTMLDivElement{}, "div", items...)
}

// Dl creates a <dl> element.
func Dl(items ...Item) *Element {
	return internalhtml.El(HTMLDlElement{}, "dl", items...)
}

// Dt creates a <dt> element.
func Dt(items ...Item) *Element {
	return internalhtml.El(HTMLDtElement{}, "dt", items...)
}

// Ellipse creates an <ellipse> element.
func Ellipse(items ...Item) *Element {
	return internalhtml.El(SVGEllipseElement{}, "ellipse", items...)
}

// Em creates an <em> element.
func Em(items ...Item) *Element {
	return internalhtml.El(HTMLEmElement{}, "em", items...)
}

// Embed creates an <embed> element.
func Embed(items ...Item) *Element {
	return internalhtml.El(HTMLEmbedElement{}, "embed", items...)
}

// Fieldset creates a <fieldset> element.
func Fieldset(items ...Item) *Element {
	return internalhtml.El(HTMLFieldsetElement{}, "fieldset", items...)
}

// Figcaption creates a <figcaption> element.
func Figcaption(items ...Item) *Element {
	return internalhtml.El(HTMLFigcaptionElement{}, "figcaption", items...)
}

// Figure creates a <figure> element.
func Figure(items ...Item) *Element {
	return internalhtml.El(HTMLFigureElement{}, "figure", items...)
}

// Footer creates a <footer> element.
func Footer(items ...Item) *Element {
	return internalhtml.El(HTMLFooterElement{}, "footer", items...)
}

// ForeignObject creates a <foreignObject> element.
func ForeignObject(items ...Item) *Element {
	return internalhtml.El(SVGForeignObjectElement{}, "foreignObject", items...)
}

// Form creates a <form> element.
func Form(items ...Item) *Element {
	return internalhtml.El(HTMLFormElement{}, "form", items...)
}

// G creates a <g> element.
func G(items ...Item) *Element {
	return internalhtml.El(SVGGElement{}, "g", items...)
}

// H1 creates an <h1> element.
func H1(items ...Item) *Element {
	return internalhtml.El(HTMLH1Element{}, "h1", items...)
}

// H2 creates an <h2> element.
func H2(items ...Item) *Element {
	return internalhtml.El(HTMLH2Element{}, "h2", items...)
}

// H3 creates an <h3> element.
func H3(items ...Item) *Element {
	return internalhtml.El(HTMLH3Element{}, "h3", items...)
}

// H4 creates an <h4> element.
func H4(items ...Item) *Element {
	return internalhtml.El(HTMLH4Element{}, "h4", items...)
}

// H5 creates an <h5> element.
func H5(items ...Item) *Element {
	return internalhtml.El(HTMLH5Element{}, "h5", items...)
}

// H6 creates an <h6> element.
func H6(items ...Item) *Element {
	return internalhtml.El(HTMLH6Element{}, "h6", items...)
}

// Head creates a <head> element.
func Head(items ...Item) *Element {
	return internalhtml.El(HTMLHeadElement{}, "head", items...)
}

// Header creates a <header> element.
func Header(items ...Item) *Element {
	return internalhtml.El(HTMLHeaderElement{}, "header", items...)
}

// Hgroup creates an <hgroup> element.
func Hgroup(items ...Item) *Element {
	return internalhtml.El(HTMLHgroupElement{}, "hgroup", items...)
}

// Hr creates an <hr> element.
func Hr(items ...Item) *Element {
	return internalhtml.El(HTMLHrElement{}, "hr", items...)
}

// Html creates an <html> element.
func Html(items ...Item) *Element {
	return internalhtml.El(HTMLHtmlElement{}, "html", items...)
}

// I creates an <i> element.
func I(items ...Item) *Element {
	return internalhtml.El(HTMLIElement{}, "i", items...)
}

// Iframe creates an <iframe> element.
func Iframe(items ...Item) *Element {
	return internalhtml.El(HTMLIframeElement{}, "iframe", items...)
}

// Image creates an <image> element.
func Image(items ...Item) *Element {
	return internalhtml.El(SVGImageElement{}, "image", items...)
}

// Img creates an <img> element.
func Img(items ...Item) *Element {
	return internalhtml.El(HTMLImgElement{}, "img", items...)
}

// Input creates an <input> element.
func Input(items ...Item) *Element {
	return internalhtml.El(HTMLInputElement{}, "input", items...)
}

// InsEl creates an <ins> element.
func InsEl(items ...Item) *Element {
	return internalhtml.El(HTMLInsElement{}, "ins", items...)
}

// Kbd creates a <kbd> element.
func Kbd(items ...Item) *Element {
	return internalhtml.El(HTMLKbdElement{}, "kbd", items...)
}

// Label creates a <label> element.
func Label(items ...Item) *Element {
	return internalhtml.El(HTMLLabelElement{}, "label", items...)
}

// Legend creates a <legend> element.
func Legend(items ...Item) *Element {
	return internalhtml.El(HTMLLegendElement{}, "legend", items...)
}

// Li creates an <li> element.
func Li(items ...Item) *Element {
	return internalhtml.El(HTMLLiElement{}, "li", items...)
}

// Line creates a <line> element.
func Line(items ...Item) *Element {
	return internalhtml.El(SVGLineElement{}, "line", items...)
}

// LinearGradient creates a <linearGradient> element.
func LinearGradient(items ...Item) *Element {
	return internalhtml.El(SVGLinearGradientElement{}, "linearGradient", items...)
}

// Link creates a <link> element.
func Link(items ...Item) *Element {
	return internalhtml.El(HTMLLinkElement{}, "link", items...)
}

// Main creates a <main> element.
func Main(items ...Item) *Element {
	return internalhtml.El(HTMLMainElement{}, "main", items...)
}

// MapEl creates a <map> element.
func MapEl(items ...Item) *Element {
	return internalhtml.El(HTMLMapElement{}, "map", items...)
}

// Mark creates a <mark> element.
func Mark(items ...Item) *Element {
	return internalhtml.El(HTMLMarkElement{}, "mark", items...)
}

// Marker creates a <marker> element.
func Marker(items ...Item) *Element {
	return internalhtml.El(SVGMarkerElement{}, "marker", items...)
}

// Mask creates a <mask> element.
func Mask(items ...Item) *Element {
	return internalhtml.El(SVGMaskElement{}, "mask", items...)
}

// Menu creates a <menu> element.
func Menu(items ...Item) *Element {
	return internalhtml.El(HTMLMenuElement{}, "menu", items...)
}

// MenuItem creates a <menuitem> element.
func MenuItem(items ...Item) *Element {
	return internalhtml.El(HTMLMenuItemElement{}, "menuitem", items...)
}

// Meta creates a <meta> element.
func Meta(items ...Item) *Element {
	return internalhtml.El(HTMLMetaElement{}, "meta", items...)
}

// Meter creates a <meter> element.
func Meter(items ...Item) *Element {
	return internalhtml.El(HTMLMeterElement{}, "meter", items...)
}

// Nav creates a <nav> element.
func Nav(items ...Item) *Element {
	return internalhtml.El(HTMLNavElement{}, "nav", items...)
}

// Noscript creates a <noscript> element.
func Noscript(items ...Item) *Element {
	return internalhtml.El(HTMLNoscriptElement{}, "noscript", items...)
}

// Object creates an <object> element.
func Object(items ...Item) *Element {
	return internalhtml.El(HTMLObjectElement{}, "object", items...)
}

// Ol creates an <ol> element.
func Ol(items ...Item) *Element {
	return internalhtml.El(HTMLOlElement{}, "ol", items...)
}

// Optgroup creates an <optgroup> element.
func Optgroup(items ...Item) *Element {
	return internalhtml.El(HTMLOptgroupElement{}, "optgroup", items...)
}

// Option creates an <option> element.
func Option(items ...Item) *Element {
	return internalhtml.El(HTMLOptionElement{}, "option", items...)
}

// Output creates an <output> element.
func Output(items ...Item) *Element {
	return internalhtml.El(HTMLOutputElement{}, "output", items...)
}

// P creates a <p> element.
func P(items ...Item) *Element {
	return internalhtml.El(HTMLPElement{}, "p", items...)
}

// Param creates a <param> element.
func Param(items ...Item) *Element {
	return internalhtml.El(HTMLParamElement{}, "param", items...)
}

// Path creates a <path> element.
func Path(items ...Item) *Element {
	return internalhtml.El(SVGPathElement{}, "path", items...)
}

// Pattern creates a <pattern> element.
func Pattern(items ...Item) *Element {
	return internalhtml.El(SVGPatternElement{}, "pattern", items...)
}

// Picture creates a <picture> element.
func Picture(items ...Item) *Element {
	return internalhtml.El(HTMLPictureElement{}, "picture", items...)
}

// Polygon creates a <polygon> element.
func Polygon(items ...Item) *Element {
	return internalhtml.El(SVGPolygonElement{}, "polygon", items...)
}

// Polyline creates a <polyline> element.
func Polyline(items ...Item) *Element {
	return internalhtml.El(SVGPolylineElement{}, "polyline", items...)
}

// Portal creates a <portal> element.
func Portal(items ...Item) *Element {
	return internalhtml.El(HTMLPortalElement{}, "portal", items...)
}

// Pre creates a <pre> element.
func Pre(items ...Item) *Element {
	return internalhtml.El(HTMLPreElement{}, "pre", items...)
}

// Progress creates a <progress> element.
func Progress(items ...Item) *Element {
	return internalhtml.El(HTMLProgressElement{}, "progress", items...)
}

// Q creates a <q> element.
func Q(items ...Item) *Element {
	return internalhtml.El(HTMLQElement{}, "q", items...)
}

// RadialGradient creates a <radialGradient> element.
func RadialGradient(items ...Item) *Element {
	return internalhtml.El(SVGRadialGradientElement{}, "radialGradient", items...)
}

// Rb creates an <rb> element.
func Rb(items ...Item) *Element {
	return internalhtml.El(HTMLRbElement{}, "rb", items...)
}

// Rect creates a <rect> element.
func Rect(items ...Item) *Element {
	return internalhtml.El(SVGRectElement{}, "rect", items...)
}

// Rp creates an <rp> element.
func Rp(items ...Item) *Element {
	return internalhtml.El(HTMLRpElement{}, "rp", items...)
}

// Rt creates an <rt> element.
func Rt(items ...Item) *Element {
	return internalhtml.El(HTMLRtElement{}, "rt", items...)
}

// Rtc creates a <rtc> element.
func Rtc(items ...Item) *Element {
	return internalhtml.El(HTMLRtcElement{}, "rtc", items...)
}

// Ruby creates a <ruby> element.
func Ruby(items ...Item) *Element {
	return internalhtml.El(HTMLRubyElement{}, "ruby", items...)
}

// S creates an <s> element.
func S(items ...Item) *Element {
	return internalhtml.El(HTMLSElement{}, "s", items...)
}

// Samp creates a <samp> element.
func Samp(items ...Item) *Element {
	return internalhtml.El(HTMLSampElement{}, "samp", items...)
}

// Script creates a <script> element.
func Script(items ...Item) *Element {
	return internalhtml.El(HTMLScriptElement{}, "script", items...)
}

// Section creates a <section> element.
func Section(items ...Item) *Element {
	return internalhtml.El(HTMLSectionElement{}, "section", items...)
}

// Select creates a <select> element.
func Select(items ...Item) *Element {
	return internalhtml.El(HTMLSelectElement{}, "select", items...)
}

// Slot creates a <slot> element.
func Slot(items ...Item) *Element {
	return internalhtml.El(HTMLSlotElement{}, "slot", items...)
}

// Small creates a <small> element.
func Small(items ...Item) *Element {
	return internalhtml.El(HTMLSmallElement{}, "small", items...)
}

// Source creates a <source> element.
func Source(items ...Item) *Element {
	return internalhtml.El(HTMLSourceElement{}, "source", items...)
}

// Span creates a <span> element.
func Span(items ...Item) *Element {
	return internalhtml.El(HTMLSpanElement{}, "span", items...)
}

// Stop creates a <stop> element.
func Stop(items ...Item) *Element {
	return internalhtml.El(SVGStopElement{}, "stop", items...)
}

// Strong creates a <strong> element.
func Strong(items ...Item) *Element {
	return internalhtml.El(HTMLStrongElement{}, "strong", items...)
}

// StyleEl creates a <style> element.
func StyleEl(items ...Item) *Element {
	return internalhtml.El(HTMLStyleElement{}, "style", items...)
}

// Sub creates a <sub> element.
func Sub(items ...Item) *Element {
	return internalhtml.El(HTMLSubElement{}, "sub", items...)
}

// Summary creates a <summary> element.
func Summary(items ...Item) *Element {
	return internalhtml.El(HTMLSummaryElement{}, "summary", items...)
}

// Sup creates a <sup> element.
func Sup(items ...Item) *Element {
	return internalhtml.El(HTMLSupElement{}, "sup", items...)
}

// Svg creates an <svg> element.
func Svg(items ...Item) *Element {
	return internalhtml.El(SVGSvgElement{}, "svg", items...)
}

// SvgText creates an SVG <text> element.
func SvgText(items ...Item) *Element {
	return internalhtml.El(SVGSvgTextElement{}, "text", items...)
}

// TSpan creates a <tspan> element.
func TSpan(items ...Item) *Element {
	return internalhtml.El(SVGTSpanElement{}, "tspan", items...)
}

// Table creates a <table> element.
func Table(items ...Item) *Element {
	return internalhtml.El(HTMLTableElement{}, "table", items...)
}

// Tbody creates a <tbody> element.
func Tbody(items ...Item) *Element {
	return internalhtml.El(HTMLTbodyElement{}, "tbody", items...)
}

// Td creates a <td> element.
func Td(items ...Item) *Element {
	return internalhtml.El(HTMLTdElement{}, "td", items...)
}

// Template creates a <template> element.
func Template(items ...Item) *Element {
	return internalhtml.El(HTMLTemplateElement{}, "template", items...)
}

// Textarea creates a <textarea> element.
func Textarea(items ...Item) *Element {
	return internalhtml.El(HTMLTextareaElement{}, "textarea", items...)
}

// Tfoot creates a <tfoot> element.
func Tfoot(items ...Item) *Element {
	return internalhtml.El(HTMLTfootElement{}, "tfoot", items...)
}

// Th creates a <th> element.
func Th(items ...Item) *Element {
	return internalhtml.El(HTMLThElement{}, "th", items...)
}

// Thead creates a <thead> element.
func Thead(items ...Item) *Element {
	return internalhtml.El(HTMLTheadElement{}, "thead", items...)
}

// Time creates a <time> element.
func Time(items ...Item) *Element {
	return internalhtml.El(HTMLTimeElement{}, "time", items...)
}

// TitleEl creates a <title> element.
func TitleEl(items ...Item) *Element {
	return internalhtml.El(HTMLTitleElement{}, "title", items...)
}

// Tr creates a <tr> element.
func Tr(items ...Item) *Element {
	return internalhtml.El(HTMLTrElement{}, "tr", items...)
}

// Track creates a <track> element.
func Track(items ...Item) *Element {
	return internalhtml.El(HTMLTrackElement{}, "track", items...)
}

// U creates a <u> element.
func U(items ...Item) *Element {
	return internalhtml.El(HTMLUElement{}, "u", items...)
}

// Ul creates a <ul> element.
func Ul(items ...Item) *Element {
	return internalhtml.El(HTMLUlElement{}, "ul", items...)
}

// Use creates a <use> element.
func Use(items ...Item) *Element {
	return internalhtml.El(SVGUseElement{}, "use", items...)
}

// Var creates a <var> element.
func Var(items ...Item) *Element {
	return internalhtml.El(HTMLVarElement{}, "var", items...)
}

// Video creates a <video> element.
func Video(items ...Item) *Element {
	return internalhtml.El(HTMLVideoElement{}, "video", items...)
}

// Wbr creates a <wbr> element.
func Wbr(items ...Item) *Element {
	return internalhtml.El(HTMLWbrElement{}, "wbr", items...)
}

// Element ref types
type (
	ARef              = internalhtml.ARef
	AbbrRef           = internalhtml.AbbrRef
	AddressRef        = internalhtml.AddressRef
	AreaRef           = internalhtml.AreaRef
	ArticleRef        = internalhtml.ArticleRef
	AsideRef          = internalhtml.AsideRef
	AudioRef          = internalhtml.AudioRef
	BRef              = internalhtml.BRef
	BaseRef           = internalhtml.BaseRef
	BdiRef            = internalhtml.BdiRef
	BdoRef            = internalhtml.BdoRef
	BlockquoteRef     = internalhtml.BlockquoteRef
	BodyRef           = internalhtml.BodyRef
	BrRef             = internalhtml.BrRef
	ButtonRef         = internalhtml.ButtonRef
	CanvasRef         = internalhtml.CanvasRef
	CaptionRef        = internalhtml.CaptionRef
	CircleRef         = internalhtml.CircleRef
	CiteRef           = internalhtml.CiteRef
	ClipPathRef       = internalhtml.ClipPathRef
	CodeRef           = internalhtml.CodeRef
	ColRef            = internalhtml.ColRef
	ColgroupRef       = internalhtml.ColgroupRef
	DataElRef         = internalhtml.DataElRef
	DatalistRef       = internalhtml.DatalistRef
	DdRef             = internalhtml.DdRef
	DefsRef           = internalhtml.DefsRef
	DelElRef          = internalhtml.DelElRef
	DetailsRef        = internalhtml.DetailsRef
	DfnRef            = internalhtml.DfnRef
	DialogRef         = internalhtml.DialogRef
	DivRef            = internalhtml.DivRef
	DlRef             = internalhtml.DlRef
	DtRef             = internalhtml.DtRef
	EllipseRef        = internalhtml.EllipseRef
	EmRef             = internalhtml.EmRef
	EmbedRef          = internalhtml.EmbedRef
	FieldsetRef       = internalhtml.FieldsetRef
	FigcaptionRef     = internalhtml.FigcaptionRef
	FigureRef         = internalhtml.FigureRef
	FooterRef         = internalhtml.FooterRef
	ForeignObjectRef  = internalhtml.ForeignObjectRef
	FormRef           = internalhtml.FormRef
	GRef              = internalhtml.GRef
	H1Ref             = internalhtml.H1Ref
	H2Ref             = internalhtml.H2Ref
	H3Ref             = internalhtml.H3Ref
	H4Ref             = internalhtml.H4Ref
	H5Ref             = internalhtml.H5Ref
	H6Ref             = internalhtml.H6Ref
	HeadRef           = internalhtml.HeadRef
	HeaderRef         = internalhtml.HeaderRef
	HgroupRef         = internalhtml.HgroupRef
	HrRef             = internalhtml.HrRef
	HtmlRef           = internalhtml.HtmlRef
	IRef              = internalhtml.IRef
	IframeRef         = internalhtml.IframeRef
	ImageRef          = internalhtml.ImageRef
	ImgRef            = internalhtml.ImgRef
	InputRef          = internalhtml.InputRef
	InsElRef          = internalhtml.InsElRef
	KbdRef            = internalhtml.KbdRef
	LabelRef          = internalhtml.LabelRef
	LegendRef         = internalhtml.LegendRef
	LiRef             = internalhtml.LiRef
	LineRef           = internalhtml.LineRef
	LinearGradientRef = internalhtml.LinearGradientRef
	LinkRef           = internalhtml.LinkRef
	MainRef           = internalhtml.MainRef
	MapElRef          = internalhtml.MapElRef
	MarkRef           = internalhtml.MarkRef
	MarkerRef         = internalhtml.MarkerRef
	MaskRef           = internalhtml.MaskRef
	MenuRef           = internalhtml.MenuRef
	MenuItemRef       = internalhtml.MenuItemRef
	MetaRef           = internalhtml.MetaRef
	MeterRef          = internalhtml.MeterRef
	NavRef            = internalhtml.NavRef
	NoscriptRef       = internalhtml.NoscriptRef
	ObjectRef         = internalhtml.ObjectRef
	OlRef             = internalhtml.OlRef
	OptgroupRef       = internalhtml.OptgroupRef
	OptionRef         = internalhtml.OptionRef
	OutputRef         = internalhtml.OutputRef
	PRef              = internalhtml.PRef
	ParamRef          = internalhtml.ParamRef
	PathRef           = internalhtml.PathRef
	PatternRef        = internalhtml.PatternRef
	PictureRef        = internalhtml.PictureRef
	PolygonRef        = internalhtml.PolygonRef
	PolylineRef       = internalhtml.PolylineRef
	PortalRef         = internalhtml.PortalRef
	PreRef            = internalhtml.PreRef
	ProgressRef       = internalhtml.ProgressRef
	QRef              = internalhtml.QRef
	RadialGradientRef = internalhtml.RadialGradientRef
	RbRef             = internalhtml.RbRef
	RectRef           = internalhtml.RectRef
	RpRef             = internalhtml.RpRef
	RtRef             = internalhtml.RtRef
	RtcRef            = internalhtml.RtcRef
	RubyRef           = internalhtml.RubyRef
	SRef              = internalhtml.SRef
	SampRef           = internalhtml.SampRef
	ScriptRef         = internalhtml.ScriptRef
	SectionRef        = internalhtml.SectionRef
	SelectRef         = internalhtml.SelectRef
	SlotRef           = internalhtml.SlotRef
	SmallRef          = internalhtml.SmallRef
	SourceRef         = internalhtml.SourceRef
	SpanRef           = internalhtml.SpanRef
	StopRef           = internalhtml.StopRef
	StrongRef         = internalhtml.StrongRef
	StyleElRef        = internalhtml.StyleElRef
	SubRef            = internalhtml.SubRef
	SummaryRef        = internalhtml.SummaryRef
	SupRef            = internalhtml.SupRef
	SvgRef            = internalhtml.SvgRef
	SvgTextRef        = internalhtml.SvgTextRef
	TSpanRef          = internalhtml.TSpanRef
	TableRef          = internalhtml.TableRef
	TbodyRef          = internalhtml.TbodyRef
	TdRef             = internalhtml.TdRef
	TemplateRef       = internalhtml.TemplateRef
	TextareaRef       = internalhtml.TextareaRef
	TfootRef          = internalhtml.TfootRef
	ThRef             = internalhtml.ThRef
	TheadRef          = internalhtml.TheadRef
	TimeRef           = internalhtml.TimeRef
	TitleElRef        = internalhtml.TitleElRef
	TrRef             = internalhtml.TrRef
	TrackRef          = internalhtml.TrackRef
	URef              = internalhtml.URef
	UlRef             = internalhtml.UlRef
	UseRef            = internalhtml.UseRef
	VarRef            = internalhtml.VarRef
	VideoRef          = internalhtml.VideoRef
	WbrRef            = internalhtml.WbrRef
)
