// Code generated by tags_gen.go; DO NOT EDIT.
// Package html provides public re-exports from internal/html and internal/dom.
package html

import (
	"github.com/eleven-am/pondlive/go/internal/dom"
	internalhtml "github.com/eleven-am/pondlive/go/internal/html"
)

var El = dom.El

// Element descriptor types
type (
	HTMLAElement             = internalhtml.HTMLAElement
	HTMLAbbrElement          = internalhtml.HTMLAbbrElement
	HTMLAddressElement       = internalhtml.HTMLAddressElement
	HTMLAreaElement          = internalhtml.HTMLAreaElement
	HTMLArticleElement       = internalhtml.HTMLArticleElement
	HTMLAsideElement         = internalhtml.HTMLAsideElement
	HTMLAudioElement         = internalhtml.HTMLAudioElement
	HTMLBElement             = internalhtml.HTMLBElement
	HTMLBaseElement          = internalhtml.HTMLBaseElement
	HTMLBdiElement           = internalhtml.HTMLBdiElement
	HTMLBdoElement           = internalhtml.HTMLBdoElement
	HTMLBlockquoteElement    = internalhtml.HTMLBlockquoteElement
	HTMLBodyElement          = internalhtml.HTMLBodyElement
	HTMLBrElement            = internalhtml.HTMLBrElement
	HTMLButtonElement        = internalhtml.HTMLButtonElement
	HTMLCanvasElement        = internalhtml.HTMLCanvasElement
	HTMLCaptionElement       = internalhtml.HTMLCaptionElement
	SVGCircleElement         = internalhtml.SVGCircleElement
	HTMLCiteElement          = internalhtml.HTMLCiteElement
	SVGClipPathElement       = internalhtml.SVGClipPathElement
	HTMLCodeElement          = internalhtml.HTMLCodeElement
	HTMLColElement           = internalhtml.HTMLColElement
	HTMLColgroupElement      = internalhtml.HTMLColgroupElement
	HTMLDataElement          = internalhtml.HTMLDataElement
	HTMLDatalistElement      = internalhtml.HTMLDatalistElement
	HTMLDdElement            = internalhtml.HTMLDdElement
	SVGDefsElement           = internalhtml.SVGDefsElement
	HTMLDelElement           = internalhtml.HTMLDelElement
	HTMLDetailsElement       = internalhtml.HTMLDetailsElement
	HTMLDfnElement           = internalhtml.HTMLDfnElement
	HTMLDialogElement        = internalhtml.HTMLDialogElement
	HTMLDivElement           = internalhtml.HTMLDivElement
	HTMLDlElement            = internalhtml.HTMLDlElement
	HTMLDtElement            = internalhtml.HTMLDtElement
	SVGEllipseElement        = internalhtml.SVGEllipseElement
	HTMLEmElement            = internalhtml.HTMLEmElement
	HTMLEmbedElement         = internalhtml.HTMLEmbedElement
	HTMLFieldsetElement      = internalhtml.HTMLFieldsetElement
	HTMLFigcaptionElement    = internalhtml.HTMLFigcaptionElement
	HTMLFigureElement        = internalhtml.HTMLFigureElement
	HTMLFooterElement        = internalhtml.HTMLFooterElement
	SVGForeignObjectElement  = internalhtml.SVGForeignObjectElement
	HTMLFormElement          = internalhtml.HTMLFormElement
	SVGGElement              = internalhtml.SVGGElement
	HTMLH1Element            = internalhtml.HTMLH1Element
	HTMLH2Element            = internalhtml.HTMLH2Element
	HTMLH3Element            = internalhtml.HTMLH3Element
	HTMLH4Element            = internalhtml.HTMLH4Element
	HTMLH5Element            = internalhtml.HTMLH5Element
	HTMLH6Element            = internalhtml.HTMLH6Element
	HTMLHeadElement          = internalhtml.HTMLHeadElement
	HTMLHeaderElement        = internalhtml.HTMLHeaderElement
	HTMLHgroupElement        = internalhtml.HTMLHgroupElement
	HTMLHrElement            = internalhtml.HTMLHrElement
	HTMLHtmlElement          = internalhtml.HTMLHtmlElement
	HTMLIElement             = internalhtml.HTMLIElement
	HTMLIframeElement        = internalhtml.HTMLIframeElement
	SVGImageElement          = internalhtml.SVGImageElement
	HTMLImgElement           = internalhtml.HTMLImgElement
	HTMLInputElement         = internalhtml.HTMLInputElement
	HTMLInsElement           = internalhtml.HTMLInsElement
	HTMLKbdElement           = internalhtml.HTMLKbdElement
	HTMLLabelElement         = internalhtml.HTMLLabelElement
	HTMLLegendElement        = internalhtml.HTMLLegendElement
	HTMLLiElement            = internalhtml.HTMLLiElement
	SVGLineElement           = internalhtml.SVGLineElement
	SVGLinearGradientElement = internalhtml.SVGLinearGradientElement
	HTMLLinkElement          = internalhtml.HTMLLinkElement
	HTMLMainElement          = internalhtml.HTMLMainElement
	HTMLMapElement           = internalhtml.HTMLMapElement
	HTMLMarkElement          = internalhtml.HTMLMarkElement
	SVGMarkerElement         = internalhtml.SVGMarkerElement
	SVGMaskElement           = internalhtml.SVGMaskElement
	HTMLMenuElement          = internalhtml.HTMLMenuElement
	HTMLMenuItemElement      = internalhtml.HTMLMenuItemElement
	HTMLMetaElement          = internalhtml.HTMLMetaElement
	HTMLMeterElement         = internalhtml.HTMLMeterElement
	HTMLNavElement           = internalhtml.HTMLNavElement
	HTMLNoscriptElement      = internalhtml.HTMLNoscriptElement
	HTMLObjectElement        = internalhtml.HTMLObjectElement
	HTMLOlElement            = internalhtml.HTMLOlElement
	HTMLOptgroupElement      = internalhtml.HTMLOptgroupElement
	HTMLOptionElement        = internalhtml.HTMLOptionElement
	HTMLOutputElement        = internalhtml.HTMLOutputElement
	HTMLPElement             = internalhtml.HTMLPElement
	HTMLParamElement         = internalhtml.HTMLParamElement
	SVGPathElement           = internalhtml.SVGPathElement
	SVGPatternElement        = internalhtml.SVGPatternElement
	HTMLPictureElement       = internalhtml.HTMLPictureElement
	SVGPolygonElement        = internalhtml.SVGPolygonElement
	SVGPolylineElement       = internalhtml.SVGPolylineElement
	HTMLPortalElement        = internalhtml.HTMLPortalElement
	HTMLPreElement           = internalhtml.HTMLPreElement
	HTMLProgressElement      = internalhtml.HTMLProgressElement
	HTMLQElement             = internalhtml.HTMLQElement
	SVGRadialGradientElement = internalhtml.SVGRadialGradientElement
	HTMLRbElement            = internalhtml.HTMLRbElement
	SVGRectElement           = internalhtml.SVGRectElement
	HTMLRpElement            = internalhtml.HTMLRpElement
	HTMLRtElement            = internalhtml.HTMLRtElement
	HTMLRtcElement           = internalhtml.HTMLRtcElement
	HTMLRubyElement          = internalhtml.HTMLRubyElement
	HTMLSElement             = internalhtml.HTMLSElement
	HTMLSampElement          = internalhtml.HTMLSampElement
	HTMLScriptElement        = internalhtml.HTMLScriptElement
	HTMLSectionElement       = internalhtml.HTMLSectionElement
	HTMLSelectElement        = internalhtml.HTMLSelectElement
	HTMLSlotElement          = internalhtml.HTMLSlotElement
	HTMLSmallElement         = internalhtml.HTMLSmallElement
	HTMLSourceElement        = internalhtml.HTMLSourceElement
	HTMLSpanElement          = internalhtml.HTMLSpanElement
	SVGStopElement           = internalhtml.SVGStopElement
	HTMLStrongElement        = internalhtml.HTMLStrongElement
	HTMLStyleElement         = internalhtml.HTMLStyleElement
	HTMLSubElement           = internalhtml.HTMLSubElement
	HTMLSummaryElement       = internalhtml.HTMLSummaryElement
	HTMLSupElement           = internalhtml.HTMLSupElement
	SVGSvgElement            = internalhtml.SVGSvgElement
	SVGSvgTextElement        = internalhtml.SVGSvgTextElement
	SVGTSpanElement          = internalhtml.SVGTSpanElement
	HTMLTableElement         = internalhtml.HTMLTableElement
	HTMLTbodyElement         = internalhtml.HTMLTbodyElement
	HTMLTdElement            = internalhtml.HTMLTdElement
	HTMLTemplateElement      = internalhtml.HTMLTemplateElement
	HTMLTextareaElement      = internalhtml.HTMLTextareaElement
	HTMLTfootElement         = internalhtml.HTMLTfootElement
	HTMLThElement            = internalhtml.HTMLThElement
	HTMLTheadElement         = internalhtml.HTMLTheadElement
	HTMLTimeElement          = internalhtml.HTMLTimeElement
	HTMLTitleElement         = internalhtml.HTMLTitleElement
	HTMLTrElement            = internalhtml.HTMLTrElement
	HTMLTrackElement         = internalhtml.HTMLTrackElement
	HTMLUElement             = internalhtml.HTMLUElement
	HTMLUlElement            = internalhtml.HTMLUlElement
	SVGUseElement            = internalhtml.SVGUseElement
	HTMLVarElement           = internalhtml.HTMLVarElement
	HTMLVideoElement         = internalhtml.HTMLVideoElement
	HTMLWbrElement           = internalhtml.HTMLWbrElement
)

// A creates an <a> element.
func A(items ...Item) Node {
	return El(HTMLAElement{}, items...)
}

// Abbr creates an <abbr> element.
func Abbr(items ...Item) Node {
	return El(HTMLAbbrElement{}, items...)
}

// Address creates an <address> element.
func Address(items ...Item) Node {
	return El(HTMLAddressElement{}, items...)
}

// Area creates an <area> element.
func Area(items ...Item) Node {
	return El(HTMLAreaElement{}, items...)
}

// Article creates an <article> element.
func Article(items ...Item) Node {
	return El(HTMLArticleElement{}, items...)
}

// Aside creates an <aside> element.
func Aside(items ...Item) Node {
	return El(HTMLAsideElement{}, items...)
}

// Audio creates an <audio> element.
func Audio(items ...Item) Node {
	return El(HTMLAudioElement{}, items...)
}

// B creates a <b> element.
func B(items ...Item) Node {
	return El(HTMLBElement{}, items...)
}

// Base creates a <base> element.
func Base(items ...Item) Node {
	return El(HTMLBaseElement{}, items...)
}

// Bdi creates a <bdi> element.
func Bdi(items ...Item) Node {
	return El(HTMLBdiElement{}, items...)
}

// Bdo creates a <bdo> element.
func Bdo(items ...Item) Node {
	return El(HTMLBdoElement{}, items...)
}

// Blockquote creates a <blockquote> element.
func Blockquote(items ...Item) Node {
	return El(HTMLBlockquoteElement{}, items...)
}

// Body creates a <body> element.
func Body(items ...Item) Node {
	return El(HTMLBodyElement{}, items...)
}

// Br creates a <br> element.
func Br(items ...Item) Node {
	return El(HTMLBrElement{}, items...)
}

// Button creates a <button> element.
func Button(items ...Item) Node {
	return El(HTMLButtonElement{}, items...)
}

// Canvas creates a <canvas> element.
func Canvas(items ...Item) Node {
	return El(HTMLCanvasElement{}, items...)
}

// Caption creates a <caption> element.
func Caption(items ...Item) Node {
	return El(HTMLCaptionElement{}, items...)
}

// Circle creates a <circle> element.
func Circle(items ...Item) Node {
	return El(SVGCircleElement{}, items...)
}

// Cite creates a <cite> element.
func Cite(items ...Item) Node {
	return El(HTMLCiteElement{}, items...)
}

// ClipPath creates a <clipPath> element.
func ClipPath(items ...Item) Node {
	return El(SVGClipPathElement{}, items...)
}

// Code creates a <code> element.
func Code(items ...Item) Node {
	return El(HTMLCodeElement{}, items...)
}

// Col creates a <col> element.
func Col(items ...Item) Node {
	return El(HTMLColElement{}, items...)
}

// Colgroup creates a <colgroup> element.
func Colgroup(items ...Item) Node {
	return El(HTMLColgroupElement{}, items...)
}

// DataEl creates a <data> element.
func DataEl(items ...Item) Node {
	return El(HTMLDataElement{}, items...)
}

// Datalist creates a <datalist> element.
func Datalist(items ...Item) Node {
	return El(HTMLDatalistElement{}, items...)
}

// Dd creates a <dd> element.
func Dd(items ...Item) Node {
	return El(HTMLDdElement{}, items...)
}

// Defs creates a <defs> element.
func Defs(items ...Item) Node {
	return El(SVGDefsElement{}, items...)
}

// DelEl creates a <del> element.
func DelEl(items ...Item) Node {
	return El(HTMLDelElement{}, items...)
}

// Details creates a <details> element.
func Details(items ...Item) Node {
	return El(HTMLDetailsElement{}, items...)
}

// Dfn creates a <dfn> element.
func Dfn(items ...Item) Node {
	return El(HTMLDfnElement{}, items...)
}

// Dialog creates a <dialog> element.
func Dialog(items ...Item) Node {
	return El(HTMLDialogElement{}, items...)
}

// Div creates a <div> element.
func Div(items ...Item) Node {
	return El(HTMLDivElement{}, items...)
}

// Dl creates a <dl> element.
func Dl(items ...Item) Node {
	return El(HTMLDlElement{}, items...)
}

// Dt creates a <dt> element.
func Dt(items ...Item) Node {
	return El(HTMLDtElement{}, items...)
}

// Ellipse creates an <ellipse> element.
func Ellipse(items ...Item) Node {
	return El(SVGEllipseElement{}, items...)
}

// Em creates an <em> element.
func Em(items ...Item) Node {
	return El(HTMLEmElement{}, items...)
}

// Embed creates an <embed> element.
func Embed(items ...Item) Node {
	return El(HTMLEmbedElement{}, items...)
}

// Fieldset creates a <fieldset> element.
func Fieldset(items ...Item) Node {
	return El(HTMLFieldsetElement{}, items...)
}

// Figcaption creates a <figcaption> element.
func Figcaption(items ...Item) Node {
	return El(HTMLFigcaptionElement{}, items...)
}

// Figure creates a <figure> element.
func Figure(items ...Item) Node {
	return El(HTMLFigureElement{}, items...)
}

// Footer creates a <footer> element.
func Footer(items ...Item) Node {
	return El(HTMLFooterElement{}, items...)
}

// ForeignObject creates a <foreignObject> element.
func ForeignObject(items ...Item) Node {
	return El(SVGForeignObjectElement{}, items...)
}

// Form creates a <form> element.
func Form(items ...Item) Node {
	return El(HTMLFormElement{}, items...)
}

// G creates a <g> element.
func G(items ...Item) Node {
	return El(SVGGElement{}, items...)
}

// H1 creates an <h1> element.
func H1(items ...Item) Node {
	return El(HTMLH1Element{}, items...)
}

// H2 creates an <h2> element.
func H2(items ...Item) Node {
	return El(HTMLH2Element{}, items...)
}

// H3 creates an <h3> element.
func H3(items ...Item) Node {
	return El(HTMLH3Element{}, items...)
}

// H4 creates an <h4> element.
func H4(items ...Item) Node {
	return El(HTMLH4Element{}, items...)
}

// H5 creates an <h5> element.
func H5(items ...Item) Node {
	return El(HTMLH5Element{}, items...)
}

// H6 creates an <h6> element.
func H6(items ...Item) Node {
	return El(HTMLH6Element{}, items...)
}

// Head creates a <head> element.
func Head(items ...Item) Node {
	return El(HTMLHeadElement{}, items...)
}

// Header creates a <header> element.
func Header(items ...Item) Node {
	return El(HTMLHeaderElement{}, items...)
}

// Hgroup creates an <hgroup> element.
func Hgroup(items ...Item) Node {
	return El(HTMLHgroupElement{}, items...)
}

// Hr creates an <hr> element.
func Hr(items ...Item) Node {
	return El(HTMLHrElement{}, items...)
}

// Html creates an <html> element.
func Html(items ...Item) Node {
	return El(HTMLHtmlElement{}, items...)
}

// I creates an <i> element.
func I(items ...Item) Node {
	return El(HTMLIElement{}, items...)
}

// Iframe creates an <iframe> element.
func Iframe(items ...Item) Node {
	return El(HTMLIframeElement{}, items...)
}

// Image creates an <image> element.
func Image(items ...Item) Node {
	return El(SVGImageElement{}, items...)
}

// Img creates an <img> element.
func Img(items ...Item) Node {
	return El(HTMLImgElement{}, items...)
}

// Input creates an <input> element.
func Input(items ...Item) Node {
	return El(HTMLInputElement{}, items...)
}

// InsEl creates an <ins> element.
func InsEl(items ...Item) Node {
	return El(HTMLInsElement{}, items...)
}

// Kbd creates a <kbd> element.
func Kbd(items ...Item) Node {
	return El(HTMLKbdElement{}, items...)
}

// Label creates a <label> element.
func Label(items ...Item) Node {
	return El(HTMLLabelElement{}, items...)
}

// Legend creates a <legend> element.
func Legend(items ...Item) Node {
	return El(HTMLLegendElement{}, items...)
}

// Li creates an <li> element.
func Li(items ...Item) Node {
	return El(HTMLLiElement{}, items...)
}

// Line creates a <line> element.
func Line(items ...Item) Node {
	return El(SVGLineElement{}, items...)
}

// LinearGradient creates a <linearGradient> element.
func LinearGradient(items ...Item) Node {
	return El(SVGLinearGradientElement{}, items...)
}

// Link creates a <link> element.
func Link(items ...Item) Node {
	return El(HTMLLinkElement{}, items...)
}

// Main creates a <main> element.
func Main(items ...Item) Node {
	return El(HTMLMainElement{}, items...)
}

// MapEl creates a <map> element.
func MapEl(items ...Item) Node {
	return El(HTMLMapElement{}, items...)
}

// Mark creates a <mark> element.
func Mark(items ...Item) Node {
	return El(HTMLMarkElement{}, items...)
}

// Marker creates a <marker> element.
func Marker(items ...Item) Node {
	return El(SVGMarkerElement{}, items...)
}

// Mask creates a <mask> element.
func Mask(items ...Item) Node {
	return El(SVGMaskElement{}, items...)
}

// Menu creates a <menu> element.
func Menu(items ...Item) Node {
	return El(HTMLMenuElement{}, items...)
}

// MenuItem creates a <menuitem> element.
func MenuItem(items ...Item) Node {
	return El(HTMLMenuItemElement{}, items...)
}

// Meta creates a <meta> element.
func Meta(items ...Item) Node {
	return El(HTMLMetaElement{}, items...)
}

// Meter creates a <meter> element.
func Meter(items ...Item) Node {
	return El(HTMLMeterElement{}, items...)
}

// Nav creates a <nav> element.
func Nav(items ...Item) Node {
	return El(HTMLNavElement{}, items...)
}

// Noscript creates a <noscript> element.
func Noscript(items ...Item) Node {
	return El(HTMLNoscriptElement{}, items...)
}

// Object creates an <object> element.
func Object(items ...Item) Node {
	return El(HTMLObjectElement{}, items...)
}

// Ol creates an <ol> element.
func Ol(items ...Item) Node {
	return El(HTMLOlElement{}, items...)
}

// Optgroup creates an <optgroup> element.
func Optgroup(items ...Item) Node {
	return El(HTMLOptgroupElement{}, items...)
}

// Option creates an <option> element.
func Option(items ...Item) Node {
	return El(HTMLOptionElement{}, items...)
}

// Output creates an <output> element.
func Output(items ...Item) Node {
	return El(HTMLOutputElement{}, items...)
}

// P creates a <p> element.
func P(items ...Item) Node {
	return El(HTMLPElement{}, items...)
}

// Param creates a <param> element.
func Param(items ...Item) Node {
	return El(HTMLParamElement{}, items...)
}

// Path creates a <path> element.
func Path(items ...Item) Node {
	return El(SVGPathElement{}, items...)
}

// Pattern creates a <pattern> element.
func Pattern(items ...Item) Node {
	return El(SVGPatternElement{}, items...)
}

// Picture creates a <picture> element.
func Picture(items ...Item) Node {
	return El(HTMLPictureElement{}, items...)
}

// Polygon creates a <polygon> element.
func Polygon(items ...Item) Node {
	return El(SVGPolygonElement{}, items...)
}

// Polyline creates a <polyline> element.
func Polyline(items ...Item) Node {
	return El(SVGPolylineElement{}, items...)
}

// Portal creates a <portal> element.
func Portal(items ...Item) Node {
	return El(HTMLPortalElement{}, items...)
}

// Pre creates a <pre> element.
func Pre(items ...Item) Node {
	return El(HTMLPreElement{}, items...)
}

// Progress creates a <progress> element.
func Progress(items ...Item) Node {
	return El(HTMLProgressElement{}, items...)
}

// Q creates a <q> element.
func Q(items ...Item) Node {
	return El(HTMLQElement{}, items...)
}

// RadialGradient creates a <radialGradient> element.
func RadialGradient(items ...Item) Node {
	return El(SVGRadialGradientElement{}, items...)
}

// Rb creates an <rb> element.
func Rb(items ...Item) Node {
	return El(HTMLRbElement{}, items...)
}

// Rect creates a <rect> element.
func Rect(items ...Item) Node {
	return El(SVGRectElement{}, items...)
}

// Rp creates an <rp> element.
func Rp(items ...Item) Node {
	return El(HTMLRpElement{}, items...)
}

// Rt creates an <rt> element.
func Rt(items ...Item) Node {
	return El(HTMLRtElement{}, items...)
}

// Rtc creates a <rtc> element.
func Rtc(items ...Item) Node {
	return El(HTMLRtcElement{}, items...)
}

// Ruby creates a <ruby> element.
func Ruby(items ...Item) Node {
	return El(HTMLRubyElement{}, items...)
}

// S creates an <s> element.
func S(items ...Item) Node {
	return El(HTMLSElement{}, items...)
}

// Samp creates a <samp> element.
func Samp(items ...Item) Node {
	return El(HTMLSampElement{}, items...)
}

// Script creates a <script> element.
func Script(items ...Item) Node {
	return El(HTMLScriptElement{}, items...)
}

// Section creates a <section> element.
func Section(items ...Item) Node {
	return El(HTMLSectionElement{}, items...)
}

// Select creates a <select> element.
func Select(items ...Item) Node {
	return El(HTMLSelectElement{}, items...)
}

// Slot creates a <slot> element.
func Slot(items ...Item) Node {
	return El(HTMLSlotElement{}, items...)
}

// Small creates a <small> element.
func Small(items ...Item) Node {
	return El(HTMLSmallElement{}, items...)
}

// Source creates a <source> element.
func Source(items ...Item) Node {
	return El(HTMLSourceElement{}, items...)
}

// Span creates a <span> element.
func Span(items ...Item) Node {
	return El(HTMLSpanElement{}, items...)
}

// Stop creates a <stop> element.
func Stop(items ...Item) Node {
	return El(SVGStopElement{}, items...)
}

// Strong creates a <strong> element.
func Strong(items ...Item) Node {
	return El(HTMLStrongElement{}, items...)
}

// StyleEl creates a <style> element.
func StyleEl(items ...Item) Node {
	return El(HTMLStyleElement{}, items...)
}

// Sub creates a <sub> element.
func Sub(items ...Item) Node {
	return El(HTMLSubElement{}, items...)
}

// Summary creates a <summary> element.
func Summary(items ...Item) Node {
	return El(HTMLSummaryElement{}, items...)
}

// Sup creates a <sup> element.
func Sup(items ...Item) Node {
	return El(HTMLSupElement{}, items...)
}

// Svg creates an <svg> element.
func Svg(items ...Item) Node {
	return El(SVGSvgElement{}, items...)
}

// SvgText creates an SVG <text> element.
func SvgText(items ...Item) Node {
	return El(SVGSvgTextElement{}, items...)
}

// TSpan creates a <tspan> element.
func TSpan(items ...Item) Node {
	return El(SVGTSpanElement{}, items...)
}

// Table creates a <table> element.
func Table(items ...Item) Node {
	return El(HTMLTableElement{}, items...)
}

// Tbody creates a <tbody> element.
func Tbody(items ...Item) Node {
	return El(HTMLTbodyElement{}, items...)
}

// Td creates a <td> element.
func Td(items ...Item) Node {
	return El(HTMLTdElement{}, items...)
}

// Template creates a <template> element.
func Template(items ...Item) Node {
	return El(HTMLTemplateElement{}, items...)
}

// Textarea creates a <textarea> element.
func Textarea(items ...Item) Node {
	return El(HTMLTextareaElement{}, items...)
}

// Tfoot creates a <tfoot> element.
func Tfoot(items ...Item) Node {
	return El(HTMLTfootElement{}, items...)
}

// Th creates a <th> element.
func Th(items ...Item) Node {
	return El(HTMLThElement{}, items...)
}

// Thead creates a <thead> element.
func Thead(items ...Item) Node {
	return El(HTMLTheadElement{}, items...)
}

// Time creates a <time> element.
func Time(items ...Item) Node {
	return El(HTMLTimeElement{}, items...)
}

// TitleEl creates a <title> element.
func TitleEl(items ...Item) Node {
	return El(HTMLTitleElement{}, items...)
}

// Tr creates a <tr> element.
func Tr(items ...Item) Node {
	return El(HTMLTrElement{}, items...)
}

// Track creates a <track> element.
func Track(items ...Item) Node {
	return El(HTMLTrackElement{}, items...)
}

// U creates a <u> element.
func U(items ...Item) Node {
	return El(HTMLUElement{}, items...)
}

// Ul creates a <ul> element.
func Ul(items ...Item) Node {
	return El(HTMLUlElement{}, items...)
}

// Use creates a <use> element.
func Use(items ...Item) Node {
	return El(SVGUseElement{}, items...)
}

// Var creates a <var> element.
func Var(items ...Item) Node {
	return El(HTMLVarElement{}, items...)
}

// Video creates a <video> element.
func Video(items ...Item) Node {
	return El(HTMLVideoElement{}, items...)
}

// Wbr creates a <wbr> element.
func Wbr(items ...Item) Node {
	return El(HTMLWbrElement{}, items...)
}

// Element ref types
type (
	ARef              = internalhtml.ARef
	AbbrRef           = internalhtml.AbbrRef
	AddressRef        = internalhtml.AddressRef
	AreaRef           = internalhtml.AreaRef
	ArticleRef        = internalhtml.ArticleRef
	AsideRef          = internalhtml.AsideRef
	AudioRef          = internalhtml.AudioRef
	BRef              = internalhtml.BRef
	BaseRef           = internalhtml.BaseRef
	BdiRef            = internalhtml.BdiRef
	BdoRef            = internalhtml.BdoRef
	BlockquoteRef     = internalhtml.BlockquoteRef
	BodyRef           = internalhtml.BodyRef
	BrRef             = internalhtml.BrRef
	ButtonRef         = internalhtml.ButtonRef
	CanvasRef         = internalhtml.CanvasRef
	CaptionRef        = internalhtml.CaptionRef
	CircleRef         = internalhtml.CircleRef
	CiteRef           = internalhtml.CiteRef
	ClipPathRef       = internalhtml.ClipPathRef
	CodeRef           = internalhtml.CodeRef
	ColRef            = internalhtml.ColRef
	ColgroupRef       = internalhtml.ColgroupRef
	DataElRef         = internalhtml.DataElRef
	DatalistRef       = internalhtml.DatalistRef
	DdRef             = internalhtml.DdRef
	DefsRef           = internalhtml.DefsRef
	DelElRef          = internalhtml.DelElRef
	DetailsRef        = internalhtml.DetailsRef
	DfnRef            = internalhtml.DfnRef
	DialogRef         = internalhtml.DialogRef
	DivRef            = internalhtml.DivRef
	DlRef             = internalhtml.DlRef
	DtRef             = internalhtml.DtRef
	EllipseRef        = internalhtml.EllipseRef
	EmRef             = internalhtml.EmRef
	EmbedRef          = internalhtml.EmbedRef
	FieldsetRef       = internalhtml.FieldsetRef
	FigcaptionRef     = internalhtml.FigcaptionRef
	FigureRef         = internalhtml.FigureRef
	FooterRef         = internalhtml.FooterRef
	ForeignObjectRef  = internalhtml.ForeignObjectRef
	FormRef           = internalhtml.FormRef
	GRef              = internalhtml.GRef
	H1Ref             = internalhtml.H1Ref
	H2Ref             = internalhtml.H2Ref
	H3Ref             = internalhtml.H3Ref
	H4Ref             = internalhtml.H4Ref
	H5Ref             = internalhtml.H5Ref
	H6Ref             = internalhtml.H6Ref
	HeadRef           = internalhtml.HeadRef
	HeaderRef         = internalhtml.HeaderRef
	HgroupRef         = internalhtml.HgroupRef
	HrRef             = internalhtml.HrRef
	HtmlRef           = internalhtml.HtmlRef
	IRef              = internalhtml.IRef
	IframeRef         = internalhtml.IframeRef
	ImageRef          = internalhtml.ImageRef
	ImgRef            = internalhtml.ImgRef
	InputRef          = internalhtml.InputRef
	InsElRef          = internalhtml.InsElRef
	KbdRef            = internalhtml.KbdRef
	LabelRef          = internalhtml.LabelRef
	LegendRef         = internalhtml.LegendRef
	LiRef             = internalhtml.LiRef
	LineRef           = internalhtml.LineRef
	LinearGradientRef = internalhtml.LinearGradientRef
	LinkRef           = internalhtml.LinkRef
	MainRef           = internalhtml.MainRef
	MapElRef          = internalhtml.MapElRef
	MarkRef           = internalhtml.MarkRef
	MarkerRef         = internalhtml.MarkerRef
	MaskRef           = internalhtml.MaskRef
	MenuRef           = internalhtml.MenuRef
	MenuItemRef       = internalhtml.MenuItemRef
	MetaRef           = internalhtml.MetaRef
	MeterRef          = internalhtml.MeterRef
	NavRef            = internalhtml.NavRef
	NoscriptRef       = internalhtml.NoscriptRef
	ObjectRef         = internalhtml.ObjectRef
	OlRef             = internalhtml.OlRef
	OptgroupRef       = internalhtml.OptgroupRef
	OptionRef         = internalhtml.OptionRef
	OutputRef         = internalhtml.OutputRef
	PRef              = internalhtml.PRef
	ParamRef          = internalhtml.ParamRef
	PathRef           = internalhtml.PathRef
	PatternRef        = internalhtml.PatternRef
	PictureRef        = internalhtml.PictureRef
	PolygonRef        = internalhtml.PolygonRef
	PolylineRef       = internalhtml.PolylineRef
	PortalRef         = internalhtml.PortalRef
	PreRef            = internalhtml.PreRef
	ProgressRef       = internalhtml.ProgressRef
	QRef              = internalhtml.QRef
	RadialGradientRef = internalhtml.RadialGradientRef
	RbRef             = internalhtml.RbRef
	RectRef           = internalhtml.RectRef
	RpRef             = internalhtml.RpRef
	RtRef             = internalhtml.RtRef
	RtcRef            = internalhtml.RtcRef
	RubyRef           = internalhtml.RubyRef
	SRef              = internalhtml.SRef
	SampRef           = internalhtml.SampRef
	ScriptRef         = internalhtml.ScriptRef
	SectionRef        = internalhtml.SectionRef
	SelectRef         = internalhtml.SelectRef
	SlotRef           = internalhtml.SlotRef
	SmallRef          = internalhtml.SmallRef
	SourceRef         = internalhtml.SourceRef
	SpanRef           = internalhtml.SpanRef
	StopRef           = internalhtml.StopRef
	StrongRef         = internalhtml.StrongRef
	StyleElRef        = internalhtml.StyleElRef
	SubRef            = internalhtml.SubRef
	SummaryRef        = internalhtml.SummaryRef
	SupRef            = internalhtml.SupRef
	SvgRef            = internalhtml.SvgRef
	SvgTextRef        = internalhtml.SvgTextRef
	TSpanRef          = internalhtml.TSpanRef
	TableRef          = internalhtml.TableRef
	TbodyRef          = internalhtml.TbodyRef
	TdRef             = internalhtml.TdRef
	TemplateRef       = internalhtml.TemplateRef
	TextareaRef       = internalhtml.TextareaRef
	TfootRef          = internalhtml.TfootRef
	ThRef             = internalhtml.ThRef
	TheadRef          = internalhtml.TheadRef
	TimeRef           = internalhtml.TimeRef
	TitleElRef        = internalhtml.TitleElRef
	TrRef             = internalhtml.TrRef
	TrackRef          = internalhtml.TrackRef
	URef              = internalhtml.URef
	UlRef             = internalhtml.UlRef
	UseRef            = internalhtml.UseRef
	VarRef            = internalhtml.VarRef
	VideoRef          = internalhtml.VideoRef
	WbrRef            = internalhtml.WbrRef
)
