// Code generated by tags_gen.go; DO NOT EDIT.
package html

// A creates an <a> element.
func A(items ...Item) *Element { return el("a", items...) }

// Abbr creates an <abbr> element.
func Abbr(items ...Item) *Element { return el("abbr", items...) }

// Address creates an <address> element.
func Address(items ...Item) *Element { return el("address", items...) }

// Area creates an <area> element.
func Area(items ...Item) *Element { return el("area", items...) }

// Article creates an <article> element.
func Article(items ...Item) *Element { return el("article", items...) }

// Aside creates an <aside> element.
func Aside(items ...Item) *Element { return el("aside", items...) }

// Audio creates an <audio> element.
func Audio(items ...Item) *Element { return el("audio", items...) }

// B creates a <b> element.
func B(items ...Item) *Element { return el("b", items...) }

// Base creates a <base> element.
func Base(items ...Item) *Element { return el("base", items...) }

// Bdi creates a <bdi> element.
func Bdi(items ...Item) *Element { return el("bdi", items...) }

// Bdo creates a <bdo> element.
func Bdo(items ...Item) *Element { return el("bdo", items...) }

// Blockquote creates a <blockquote> element.
func Blockquote(items ...Item) *Element { return el("blockquote", items...) }

// Body creates a <body> element.
func Body(items ...Item) *Element { return el("body", items...) }

// Br creates a <br> element.
func Br(items ...Item) *Element { return el("br", items...) }

// Button creates a <button> element.
func Button(items ...Item) *Element { return el("button", items...) }

// Canvas creates a <canvas> element.
func Canvas(items ...Item) *Element { return el("canvas", items...) }

// Caption creates a <caption> element.
func Caption(items ...Item) *Element { return el("caption", items...) }

// Circle creates a <circle> element.
func Circle(items ...Item) *Element { return el("circle", items...) }

// Cite creates a <cite> element.
func Cite(items ...Item) *Element { return el("cite", items...) }

// ClipPath creates a <clipPath> element.
func ClipPath(items ...Item) *Element { return el("clipPath", items...) }

// Code creates a <code> element.
func Code(items ...Item) *Element { return el("code", items...) }

// Col creates a <col> element.
func Col(items ...Item) *Element { return el("col", items...) }

// Colgroup creates a <colgroup> element.
func Colgroup(items ...Item) *Element { return el("colgroup", items...) }

// DataEl creates a <data> element.
func DataEl(items ...Item) *Element { return el("data", items...) }

// Datalist creates a <datalist> element.
func Datalist(items ...Item) *Element { return el("datalist", items...) }

// Dd creates a <dd> element.
func Dd(items ...Item) *Element { return el("dd", items...) }

// Defs creates a <defs> element.
func Defs(items ...Item) *Element { return el("defs", items...) }

// DelEl creates a <del> element.
func DelEl(items ...Item) *Element { return el("del", items...) }

// Details creates a <details> element.
func Details(items ...Item) *Element { return el("details", items...) }

// Dfn creates a <dfn> element.
func Dfn(items ...Item) *Element { return el("dfn", items...) }

// Dialog creates a <dialog> element.
func Dialog(items ...Item) *Element { return el("dialog", items...) }

// Div creates a <div> element.
func Div(items ...Item) *Element { return el("div", items...) }

// Dl creates a <dl> element.
func Dl(items ...Item) *Element { return el("dl", items...) }

// Dt creates a <dt> element.
func Dt(items ...Item) *Element { return el("dt", items...) }

// Ellipse creates an <ellipse> element.
func Ellipse(items ...Item) *Element { return el("ellipse", items...) }

// Em creates an <em> element.
func Em(items ...Item) *Element { return el("em", items...) }

// Embed creates an <embed> element.
func Embed(items ...Item) *Element { return el("embed", items...) }

// Fieldset creates a <fieldset> element.
func Fieldset(items ...Item) *Element { return el("fieldset", items...) }

// Figcaption creates a <figcaption> element.
func Figcaption(items ...Item) *Element { return el("figcaption", items...) }

// Figure creates a <figure> element.
func Figure(items ...Item) *Element { return el("figure", items...) }

// Footer creates a <footer> element.
func Footer(items ...Item) *Element { return el("footer", items...) }

// ForeignObject creates a <foreignObject> element.
func ForeignObject(items ...Item) *Element { return el("foreignObject", items...) }

// Form creates a <form> element.
func Form(items ...Item) *Element { return el("form", items...) }

// G creates a <g> element.
func G(items ...Item) *Element { return el("g", items...) }

// H1 creates an <h1> element.
func H1(items ...Item) *Element { return el("h1", items...) }

// H2 creates an <h2> element.
func H2(items ...Item) *Element { return el("h2", items...) }

// H3 creates an <h3> element.
func H3(items ...Item) *Element { return el("h3", items...) }

// H4 creates an <h4> element.
func H4(items ...Item) *Element { return el("h4", items...) }

// H5 creates an <h5> element.
func H5(items ...Item) *Element { return el("h5", items...) }

// H6 creates an <h6> element.
func H6(items ...Item) *Element { return el("h6", items...) }

// Head creates a <head> element.
func Head(items ...Item) *Element { return el("head", items...) }

// Header creates a <header> element.
func Header(items ...Item) *Element { return el("header", items...) }

// Hgroup creates an <hgroup> element.
func Hgroup(items ...Item) *Element { return el("hgroup", items...) }

// Hr creates an <hr> element.
func Hr(items ...Item) *Element { return el("hr", items...) }

// Html creates an <html> element.
func Html(items ...Item) *Element { return el("html", items...) }

// I creates an <i> element.
func I(items ...Item) *Element { return el("i", items...) }

// Iframe creates an <iframe> element.
func Iframe(items ...Item) *Element { return el("iframe", items...) }

// Image creates an <image> element.
func Image(items ...Item) *Element { return el("image", items...) }

// Img creates an <img> element.
func Img(items ...Item) *Element { return el("img", items...) }

// Input creates an <input> element.
func Input(items ...Item) *Element { return el("input", items...) }

// InsEl creates an <ins> element.
func InsEl(items ...Item) *Element { return el("ins", items...) }

// Kbd creates a <kbd> element.
func Kbd(items ...Item) *Element { return el("kbd", items...) }

// Label creates a <label> element.
func Label(items ...Item) *Element { return el("label", items...) }

// Legend creates a <legend> element.
func Legend(items ...Item) *Element { return el("legend", items...) }

// Li creates an <li> element.
func Li(items ...Item) *Element { return el("li", items...) }

// Line creates a <line> element.
func Line(items ...Item) *Element { return el("line", items...) }

// LinearGradient creates a <linearGradient> element.
func LinearGradient(items ...Item) *Element { return el("linearGradient", items...) }

// Link creates a <link> element.
func Link(items ...Item) *Element { return el("link", items...) }

// Main creates a <main> element.
func Main(items ...Item) *Element { return el("main", items...) }

// MapEl creates a <map> element.
func MapEl(items ...Item) *Element { return el("map", items...) }

// Mark creates a <mark> element.
func Mark(items ...Item) *Element { return el("mark", items...) }

// Marker creates a <marker> element.
func Marker(items ...Item) *Element { return el("marker", items...) }

// Mask creates a <mask> element.
func Mask(items ...Item) *Element { return el("mask", items...) }

// Menu creates a <menu> element.
func Menu(items ...Item) *Element { return el("menu", items...) }

// MenuItem creates a <menuitem> element.
func MenuItem(items ...Item) *Element { return el("menuitem", items...) }

// Meta creates a <meta> element.
func Meta(items ...Item) *Element { return el("meta", items...) }

// Meter creates a <meter> element.
func Meter(items ...Item) *Element { return el("meter", items...) }

// Nav creates a <nav> element.
func Nav(items ...Item) *Element { return el("nav", items...) }

// Noscript creates a <noscript> element.
func Noscript(items ...Item) *Element { return el("noscript", items...) }

// Object creates an <object> element.
func Object(items ...Item) *Element { return el("object", items...) }

// Ol creates an <ol> element.
func Ol(items ...Item) *Element { return el("ol", items...) }

// Optgroup creates an <optgroup> element.
func Optgroup(items ...Item) *Element { return el("optgroup", items...) }

// Option creates an <option> element.
func Option(items ...Item) *Element { return el("option", items...) }

// Output creates an <output> element.
func Output(items ...Item) *Element { return el("output", items...) }

// P creates a <p> element.
func P(items ...Item) *Element { return el("p", items...) }

// Param creates a <param> element.
func Param(items ...Item) *Element { return el("param", items...) }

// Path creates a <path> element.
func Path(items ...Item) *Element { return el("path", items...) }

// Pattern creates a <pattern> element.
func Pattern(items ...Item) *Element { return el("pattern", items...) }

// Picture creates a <picture> element.
func Picture(items ...Item) *Element { return el("picture", items...) }

// Polygon creates a <polygon> element.
func Polygon(items ...Item) *Element { return el("polygon", items...) }

// Polyline creates a <polyline> element.
func Polyline(items ...Item) *Element { return el("polyline", items...) }

// Portal creates a <portal> element.
func Portal(items ...Item) *Element { return el("portal", items...) }

// Pre creates a <pre> element.
func Pre(items ...Item) *Element { return el("pre", items...) }

// Progress creates a <progress> element.
func Progress(items ...Item) *Element { return el("progress", items...) }

// Q creates a <q> element.
func Q(items ...Item) *Element { return el("q", items...) }

// RadialGradient creates a <radialGradient> element.
func RadialGradient(items ...Item) *Element { return el("radialGradient", items...) }

// Rb creates an <rb> element.
func Rb(items ...Item) *Element { return el("rb", items...) }

// Rect creates a <rect> element.
func Rect(items ...Item) *Element { return el("rect", items...) }

// Rp creates an <rp> element.
func Rp(items ...Item) *Element { return el("rp", items...) }

// Rt creates an <rt> element.
func Rt(items ...Item) *Element { return el("rt", items...) }

// Rtc creates an <rtc> element.
func Rtc(items ...Item) *Element { return el("rtc", items...) }

// Ruby creates a <ruby> element.
func Ruby(items ...Item) *Element { return el("ruby", items...) }

// S creates an <s> element.
func S(items ...Item) *Element { return el("s", items...) }

// Samp creates a <samp> element.
func Samp(items ...Item) *Element { return el("samp", items...) }

// Script creates a <script> element.
func Script(items ...Item) *Element { return el("script", items...) }

// Section creates a <section> element.
func Section(items ...Item) *Element { return el("section", items...) }

// Select creates a <select> element.
func Select(items ...Item) *Element { return el("select", items...) }

// Slot creates a <slot> element.
func Slot(items ...Item) *Element { return el("slot", items...) }

// Small creates a <small> element.
func Small(items ...Item) *Element { return el("small", items...) }

// Source creates a <source> element.
func Source(items ...Item) *Element { return el("source", items...) }

// Span creates a <span> element.
func Span(items ...Item) *Element { return el("span", items...) }

// Stop creates a <stop> element.
func Stop(items ...Item) *Element { return el("stop", items...) }

// Strong creates a <strong> element.
func Strong(items ...Item) *Element { return el("strong", items...) }

// StyleEl creates a <style> element.
func StyleEl(items ...Item) *Element { return el("style", items...) }

// Sub creates a <sub> element.
func Sub(items ...Item) *Element { return el("sub", items...) }

// Summary creates a <summary> element.
func Summary(items ...Item) *Element { return el("summary", items...) }

// Sup creates a <sup> element.
func Sup(items ...Item) *Element { return el("sup", items...) }

// Svg creates an <svg> element.
func Svg(items ...Item) *Element { return el("svg", items...) }

// SvgText creates an SVG <text> element.
func SvgText(items ...Item) *Element { return el("text", items...) }

// TSpan creates a <tspan> element.
func TSpan(items ...Item) *Element { return el("tspan", items...) }

// Table creates a <table> element.
func Table(items ...Item) *Element { return el("table", items...) }

// Tbody creates a <tbody> element.
func Tbody(items ...Item) *Element { return el("tbody", items...) }

// Td creates a <td> element.
func Td(items ...Item) *Element { return el("td", items...) }

// Template creates a <template> element.
func Template(items ...Item) *Element { return el("template", items...) }

// Textarea creates a <textarea> element.
func Textarea(items ...Item) *Element { return el("textarea", items...) }

// Tfoot creates a <tfoot> element.
func Tfoot(items ...Item) *Element { return el("tfoot", items...) }

// Th creates a <th> element.
func Th(items ...Item) *Element { return el("th", items...) }

// Thead creates a <thead> element.
func Thead(items ...Item) *Element { return el("thead", items...) }

// Time creates a <time> element.
func Time(items ...Item) *Element { return el("time", items...) }

// TitleEl creates a <title> element.
func TitleEl(items ...Item) *Element { return el("title", items...) }

// Tr creates a <tr> element.
func Tr(items ...Item) *Element { return el("tr", items...) }

// Track creates a <track> element.
func Track(items ...Item) *Element { return el("track", items...) }

// U creates a <u> element.
func U(items ...Item) *Element { return el("u", items...) }

// Ul creates a <ul> element.
func Ul(items ...Item) *Element { return el("ul", items...) }

// Use creates a <use> element.
func Use(items ...Item) *Element { return el("use", items...) }

// Var creates a <var> element.
func Var(items ...Item) *Element { return el("var", items...) }

// Video creates a <video> element.
func Video(items ...Item) *Element { return el("video", items...) }

// Wbr creates a <wbr> element.
func Wbr(items ...Item) *Element { return el("wbr", items...) }
