// Code generated by tags_gen.go; DO NOT EDIT.
package html

func UseA(ctx ElementHookContext) *ARef {
	return NewARef(useElementRef[HTMLAElement](ctx))
}

func UseAbbr(ctx ElementHookContext) *AbbrRef {
	return NewAbbrRef(useElementRef[HTMLAbbrElement](ctx))
}

func UseAddress(ctx ElementHookContext) *AddressRef {
	return NewAddressRef(useElementRef[HTMLAddressElement](ctx))
}

func UseArea(ctx ElementHookContext) *AreaRef {
	return NewAreaRef(useElementRef[HTMLAreaElement](ctx))
}

func UseArticle(ctx ElementHookContext) *ArticleRef {
	return NewArticleRef(useElementRef[HTMLArticleElement](ctx))
}

func UseAside(ctx ElementHookContext) *AsideRef {
	return NewAsideRef(useElementRef[HTMLAsideElement](ctx))
}

func UseAudio(ctx ElementHookContext) *AudioRef {
	return NewAudioRef(useElementRef[HTMLAudioElement](ctx))
}

func UseB(ctx ElementHookContext) *BRef {
	return NewBRef(useElementRef[HTMLBElement](ctx))
}

func UseBase(ctx ElementHookContext) *BaseRef {
	return NewBaseRef(useElementRef[HTMLBaseElement](ctx))
}

func UseBdi(ctx ElementHookContext) *BdiRef {
	return NewBdiRef(useElementRef[HTMLBdiElement](ctx))
}

func UseBdo(ctx ElementHookContext) *BdoRef {
	return NewBdoRef(useElementRef[HTMLBdoElement](ctx))
}

func UseBlockquote(ctx ElementHookContext) *BlockquoteRef {
	return NewBlockquoteRef(useElementRef[HTMLBlockquoteElement](ctx))
}

func UseBody(ctx ElementHookContext) *BodyRef {
	return NewBodyRef(useElementRef[HTMLBodyElement](ctx))
}

func UseBr(ctx ElementHookContext) *BrRef {
	return NewBrRef(useElementRef[HTMLBrElement](ctx))
}

func UseButton(ctx ElementHookContext) *ButtonRef {
	return NewButtonRef(useElementRef[HTMLButtonElement](ctx))
}

func UseCanvas(ctx ElementHookContext) *CanvasRef {
	return NewCanvasRef(useElementRef[HTMLCanvasElement](ctx))
}

func UseCaption(ctx ElementHookContext) *CaptionRef {
	return NewCaptionRef(useElementRef[HTMLCaptionElement](ctx))
}

func UseCircle(ctx ElementHookContext) *CircleRef {
	return NewCircleRef(useElementRef[SVGCircleElement](ctx))
}

func UseCite(ctx ElementHookContext) *CiteRef {
	return NewCiteRef(useElementRef[HTMLCiteElement](ctx))
}

func UseClipPath(ctx ElementHookContext) *ClipPathRef {
	return NewClipPathRef(useElementRef[SVGClipPathElement](ctx))
}

func UseCode(ctx ElementHookContext) *CodeRef {
	return NewCodeRef(useElementRef[HTMLCodeElement](ctx))
}

func UseCol(ctx ElementHookContext) *ColRef {
	return NewColRef(useElementRef[HTMLColElement](ctx))
}

func UseColgroup(ctx ElementHookContext) *ColgroupRef {
	return NewColgroupRef(useElementRef[HTMLColgroupElement](ctx))
}

func UseDataEl(ctx ElementHookContext) *DataElRef {
	return NewDataElRef(useElementRef[HTMLDataElement](ctx))
}

func UseDatalist(ctx ElementHookContext) *DatalistRef {
	return NewDatalistRef(useElementRef[HTMLDatalistElement](ctx))
}

func UseDd(ctx ElementHookContext) *DdRef {
	return NewDdRef(useElementRef[HTMLDdElement](ctx))
}

func UseDefs(ctx ElementHookContext) *DefsRef {
	return NewDefsRef(useElementRef[SVGDefsElement](ctx))
}

func UseDelEl(ctx ElementHookContext) *DelElRef {
	return NewDelElRef(useElementRef[HTMLDelElement](ctx))
}

func UseDetails(ctx ElementHookContext) *DetailsRef {
	return NewDetailsRef(useElementRef[HTMLDetailsElement](ctx))
}

func UseDfn(ctx ElementHookContext) *DfnRef {
	return NewDfnRef(useElementRef[HTMLDfnElement](ctx))
}

func UseDialog(ctx ElementHookContext) *DialogRef {
	return NewDialogRef(useElementRef[HTMLDialogElement](ctx))
}

func UseDiv(ctx ElementHookContext) *DivRef {
	return NewDivRef(useElementRef[HTMLDivElement](ctx))
}

func UseDl(ctx ElementHookContext) *DlRef {
	return NewDlRef(useElementRef[HTMLDlElement](ctx))
}

func UseDt(ctx ElementHookContext) *DtRef {
	return NewDtRef(useElementRef[HTMLDtElement](ctx))
}

func UseEllipse(ctx ElementHookContext) *EllipseRef {
	return NewEllipseRef(useElementRef[SVGEllipseElement](ctx))
}

func UseEm(ctx ElementHookContext) *EmRef {
	return NewEmRef(useElementRef[HTMLEmElement](ctx))
}

func UseEmbed(ctx ElementHookContext) *EmbedRef {
	return NewEmbedRef(useElementRef[HTMLEmbedElement](ctx))
}

func UseFieldset(ctx ElementHookContext) *FieldsetRef {
	return NewFieldsetRef(useElementRef[HTMLFieldsetElement](ctx))
}

func UseFigcaption(ctx ElementHookContext) *FigcaptionRef {
	return NewFigcaptionRef(useElementRef[HTMLFigcaptionElement](ctx))
}

func UseFigure(ctx ElementHookContext) *FigureRef {
	return NewFigureRef(useElementRef[HTMLFigureElement](ctx))
}

func UseFooter(ctx ElementHookContext) *FooterRef {
	return NewFooterRef(useElementRef[HTMLFooterElement](ctx))
}

func UseForeignObject(ctx ElementHookContext) *ForeignObjectRef {
	return NewForeignObjectRef(useElementRef[SVGForeignObjectElement](ctx))
}

func UseForm(ctx ElementHookContext) *FormRef {
	return NewFormRef(useElementRef[HTMLFormElement](ctx))
}

func UseG(ctx ElementHookContext) *GRef {
	return NewGRef(useElementRef[SVGGElement](ctx))
}

func UseH1(ctx ElementHookContext) *H1Ref {
	return NewH1Ref(useElementRef[HTMLH1Element](ctx))
}

func UseH2(ctx ElementHookContext) *H2Ref {
	return NewH2Ref(useElementRef[HTMLH2Element](ctx))
}

func UseH3(ctx ElementHookContext) *H3Ref {
	return NewH3Ref(useElementRef[HTMLH3Element](ctx))
}

func UseH4(ctx ElementHookContext) *H4Ref {
	return NewH4Ref(useElementRef[HTMLH4Element](ctx))
}

func UseH5(ctx ElementHookContext) *H5Ref {
	return NewH5Ref(useElementRef[HTMLH5Element](ctx))
}

func UseH6(ctx ElementHookContext) *H6Ref {
	return NewH6Ref(useElementRef[HTMLH6Element](ctx))
}

func UseHead(ctx ElementHookContext) *HeadRef {
	return NewHeadRef(useElementRef[HTMLHeadElement](ctx))
}

func UseHeader(ctx ElementHookContext) *HeaderRef {
	return NewHeaderRef(useElementRef[HTMLHeaderElement](ctx))
}

func UseHgroup(ctx ElementHookContext) *HgroupRef {
	return NewHgroupRef(useElementRef[HTMLHgroupElement](ctx))
}

func UseHr(ctx ElementHookContext) *HrRef {
	return NewHrRef(useElementRef[HTMLHrElement](ctx))
}

func UseHtml(ctx ElementHookContext) *HtmlRef {
	return NewHtmlRef(useElementRef[HTMLHtmlElement](ctx))
}

func UseI(ctx ElementHookContext) *IRef {
	return NewIRef(useElementRef[HTMLIElement](ctx))
}

func UseIframe(ctx ElementHookContext) *IframeRef {
	return NewIframeRef(useElementRef[HTMLIframeElement](ctx))
}

func UseImage(ctx ElementHookContext) *ImageRef {
	return NewImageRef(useElementRef[SVGImageElement](ctx))
}

func UseImg(ctx ElementHookContext) *ImgRef {
	return NewImgRef(useElementRef[HTMLImgElement](ctx))
}

func UseInput(ctx ElementHookContext) *InputRef {
	return NewInputRef(useElementRef[HTMLInputElement](ctx))
}

func UseInsEl(ctx ElementHookContext) *InsElRef {
	return NewInsElRef(useElementRef[HTMLInsElement](ctx))
}

func UseKbd(ctx ElementHookContext) *KbdRef {
	return NewKbdRef(useElementRef[HTMLKbdElement](ctx))
}

func UseLabel(ctx ElementHookContext) *LabelRef {
	return NewLabelRef(useElementRef[HTMLLabelElement](ctx))
}

func UseLegend(ctx ElementHookContext) *LegendRef {
	return NewLegendRef(useElementRef[HTMLLegendElement](ctx))
}

func UseLi(ctx ElementHookContext) *LiRef {
	return NewLiRef(useElementRef[HTMLLiElement](ctx))
}

func UseLine(ctx ElementHookContext) *LineRef {
	return NewLineRef(useElementRef[SVGLineElement](ctx))
}

func UseLinearGradient(ctx ElementHookContext) *LinearGradientRef {
	return NewLinearGradientRef(useElementRef[SVGLinearGradientElement](ctx))
}

func UseLink(ctx ElementHookContext) *LinkRef {
	return NewLinkRef(useElementRef[HTMLLinkElement](ctx))
}

func UseMain(ctx ElementHookContext) *MainRef {
	return NewMainRef(useElementRef[HTMLMainElement](ctx))
}

func UseMapEl(ctx ElementHookContext) *MapElRef {
	return NewMapElRef(useElementRef[HTMLMapElement](ctx))
}

func UseMark(ctx ElementHookContext) *MarkRef {
	return NewMarkRef(useElementRef[HTMLMarkElement](ctx))
}

func UseMarker(ctx ElementHookContext) *MarkerRef {
	return NewMarkerRef(useElementRef[SVGMarkerElement](ctx))
}

func UseMask(ctx ElementHookContext) *MaskRef {
	return NewMaskRef(useElementRef[SVGMaskElement](ctx))
}

func UseMenu(ctx ElementHookContext) *MenuRef {
	return NewMenuRef(useElementRef[HTMLMenuElement](ctx))
}

func UseMenuItem(ctx ElementHookContext) *MenuItemRef {
	return NewMenuItemRef(useElementRef[HTMLMenuItemElement](ctx))
}

func UseMeta(ctx ElementHookContext) *MetaRef {
	return NewMetaRef(useElementRef[HTMLMetaElement](ctx))
}

func UseMeter(ctx ElementHookContext) *MeterRef {
	return NewMeterRef(useElementRef[HTMLMeterElement](ctx))
}

func UseNav(ctx ElementHookContext) *NavRef {
	return NewNavRef(useElementRef[HTMLNavElement](ctx))
}

func UseNoscript(ctx ElementHookContext) *NoscriptRef {
	return NewNoscriptRef(useElementRef[HTMLNoscriptElement](ctx))
}

func UseObject(ctx ElementHookContext) *ObjectRef {
	return NewObjectRef(useElementRef[HTMLObjectElement](ctx))
}

func UseOl(ctx ElementHookContext) *OlRef {
	return NewOlRef(useElementRef[HTMLOlElement](ctx))
}

func UseOptgroup(ctx ElementHookContext) *OptgroupRef {
	return NewOptgroupRef(useElementRef[HTMLOptgroupElement](ctx))
}

func UseOption(ctx ElementHookContext) *OptionRef {
	return NewOptionRef(useElementRef[HTMLOptionElement](ctx))
}

func UseOutput(ctx ElementHookContext) *OutputRef {
	return NewOutputRef(useElementRef[HTMLOutputElement](ctx))
}

func UseP(ctx ElementHookContext) *PRef {
	return NewPRef(useElementRef[HTMLPElement](ctx))
}

func UseParam(ctx ElementHookContext) *ParamRef {
	return NewParamRef(useElementRef[HTMLParamElement](ctx))
}

func UsePath(ctx ElementHookContext) *PathRef {
	return NewPathRef(useElementRef[SVGPathElement](ctx))
}

func UsePattern(ctx ElementHookContext) *PatternRef {
	return NewPatternRef(useElementRef[SVGPatternElement](ctx))
}

func UsePicture(ctx ElementHookContext) *PictureRef {
	return NewPictureRef(useElementRef[HTMLPictureElement](ctx))
}

func UsePolygon(ctx ElementHookContext) *PolygonRef {
	return NewPolygonRef(useElementRef[SVGPolygonElement](ctx))
}

func UsePolyline(ctx ElementHookContext) *PolylineRef {
	return NewPolylineRef(useElementRef[SVGPolylineElement](ctx))
}

func UsePortal(ctx ElementHookContext) *PortalRef {
	return NewPortalRef(useElementRef[HTMLPortalElement](ctx))
}

func UsePre(ctx ElementHookContext) *PreRef {
	return NewPreRef(useElementRef[HTMLPreElement](ctx))
}

func UseProgress(ctx ElementHookContext) *ProgressRef {
	return NewProgressRef(useElementRef[HTMLProgressElement](ctx))
}

func UseQ(ctx ElementHookContext) *QRef {
	return NewQRef(useElementRef[HTMLQElement](ctx))
}

func UseRadialGradient(ctx ElementHookContext) *RadialGradientRef {
	return NewRadialGradientRef(useElementRef[SVGRadialGradientElement](ctx))
}

func UseRb(ctx ElementHookContext) *RbRef {
	return NewRbRef(useElementRef[HTMLRbElement](ctx))
}

func UseRect(ctx ElementHookContext) *RectRef {
	return NewRectRef(useElementRef[SVGRectElement](ctx))
}

func UseRp(ctx ElementHookContext) *RpRef {
	return NewRpRef(useElementRef[HTMLRpElement](ctx))
}

func UseRt(ctx ElementHookContext) *RtRef {
	return NewRtRef(useElementRef[HTMLRtElement](ctx))
}

func UseRtc(ctx ElementHookContext) *RtcRef {
	return NewRtcRef(useElementRef[HTMLRtcElement](ctx))
}

func UseRuby(ctx ElementHookContext) *RubyRef {
	return NewRubyRef(useElementRef[HTMLRubyElement](ctx))
}

func UseS(ctx ElementHookContext) *SRef {
	return NewSRef(useElementRef[HTMLSElement](ctx))
}

func UseSamp(ctx ElementHookContext) *SampRef {
	return NewSampRef(useElementRef[HTMLSampElement](ctx))
}

func UseScript(ctx ElementHookContext) *ScriptRef {
	return NewScriptRef(useElementRef[HTMLScriptElement](ctx))
}

func UseSection(ctx ElementHookContext) *SectionRef {
	return NewSectionRef(useElementRef[HTMLSectionElement](ctx))
}

func UseSelect(ctx ElementHookContext) *SelectRef {
	return NewSelectRef(useElementRef[HTMLSelectElement](ctx))
}

func UseSlot(ctx ElementHookContext) *SlotRef {
	return NewSlotRef(useElementRef[HTMLSlotElement](ctx))
}

func UseSmall(ctx ElementHookContext) *SmallRef {
	return NewSmallRef(useElementRef[HTMLSmallElement](ctx))
}

func UseSource(ctx ElementHookContext) *SourceRef {
	return NewSourceRef(useElementRef[HTMLSourceElement](ctx))
}

func UseSpan(ctx ElementHookContext) *SpanRef {
	return NewSpanRef(useElementRef[HTMLSpanElement](ctx))
}

func UseStop(ctx ElementHookContext) *StopRef {
	return NewStopRef(useElementRef[SVGStopElement](ctx))
}

func UseStrong(ctx ElementHookContext) *StrongRef {
	return NewStrongRef(useElementRef[HTMLStrongElement](ctx))
}

func UseStyleEl(ctx ElementHookContext) *StyleElRef {
	return NewStyleElRef(useElementRef[HTMLStyleElement](ctx))
}

func UseSub(ctx ElementHookContext) *SubRef {
	return NewSubRef(useElementRef[HTMLSubElement](ctx))
}

func UseSummary(ctx ElementHookContext) *SummaryRef {
	return NewSummaryRef(useElementRef[HTMLSummaryElement](ctx))
}

func UseSup(ctx ElementHookContext) *SupRef {
	return NewSupRef(useElementRef[HTMLSupElement](ctx))
}

func UseSvg(ctx ElementHookContext) *SvgRef {
	return NewSvgRef(useElementRef[SVGSvgElement](ctx))
}

func UseSvgText(ctx ElementHookContext) *SvgTextRef {
	return NewSvgTextRef(useElementRef[SVGSvgTextElement](ctx))
}

func UseTSpan(ctx ElementHookContext) *TSpanRef {
	return NewTSpanRef(useElementRef[SVGTSpanElement](ctx))
}

func UseTable(ctx ElementHookContext) *TableRef {
	return NewTableRef(useElementRef[HTMLTableElement](ctx))
}

func UseTbody(ctx ElementHookContext) *TbodyRef {
	return NewTbodyRef(useElementRef[HTMLTbodyElement](ctx))
}

func UseTd(ctx ElementHookContext) *TdRef {
	return NewTdRef(useElementRef[HTMLTdElement](ctx))
}

func UseTemplate(ctx ElementHookContext) *TemplateRef {
	return NewTemplateRef(useElementRef[HTMLTemplateElement](ctx))
}

func UseTextarea(ctx ElementHookContext) *TextareaRef {
	return NewTextareaRef(useElementRef[HTMLTextareaElement](ctx))
}

func UseTfoot(ctx ElementHookContext) *TfootRef {
	return NewTfootRef(useElementRef[HTMLTfootElement](ctx))
}

func UseTh(ctx ElementHookContext) *ThRef {
	return NewThRef(useElementRef[HTMLThElement](ctx))
}

func UseThead(ctx ElementHookContext) *TheadRef {
	return NewTheadRef(useElementRef[HTMLTheadElement](ctx))
}

func UseTime(ctx ElementHookContext) *TimeRef {
	return NewTimeRef(useElementRef[HTMLTimeElement](ctx))
}

func UseTitleEl(ctx ElementHookContext) *TitleElRef {
	return NewTitleElRef(useElementRef[HTMLTitleElement](ctx))
}

func UseTr(ctx ElementHookContext) *TrRef {
	return NewTrRef(useElementRef[HTMLTrElement](ctx))
}

func UseTrack(ctx ElementHookContext) *TrackRef {
	return NewTrackRef(useElementRef[HTMLTrackElement](ctx))
}

func UseU(ctx ElementHookContext) *URef {
	return NewURef(useElementRef[HTMLUElement](ctx))
}

func UseUl(ctx ElementHookContext) *UlRef {
	return NewUlRef(useElementRef[HTMLUlElement](ctx))
}

func UseUse(ctx ElementHookContext) *UseRef {
	return NewUseRef(useElementRef[SVGUseElement](ctx))
}

func UseVar(ctx ElementHookContext) *VarRef {
	return NewVarRef(useElementRef[HTMLVarElement](ctx))
}

func UseVideo(ctx ElementHookContext) *VideoRef {
	return NewVideoRef(useElementRef[HTMLVideoElement](ctx))
}

func UseWbr(ctx ElementHookContext) *WbrRef {
	return NewWbrRef(useElementRef[HTMLWbrElement](ctx))
}
