// Code generated by tags_gen.go; DO NOT EDIT.
package html

type HTMLAElement struct{}
func (HTMLAElement) elementDescriptor() {}
func (HTMLAElement) TagName() string { return "a" }

type HTMLAbbrElement struct{}
func (HTMLAbbrElement) elementDescriptor() {}
func (HTMLAbbrElement) TagName() string { return "abbr" }

type HTMLAddressElement struct{}
func (HTMLAddressElement) elementDescriptor() {}
func (HTMLAddressElement) TagName() string { return "address" }

type HTMLAreaElement struct{}
func (HTMLAreaElement) elementDescriptor() {}
func (HTMLAreaElement) TagName() string { return "area" }

type HTMLArticleElement struct{}
func (HTMLArticleElement) elementDescriptor() {}
func (HTMLArticleElement) TagName() string { return "article" }

type HTMLAsideElement struct{}
func (HTMLAsideElement) elementDescriptor() {}
func (HTMLAsideElement) TagName() string { return "aside" }

type HTMLAudioElement struct{}
func (HTMLAudioElement) elementDescriptor() {}
func (HTMLAudioElement) TagName() string { return "audio" }

type HTMLBElement struct{}
func (HTMLBElement) elementDescriptor() {}
func (HTMLBElement) TagName() string { return "b" }

type HTMLBaseElement struct{}
func (HTMLBaseElement) elementDescriptor() {}
func (HTMLBaseElement) TagName() string { return "base" }

type HTMLBdiElement struct{}
func (HTMLBdiElement) elementDescriptor() {}
func (HTMLBdiElement) TagName() string { return "bdi" }

type HTMLBdoElement struct{}
func (HTMLBdoElement) elementDescriptor() {}
func (HTMLBdoElement) TagName() string { return "bdo" }

type HTMLBlockquoteElement struct{}
func (HTMLBlockquoteElement) elementDescriptor() {}
func (HTMLBlockquoteElement) TagName() string { return "blockquote" }

type HTMLBodyElement struct{}
func (HTMLBodyElement) elementDescriptor() {}
func (HTMLBodyElement) TagName() string { return "body" }

type HTMLBrElement struct{}
func (HTMLBrElement) elementDescriptor() {}
func (HTMLBrElement) TagName() string { return "br" }

type HTMLButtonElement struct{}
func (HTMLButtonElement) elementDescriptor() {}
func (HTMLButtonElement) TagName() string { return "button" }

type HTMLCanvasElement struct{}
func (HTMLCanvasElement) elementDescriptor() {}
func (HTMLCanvasElement) TagName() string { return "canvas" }

type HTMLCaptionElement struct{}
func (HTMLCaptionElement) elementDescriptor() {}
func (HTMLCaptionElement) TagName() string { return "caption" }

type SVGCircleElement struct{}
func (SVGCircleElement) elementDescriptor() {}
func (SVGCircleElement) TagName() string { return "circle" }

type HTMLCiteElement struct{}
func (HTMLCiteElement) elementDescriptor() {}
func (HTMLCiteElement) TagName() string { return "cite" }

type SVGClipPathElement struct{}
func (SVGClipPathElement) elementDescriptor() {}
func (SVGClipPathElement) TagName() string { return "clipPath" }

type HTMLCodeElement struct{}
func (HTMLCodeElement) elementDescriptor() {}
func (HTMLCodeElement) TagName() string { return "code" }

type HTMLColElement struct{}
func (HTMLColElement) elementDescriptor() {}
func (HTMLColElement) TagName() string { return "col" }

type HTMLColgroupElement struct{}
func (HTMLColgroupElement) elementDescriptor() {}
func (HTMLColgroupElement) TagName() string { return "colgroup" }

type HTMLDataElement struct{}
func (HTMLDataElement) elementDescriptor() {}
func (HTMLDataElement) TagName() string { return "data" }

type HTMLDatalistElement struct{}
func (HTMLDatalistElement) elementDescriptor() {}
func (HTMLDatalistElement) TagName() string { return "datalist" }

type HTMLDdElement struct{}
func (HTMLDdElement) elementDescriptor() {}
func (HTMLDdElement) TagName() string { return "dd" }

type SVGDefsElement struct{}
func (SVGDefsElement) elementDescriptor() {}
func (SVGDefsElement) TagName() string { return "defs" }

type HTMLDelElement struct{}
func (HTMLDelElement) elementDescriptor() {}
func (HTMLDelElement) TagName() string { return "del" }

type HTMLDetailsElement struct{}
func (HTMLDetailsElement) elementDescriptor() {}
func (HTMLDetailsElement) TagName() string { return "details" }

type HTMLDfnElement struct{}
func (HTMLDfnElement) elementDescriptor() {}
func (HTMLDfnElement) TagName() string { return "dfn" }

type HTMLDialogElement struct{}
func (HTMLDialogElement) elementDescriptor() {}
func (HTMLDialogElement) TagName() string { return "dialog" }

type HTMLDivElement struct{}
func (HTMLDivElement) elementDescriptor() {}
func (HTMLDivElement) TagName() string { return "div" }

type HTMLDlElement struct{}
func (HTMLDlElement) elementDescriptor() {}
func (HTMLDlElement) TagName() string { return "dl" }

type HTMLDtElement struct{}
func (HTMLDtElement) elementDescriptor() {}
func (HTMLDtElement) TagName() string { return "dt" }

type SVGEllipseElement struct{}
func (SVGEllipseElement) elementDescriptor() {}
func (SVGEllipseElement) TagName() string { return "ellipse" }

type HTMLEmElement struct{}
func (HTMLEmElement) elementDescriptor() {}
func (HTMLEmElement) TagName() string { return "em" }

type HTMLEmbedElement struct{}
func (HTMLEmbedElement) elementDescriptor() {}
func (HTMLEmbedElement) TagName() string { return "embed" }

type HTMLFieldsetElement struct{}
func (HTMLFieldsetElement) elementDescriptor() {}
func (HTMLFieldsetElement) TagName() string { return "fieldset" }

type HTMLFigcaptionElement struct{}
func (HTMLFigcaptionElement) elementDescriptor() {}
func (HTMLFigcaptionElement) TagName() string { return "figcaption" }

type HTMLFigureElement struct{}
func (HTMLFigureElement) elementDescriptor() {}
func (HTMLFigureElement) TagName() string { return "figure" }

type HTMLFooterElement struct{}
func (HTMLFooterElement) elementDescriptor() {}
func (HTMLFooterElement) TagName() string { return "footer" }

type SVGForeignObjectElement struct{}
func (SVGForeignObjectElement) elementDescriptor() {}
func (SVGForeignObjectElement) TagName() string { return "foreignObject" }

type HTMLFormElement struct{}
func (HTMLFormElement) elementDescriptor() {}
func (HTMLFormElement) TagName() string { return "form" }

type SVGGElement struct{}
func (SVGGElement) elementDescriptor() {}
func (SVGGElement) TagName() string { return "g" }

type HTMLH1Element struct{}
func (HTMLH1Element) elementDescriptor() {}
func (HTMLH1Element) TagName() string { return "h1" }

type HTMLH2Element struct{}
func (HTMLH2Element) elementDescriptor() {}
func (HTMLH2Element) TagName() string { return "h2" }

type HTMLH3Element struct{}
func (HTMLH3Element) elementDescriptor() {}
func (HTMLH3Element) TagName() string { return "h3" }

type HTMLH4Element struct{}
func (HTMLH4Element) elementDescriptor() {}
func (HTMLH4Element) TagName() string { return "h4" }

type HTMLH5Element struct{}
func (HTMLH5Element) elementDescriptor() {}
func (HTMLH5Element) TagName() string { return "h5" }

type HTMLH6Element struct{}
func (HTMLH6Element) elementDescriptor() {}
func (HTMLH6Element) TagName() string { return "h6" }

type HTMLHeadElement struct{}
func (HTMLHeadElement) elementDescriptor() {}
func (HTMLHeadElement) TagName() string { return "head" }

type HTMLHeaderElement struct{}
func (HTMLHeaderElement) elementDescriptor() {}
func (HTMLHeaderElement) TagName() string { return "header" }

type HTMLHgroupElement struct{}
func (HTMLHgroupElement) elementDescriptor() {}
func (HTMLHgroupElement) TagName() string { return "hgroup" }

type HTMLHrElement struct{}
func (HTMLHrElement) elementDescriptor() {}
func (HTMLHrElement) TagName() string { return "hr" }

type HTMLHtmlElement struct{}
func (HTMLHtmlElement) elementDescriptor() {}
func (HTMLHtmlElement) TagName() string { return "html" }

type HTMLIElement struct{}
func (HTMLIElement) elementDescriptor() {}
func (HTMLIElement) TagName() string { return "i" }

type HTMLIframeElement struct{}
func (HTMLIframeElement) elementDescriptor() {}
func (HTMLIframeElement) TagName() string { return "iframe" }

type SVGImageElement struct{}
func (SVGImageElement) elementDescriptor() {}
func (SVGImageElement) TagName() string { return "image" }

type HTMLImgElement struct{}
func (HTMLImgElement) elementDescriptor() {}
func (HTMLImgElement) TagName() string { return "img" }

type HTMLInputElement struct{}
func (HTMLInputElement) elementDescriptor() {}
func (HTMLInputElement) TagName() string { return "input" }

type HTMLInsElement struct{}
func (HTMLInsElement) elementDescriptor() {}
func (HTMLInsElement) TagName() string { return "ins" }

type HTMLKbdElement struct{}
func (HTMLKbdElement) elementDescriptor() {}
func (HTMLKbdElement) TagName() string { return "kbd" }

type HTMLLabelElement struct{}
func (HTMLLabelElement) elementDescriptor() {}
func (HTMLLabelElement) TagName() string { return "label" }

type HTMLLegendElement struct{}
func (HTMLLegendElement) elementDescriptor() {}
func (HTMLLegendElement) TagName() string { return "legend" }

type HTMLLiElement struct{}
func (HTMLLiElement) elementDescriptor() {}
func (HTMLLiElement) TagName() string { return "li" }

type SVGLineElement struct{}
func (SVGLineElement) elementDescriptor() {}
func (SVGLineElement) TagName() string { return "line" }

type SVGLinearGradientElement struct{}
func (SVGLinearGradientElement) elementDescriptor() {}
func (SVGLinearGradientElement) TagName() string { return "linearGradient" }

type HTMLLinkElement struct{}
func (HTMLLinkElement) elementDescriptor() {}
func (HTMLLinkElement) TagName() string { return "link" }

type HTMLMainElement struct{}
func (HTMLMainElement) elementDescriptor() {}
func (HTMLMainElement) TagName() string { return "main" }

type HTMLMapElement struct{}
func (HTMLMapElement) elementDescriptor() {}
func (HTMLMapElement) TagName() string { return "map" }

type HTMLMarkElement struct{}
func (HTMLMarkElement) elementDescriptor() {}
func (HTMLMarkElement) TagName() string { return "mark" }

type SVGMarkerElement struct{}
func (SVGMarkerElement) elementDescriptor() {}
func (SVGMarkerElement) TagName() string { return "marker" }

type SVGMaskElement struct{}
func (SVGMaskElement) elementDescriptor() {}
func (SVGMaskElement) TagName() string { return "mask" }

type HTMLMenuElement struct{}
func (HTMLMenuElement) elementDescriptor() {}
func (HTMLMenuElement) TagName() string { return "menu" }

type HTMLMenuItemElement struct{}
func (HTMLMenuItemElement) elementDescriptor() {}
func (HTMLMenuItemElement) TagName() string { return "menuitem" }

type HTMLMetaElement struct{}
func (HTMLMetaElement) elementDescriptor() {}
func (HTMLMetaElement) TagName() string { return "meta" }

type HTMLMeterElement struct{}
func (HTMLMeterElement) elementDescriptor() {}
func (HTMLMeterElement) TagName() string { return "meter" }

type HTMLNavElement struct{}
func (HTMLNavElement) elementDescriptor() {}
func (HTMLNavElement) TagName() string { return "nav" }

type HTMLNoscriptElement struct{}
func (HTMLNoscriptElement) elementDescriptor() {}
func (HTMLNoscriptElement) TagName() string { return "noscript" }

type HTMLObjectElement struct{}
func (HTMLObjectElement) elementDescriptor() {}
func (HTMLObjectElement) TagName() string { return "object" }

type HTMLOlElement struct{}
func (HTMLOlElement) elementDescriptor() {}
func (HTMLOlElement) TagName() string { return "ol" }

type HTMLOptgroupElement struct{}
func (HTMLOptgroupElement) elementDescriptor() {}
func (HTMLOptgroupElement) TagName() string { return "optgroup" }

type HTMLOptionElement struct{}
func (HTMLOptionElement) elementDescriptor() {}
func (HTMLOptionElement) TagName() string { return "option" }

type HTMLOutputElement struct{}
func (HTMLOutputElement) elementDescriptor() {}
func (HTMLOutputElement) TagName() string { return "output" }

type HTMLPElement struct{}
func (HTMLPElement) elementDescriptor() {}
func (HTMLPElement) TagName() string { return "p" }

type HTMLParamElement struct{}
func (HTMLParamElement) elementDescriptor() {}
func (HTMLParamElement) TagName() string { return "param" }

type SVGPathElement struct{}
func (SVGPathElement) elementDescriptor() {}
func (SVGPathElement) TagName() string { return "path" }

type SVGPatternElement struct{}
func (SVGPatternElement) elementDescriptor() {}
func (SVGPatternElement) TagName() string { return "pattern" }

type HTMLPictureElement struct{}
func (HTMLPictureElement) elementDescriptor() {}
func (HTMLPictureElement) TagName() string { return "picture" }

type SVGPolygonElement struct{}
func (SVGPolygonElement) elementDescriptor() {}
func (SVGPolygonElement) TagName() string { return "polygon" }

type SVGPolylineElement struct{}
func (SVGPolylineElement) elementDescriptor() {}
func (SVGPolylineElement) TagName() string { return "polyline" }

type HTMLPortalElement struct{}
func (HTMLPortalElement) elementDescriptor() {}
func (HTMLPortalElement) TagName() string { return "portal" }

type HTMLPreElement struct{}
func (HTMLPreElement) elementDescriptor() {}
func (HTMLPreElement) TagName() string { return "pre" }

type HTMLProgressElement struct{}
func (HTMLProgressElement) elementDescriptor() {}
func (HTMLProgressElement) TagName() string { return "progress" }

type HTMLQElement struct{}
func (HTMLQElement) elementDescriptor() {}
func (HTMLQElement) TagName() string { return "q" }

type SVGRadialGradientElement struct{}
func (SVGRadialGradientElement) elementDescriptor() {}
func (SVGRadialGradientElement) TagName() string { return "radialGradient" }

type HTMLRbElement struct{}
func (HTMLRbElement) elementDescriptor() {}
func (HTMLRbElement) TagName() string { return "rb" }

type SVGRectElement struct{}
func (SVGRectElement) elementDescriptor() {}
func (SVGRectElement) TagName() string { return "rect" }

type HTMLRpElement struct{}
func (HTMLRpElement) elementDescriptor() {}
func (HTMLRpElement) TagName() string { return "rp" }

type HTMLRtElement struct{}
func (HTMLRtElement) elementDescriptor() {}
func (HTMLRtElement) TagName() string { return "rt" }

type HTMLRtcElement struct{}
func (HTMLRtcElement) elementDescriptor() {}
func (HTMLRtcElement) TagName() string { return "rtc" }

type HTMLRubyElement struct{}
func (HTMLRubyElement) elementDescriptor() {}
func (HTMLRubyElement) TagName() string { return "ruby" }

type HTMLSElement struct{}
func (HTMLSElement) elementDescriptor() {}
func (HTMLSElement) TagName() string { return "s" }

type HTMLSampElement struct{}
func (HTMLSampElement) elementDescriptor() {}
func (HTMLSampElement) TagName() string { return "samp" }

type HTMLScriptElement struct{}
func (HTMLScriptElement) elementDescriptor() {}
func (HTMLScriptElement) TagName() string { return "script" }

type HTMLSectionElement struct{}
func (HTMLSectionElement) elementDescriptor() {}
func (HTMLSectionElement) TagName() string { return "section" }

type HTMLSelectElement struct{}
func (HTMLSelectElement) elementDescriptor() {}
func (HTMLSelectElement) TagName() string { return "select" }

type HTMLSlotElement struct{}
func (HTMLSlotElement) elementDescriptor() {}
func (HTMLSlotElement) TagName() string { return "slot" }

type HTMLSmallElement struct{}
func (HTMLSmallElement) elementDescriptor() {}
func (HTMLSmallElement) TagName() string { return "small" }

type HTMLSourceElement struct{}
func (HTMLSourceElement) elementDescriptor() {}
func (HTMLSourceElement) TagName() string { return "source" }

type HTMLSpanElement struct{}
func (HTMLSpanElement) elementDescriptor() {}
func (HTMLSpanElement) TagName() string { return "span" }

type SVGStopElement struct{}
func (SVGStopElement) elementDescriptor() {}
func (SVGStopElement) TagName() string { return "stop" }

type HTMLStrongElement struct{}
func (HTMLStrongElement) elementDescriptor() {}
func (HTMLStrongElement) TagName() string { return "strong" }

type HTMLStyleElement struct{}
func (HTMLStyleElement) elementDescriptor() {}
func (HTMLStyleElement) TagName() string { return "style" }

type HTMLSubElement struct{}
func (HTMLSubElement) elementDescriptor() {}
func (HTMLSubElement) TagName() string { return "sub" }

type HTMLSummaryElement struct{}
func (HTMLSummaryElement) elementDescriptor() {}
func (HTMLSummaryElement) TagName() string { return "summary" }

type HTMLSupElement struct{}
func (HTMLSupElement) elementDescriptor() {}
func (HTMLSupElement) TagName() string { return "sup" }

type SVGSvgElement struct{}
func (SVGSvgElement) elementDescriptor() {}
func (SVGSvgElement) TagName() string { return "svg" }

type SVGSvgTextElement struct{}
func (SVGSvgTextElement) elementDescriptor() {}
func (SVGSvgTextElement) TagName() string { return "text" }

type SVGTSpanElement struct{}
func (SVGTSpanElement) elementDescriptor() {}
func (SVGTSpanElement) TagName() string { return "tspan" }

type HTMLTableElement struct{}
func (HTMLTableElement) elementDescriptor() {}
func (HTMLTableElement) TagName() string { return "table" }

type HTMLTbodyElement struct{}
func (HTMLTbodyElement) elementDescriptor() {}
func (HTMLTbodyElement) TagName() string { return "tbody" }

type HTMLTdElement struct{}
func (HTMLTdElement) elementDescriptor() {}
func (HTMLTdElement) TagName() string { return "td" }

type HTMLTemplateElement struct{}
func (HTMLTemplateElement) elementDescriptor() {}
func (HTMLTemplateElement) TagName() string { return "template" }

type HTMLTextareaElement struct{}
func (HTMLTextareaElement) elementDescriptor() {}
func (HTMLTextareaElement) TagName() string { return "textarea" }

type HTMLTfootElement struct{}
func (HTMLTfootElement) elementDescriptor() {}
func (HTMLTfootElement) TagName() string { return "tfoot" }

type HTMLThElement struct{}
func (HTMLThElement) elementDescriptor() {}
func (HTMLThElement) TagName() string { return "th" }

type HTMLTheadElement struct{}
func (HTMLTheadElement) elementDescriptor() {}
func (HTMLTheadElement) TagName() string { return "thead" }

type HTMLTimeElement struct{}
func (HTMLTimeElement) elementDescriptor() {}
func (HTMLTimeElement) TagName() string { return "time" }

type HTMLTitleElement struct{}
func (HTMLTitleElement) elementDescriptor() {}
func (HTMLTitleElement) TagName() string { return "title" }

type HTMLTrElement struct{}
func (HTMLTrElement) elementDescriptor() {}
func (HTMLTrElement) TagName() string { return "tr" }

type HTMLTrackElement struct{}
func (HTMLTrackElement) elementDescriptor() {}
func (HTMLTrackElement) TagName() string { return "track" }

type HTMLUElement struct{}
func (HTMLUElement) elementDescriptor() {}
func (HTMLUElement) TagName() string { return "u" }

type HTMLUlElement struct{}
func (HTMLUlElement) elementDescriptor() {}
func (HTMLUlElement) TagName() string { return "ul" }

type SVGUseElement struct{}
func (SVGUseElement) elementDescriptor() {}
func (SVGUseElement) TagName() string { return "use" }

type HTMLVarElement struct{}
func (HTMLVarElement) elementDescriptor() {}
func (HTMLVarElement) TagName() string { return "var" }

type HTMLVideoElement struct{}
func (HTMLVideoElement) elementDescriptor() {}
func (HTMLVideoElement) TagName() string { return "video" }

type HTMLWbrElement struct{}
func (HTMLWbrElement) elementDescriptor() {}
func (HTMLWbrElement) TagName() string { return "wbr" }

// A creates an <a> element.
func A(items ...Item) *Element { return el(HTMLAElement{}, "a", items...) }

// Abbr creates an <abbr> element.
func Abbr(items ...Item) *Element { return el(HTMLAbbrElement{}, "abbr", items...) }

// Address creates an <address> element.
func Address(items ...Item) *Element { return el(HTMLAddressElement{}, "address", items...) }

// Area creates an <area> element.
func Area(items ...Item) *Element { return el(HTMLAreaElement{}, "area", items...) }

// Article creates an <article> element.
func Article(items ...Item) *Element { return el(HTMLArticleElement{}, "article", items...) }

// Aside creates an <aside> element.
func Aside(items ...Item) *Element { return el(HTMLAsideElement{}, "aside", items...) }

// Audio creates an <audio> element.
func Audio(items ...Item) *Element { return el(HTMLAudioElement{}, "audio", items...) }

// B creates a <b> element.
func B(items ...Item) *Element { return el(HTMLBElement{}, "b", items...) }

// Base creates a <base> element.
func Base(items ...Item) *Element { return el(HTMLBaseElement{}, "base", items...) }

// Bdi creates a <bdi> element.
func Bdi(items ...Item) *Element { return el(HTMLBdiElement{}, "bdi", items...) }

// Bdo creates a <bdo> element.
func Bdo(items ...Item) *Element { return el(HTMLBdoElement{}, "bdo", items...) }

// Blockquote creates a <blockquote> element.
func Blockquote(items ...Item) *Element { return el(HTMLBlockquoteElement{}, "blockquote", items...) }

// Body creates a <body> element.
func Body(items ...Item) *Element { return el(HTMLBodyElement{}, "body", items...) }

// Br creates a <br> element.
func Br(items ...Item) *Element { return el(HTMLBrElement{}, "br", items...) }

// Button creates a <button> element.
func Button(items ...Item) *Element { return el(HTMLButtonElement{}, "button", items...) }

// Canvas creates a <canvas> element.
func Canvas(items ...Item) *Element { return el(HTMLCanvasElement{}, "canvas", items...) }

// Caption creates a <caption> element.
func Caption(items ...Item) *Element { return el(HTMLCaptionElement{}, "caption", items...) }

// Circle creates a <circle> element.
func Circle(items ...Item) *Element { return el(SVGCircleElement{}, "circle", items...) }

// Cite creates a <cite> element.
func Cite(items ...Item) *Element { return el(HTMLCiteElement{}, "cite", items...) }

// ClipPath creates a <clipPath> element.
func ClipPath(items ...Item) *Element { return el(SVGClipPathElement{}, "clipPath", items...) }

// Code creates a <code> element.
func Code(items ...Item) *Element { return el(HTMLCodeElement{}, "code", items...) }

// Col creates a <col> element.
func Col(items ...Item) *Element { return el(HTMLColElement{}, "col", items...) }

// Colgroup creates a <colgroup> element.
func Colgroup(items ...Item) *Element { return el(HTMLColgroupElement{}, "colgroup", items...) }

// DataEl creates a <data> element.
func DataEl(items ...Item) *Element { return el(HTMLDataElement{}, "data", items...) }

// Datalist creates a <datalist> element.
func Datalist(items ...Item) *Element { return el(HTMLDatalistElement{}, "datalist", items...) }

// Dd creates a <dd> element.
func Dd(items ...Item) *Element { return el(HTMLDdElement{}, "dd", items...) }

// Defs creates a <defs> element.
func Defs(items ...Item) *Element { return el(SVGDefsElement{}, "defs", items...) }

// DelEl creates a <del> element.
func DelEl(items ...Item) *Element { return el(HTMLDelElement{}, "del", items...) }

// Details creates a <details> element.
func Details(items ...Item) *Element { return el(HTMLDetailsElement{}, "details", items...) }

// Dfn creates a <dfn> element.
func Dfn(items ...Item) *Element { return el(HTMLDfnElement{}, "dfn", items...) }

// Dialog creates a <dialog> element.
func Dialog(items ...Item) *Element { return el(HTMLDialogElement{}, "dialog", items...) }

// Div creates a <div> element.
func Div(items ...Item) *Element { return el(HTMLDivElement{}, "div", items...) }

// Dl creates a <dl> element.
func Dl(items ...Item) *Element { return el(HTMLDlElement{}, "dl", items...) }

// Dt creates a <dt> element.
func Dt(items ...Item) *Element { return el(HTMLDtElement{}, "dt", items...) }

// Ellipse creates an <ellipse> element.
func Ellipse(items ...Item) *Element { return el(SVGEllipseElement{}, "ellipse", items...) }

// Em creates an <em> element.
func Em(items ...Item) *Element { return el(HTMLEmElement{}, "em", items...) }

// Embed creates an <embed> element.
func Embed(items ...Item) *Element { return el(HTMLEmbedElement{}, "embed", items...) }

// Fieldset creates a <fieldset> element.
func Fieldset(items ...Item) *Element { return el(HTMLFieldsetElement{}, "fieldset", items...) }

// Figcaption creates a <figcaption> element.
func Figcaption(items ...Item) *Element { return el(HTMLFigcaptionElement{}, "figcaption", items...) }

// Figure creates a <figure> element.
func Figure(items ...Item) *Element { return el(HTMLFigureElement{}, "figure", items...) }

// Footer creates a <footer> element.
func Footer(items ...Item) *Element { return el(HTMLFooterElement{}, "footer", items...) }

// ForeignObject creates a <foreignObject> element.
func ForeignObject(items ...Item) *Element { return el(SVGForeignObjectElement{}, "foreignObject", items...) }

// Form creates a <form> element.
func Form(items ...Item) *Element { return el(HTMLFormElement{}, "form", items...) }

// G creates a <g> element.
func G(items ...Item) *Element { return el(SVGGElement{}, "g", items...) }

// H1 creates an <h1> element.
func H1(items ...Item) *Element { return el(HTMLH1Element{}, "h1", items...) }

// H2 creates an <h2> element.
func H2(items ...Item) *Element { return el(HTMLH2Element{}, "h2", items...) }

// H3 creates an <h3> element.
func H3(items ...Item) *Element { return el(HTMLH3Element{}, "h3", items...) }

// H4 creates an <h4> element.
func H4(items ...Item) *Element { return el(HTMLH4Element{}, "h4", items...) }

// H5 creates an <h5> element.
func H5(items ...Item) *Element { return el(HTMLH5Element{}, "h5", items...) }

// H6 creates an <h6> element.
func H6(items ...Item) *Element { return el(HTMLH6Element{}, "h6", items...) }

// Head creates a <head> element.
func Head(items ...Item) *Element { return el(HTMLHeadElement{}, "head", items...) }

// Header creates a <header> element.
func Header(items ...Item) *Element { return el(HTMLHeaderElement{}, "header", items...) }

// Hgroup creates an <hgroup> element.
func Hgroup(items ...Item) *Element { return el(HTMLHgroupElement{}, "hgroup", items...) }

// Hr creates an <hr> element.
func Hr(items ...Item) *Element { return el(HTMLHrElement{}, "hr", items...) }

// Html creates an <html> element.
func Html(items ...Item) *Element { return el(HTMLHtmlElement{}, "html", items...) }

// I creates an <i> element.
func I(items ...Item) *Element { return el(HTMLIElement{}, "i", items...) }

// Iframe creates an <iframe> element.
func Iframe(items ...Item) *Element { return el(HTMLIframeElement{}, "iframe", items...) }

// Image creates an <image> element.
func Image(items ...Item) *Element { return el(SVGImageElement{}, "image", items...) }

// Img creates an <img> element.
func Img(items ...Item) *Element { return el(HTMLImgElement{}, "img", items...) }

// Input creates an <input> element.
func Input(items ...Item) *Element { return el(HTMLInputElement{}, "input", items...) }

// InsEl creates an <ins> element.
func InsEl(items ...Item) *Element { return el(HTMLInsElement{}, "ins", items...) }

// Kbd creates a <kbd> element.
func Kbd(items ...Item) *Element { return el(HTMLKbdElement{}, "kbd", items...) }

// Label creates a <label> element.
func Label(items ...Item) *Element { return el(HTMLLabelElement{}, "label", items...) }

// Legend creates a <legend> element.
func Legend(items ...Item) *Element { return el(HTMLLegendElement{}, "legend", items...) }

// Li creates an <li> element.
func Li(items ...Item) *Element { return el(HTMLLiElement{}, "li", items...) }

// Line creates a <line> element.
func Line(items ...Item) *Element { return el(SVGLineElement{}, "line", items...) }

// LinearGradient creates a <linearGradient> element.
func LinearGradient(items ...Item) *Element { return el(SVGLinearGradientElement{}, "linearGradient", items...) }

// Link creates a <link> element.
func Link(items ...Item) *Element { return el(HTMLLinkElement{}, "link", items...) }

// Main creates a <main> element.
func Main(items ...Item) *Element { return el(HTMLMainElement{}, "main", items...) }

// MapEl creates a <map> element.
func MapEl(items ...Item) *Element { return el(HTMLMapElement{}, "map", items...) }

// Mark creates a <mark> element.
func Mark(items ...Item) *Element { return el(HTMLMarkElement{}, "mark", items...) }

// Marker creates a <marker> element.
func Marker(items ...Item) *Element { return el(SVGMarkerElement{}, "marker", items...) }

// Mask creates a <mask> element.
func Mask(items ...Item) *Element { return el(SVGMaskElement{}, "mask", items...) }

// Menu creates a <menu> element.
func Menu(items ...Item) *Element { return el(HTMLMenuElement{}, "menu", items...) }

// MenuItem creates a <menuitem> element.
func MenuItem(items ...Item) *Element { return el(HTMLMenuItemElement{}, "menuitem", items...) }

// Meta creates a <meta> element.
func Meta(items ...Item) *Element { return el(HTMLMetaElement{}, "meta", items...) }

// Meter creates a <meter> element.
func Meter(items ...Item) *Element { return el(HTMLMeterElement{}, "meter", items...) }

// Nav creates a <nav> element.
func Nav(items ...Item) *Element { return el(HTMLNavElement{}, "nav", items...) }

// Noscript creates a <noscript> element.
func Noscript(items ...Item) *Element { return el(HTMLNoscriptElement{}, "noscript", items...) }

// Object creates an <object> element.
func Object(items ...Item) *Element { return el(HTMLObjectElement{}, "object", items...) }

// Ol creates an <ol> element.
func Ol(items ...Item) *Element { return el(HTMLOlElement{}, "ol", items...) }

// Optgroup creates an <optgroup> element.
func Optgroup(items ...Item) *Element { return el(HTMLOptgroupElement{}, "optgroup", items...) }

// Option creates an <option> element.
func Option(items ...Item) *Element { return el(HTMLOptionElement{}, "option", items...) }

// Output creates an <output> element.
func Output(items ...Item) *Element { return el(HTMLOutputElement{}, "output", items...) }

// P creates a <p> element.
func P(items ...Item) *Element { return el(HTMLPElement{}, "p", items...) }

// Param creates a <param> element.
func Param(items ...Item) *Element { return el(HTMLParamElement{}, "param", items...) }

// Path creates a <path> element.
func Path(items ...Item) *Element { return el(SVGPathElement{}, "path", items...) }

// Pattern creates a <pattern> element.
func Pattern(items ...Item) *Element { return el(SVGPatternElement{}, "pattern", items...) }

// Picture creates a <picture> element.
func Picture(items ...Item) *Element { return el(HTMLPictureElement{}, "picture", items...) }

// Polygon creates a <polygon> element.
func Polygon(items ...Item) *Element { return el(SVGPolygonElement{}, "polygon", items...) }

// Polyline creates a <polyline> element.
func Polyline(items ...Item) *Element { return el(SVGPolylineElement{}, "polyline", items...) }

// Portal creates a <portal> element.
func Portal(items ...Item) *Element { return el(HTMLPortalElement{}, "portal", items...) }

// Pre creates a <pre> element.
func Pre(items ...Item) *Element { return el(HTMLPreElement{}, "pre", items...) }

// Progress creates a <progress> element.
func Progress(items ...Item) *Element { return el(HTMLProgressElement{}, "progress", items...) }

// Q creates a <q> element.
func Q(items ...Item) *Element { return el(HTMLQElement{}, "q", items...) }

// RadialGradient creates a <radialGradient> element.
func RadialGradient(items ...Item) *Element { return el(SVGRadialGradientElement{}, "radialGradient", items...) }

// Rb creates an <rb> element.
func Rb(items ...Item) *Element { return el(HTMLRbElement{}, "rb", items...) }

// Rect creates a <rect> element.
func Rect(items ...Item) *Element { return el(SVGRectElement{}, "rect", items...) }

// Rp creates an <rp> element.
func Rp(items ...Item) *Element { return el(HTMLRpElement{}, "rp", items...) }

// Rt creates an <rt> element.
func Rt(items ...Item) *Element { return el(HTMLRtElement{}, "rt", items...) }

// Rtc creates a <rtc> element.
func Rtc(items ...Item) *Element { return el(HTMLRtcElement{}, "rtc", items...) }

// Ruby creates a <ruby> element.
func Ruby(items ...Item) *Element { return el(HTMLRubyElement{}, "ruby", items...) }

// S creates an <s> element.
func S(items ...Item) *Element { return el(HTMLSElement{}, "s", items...) }

// Samp creates a <samp> element.
func Samp(items ...Item) *Element { return el(HTMLSampElement{}, "samp", items...) }

// Script creates a <script> element.
func Script(items ...Item) *Element { return el(HTMLScriptElement{}, "script", items...) }

// Section creates a <section> element.
func Section(items ...Item) *Element { return el(HTMLSectionElement{}, "section", items...) }

// Select creates a <select> element.
func Select(items ...Item) *Element { return el(HTMLSelectElement{}, "select", items...) }

// Slot creates a <slot> element.
func Slot(items ...Item) *Element { return el(HTMLSlotElement{}, "slot", items...) }

// Small creates a <small> element.
func Small(items ...Item) *Element { return el(HTMLSmallElement{}, "small", items...) }

// Source creates a <source> element.
func Source(items ...Item) *Element { return el(HTMLSourceElement{}, "source", items...) }

// Span creates a <span> element.
func Span(items ...Item) *Element { return el(HTMLSpanElement{}, "span", items...) }

// Stop creates a <stop> element.
func Stop(items ...Item) *Element { return el(SVGStopElement{}, "stop", items...) }

// Strong creates a <strong> element.
func Strong(items ...Item) *Element { return el(HTMLStrongElement{}, "strong", items...) }

// StyleEl creates a <style> element.
func StyleEl(items ...Item) *Element { return el(HTMLStyleElement{}, "style", items...) }

// Sub creates a <sub> element.
func Sub(items ...Item) *Element { return el(HTMLSubElement{}, "sub", items...) }

// Summary creates a <summary> element.
func Summary(items ...Item) *Element { return el(HTMLSummaryElement{}, "summary", items...) }

// Sup creates a <sup> element.
func Sup(items ...Item) *Element { return el(HTMLSupElement{}, "sup", items...) }

// Svg creates an <svg> element.
func Svg(items ...Item) *Element { return el(SVGSvgElement{}, "svg", items...) }

// SvgText creates an SVG <text> element.
func SvgText(items ...Item) *Element { return el(SVGSvgTextElement{}, "text", items...) }

// TSpan creates a <tspan> element.
func TSpan(items ...Item) *Element { return el(SVGTSpanElement{}, "tspan", items...) }

// Table creates a <table> element.
func Table(items ...Item) *Element { return el(HTMLTableElement{}, "table", items...) }

// Tbody creates a <tbody> element.
func Tbody(items ...Item) *Element { return el(HTMLTbodyElement{}, "tbody", items...) }

// Td creates a <td> element.
func Td(items ...Item) *Element { return el(HTMLTdElement{}, "td", items...) }

// Template creates a <template> element.
func Template(items ...Item) *Element { return el(HTMLTemplateElement{}, "template", items...) }

// Textarea creates a <textarea> element.
func Textarea(items ...Item) *Element { return el(HTMLTextareaElement{}, "textarea", items...) }

// Tfoot creates a <tfoot> element.
func Tfoot(items ...Item) *Element { return el(HTMLTfootElement{}, "tfoot", items...) }

// Th creates a <th> element.
func Th(items ...Item) *Element { return el(HTMLThElement{}, "th", items...) }

// Thead creates a <thead> element.
func Thead(items ...Item) *Element { return el(HTMLTheadElement{}, "thead", items...) }

// Time creates a <time> element.
func Time(items ...Item) *Element { return el(HTMLTimeElement{}, "time", items...) }

// TitleEl creates a <title> element.
func TitleEl(items ...Item) *Element { return el(HTMLTitleElement{}, "title", items...) }

// Tr creates a <tr> element.
func Tr(items ...Item) *Element { return el(HTMLTrElement{}, "tr", items...) }

// Track creates a <track> element.
func Track(items ...Item) *Element { return el(HTMLTrackElement{}, "track", items...) }

// U creates a <u> element.
func U(items ...Item) *Element { return el(HTMLUElement{}, "u", items...) }

// Ul creates a <ul> element.
func Ul(items ...Item) *Element { return el(HTMLUlElement{}, "ul", items...) }

// Use creates a <use> element.
func Use(items ...Item) *Element { return el(SVGUseElement{}, "use", items...) }

// Var creates a <var> element.
func Var(items ...Item) *Element { return el(HTMLVarElement{}, "var", items...) }

// Video creates a <video> element.
func Video(items ...Item) *Element { return el(HTMLVideoElement{}, "video", items...) }

// Wbr creates a <wbr> element.
func Wbr(items ...Item) *Element { return el(HTMLWbrElement{}, "wbr", items...) }

