// Code generated by tags_gen.go; DO NOT EDIT.

package pkg

type ARef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type AbbrRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type AddressRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type AreaRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type ArticleRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type AsideRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type AudioRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
	*MediaActions
}

type BRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type BaseRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type BdiRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type BdoRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type BlockquoteRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type BodyRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type BrRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type ButtonRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
	*DisableableActions
}

type CanvasRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
	*CanvasActions
}

type CaptionRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type CircleRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type CiteRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type ClipPathRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type CodeRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type ColRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type ColgroupRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type DataElRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type DatalistRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type DdRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type DefsRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type DelElRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type DetailsRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
	*DetailsActions
}

type DfnRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type DialogRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
	*DialogActions
}

type DivRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type DlRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type DtRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type EllipseRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type EmRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type EmbedRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type FieldsetRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
	*DisableableActions
}

type FigcaptionRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type FigureRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type FooterRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type ForeignObjectRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type FormRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
	*FormActions
}

type GRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type H1Ref struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type H2Ref struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type H3Ref struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type H4Ref struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type H5Ref struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type H6Ref struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type HeadRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type HeaderRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type HgroupRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type HrRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type HtmlRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type IRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type IframeRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type ImageRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type ImgRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type InputRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
	*ValueActions
	*DisableableActions
	*SelectionActions
}

type InsElRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type KbdRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type LabelRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type LegendRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type LiRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type LineRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type LinearGradientRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type LinkElRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type MainRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type MapElRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type MarkRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type MarkerRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type MaskRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type MenuRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type MenuItemRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type MetaElRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type MeterRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
	*ValueActions
}

type NavRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type NoscriptRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type ObjectRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type OlRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type OptgroupRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type OptionRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type OutputRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type PRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type ParamRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type PathRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type PatternRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type PictureRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type PolygonRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type PolylineRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type PortalElRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type PreRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type ProgressRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
	*ValueActions
}

type QRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type RadialGradientRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type RbRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type RectRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type RpRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type RtRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type RtcRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type RubyRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type SRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type SampRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type ScriptElRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type SectionRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type SelectRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
	*ValueActions
	*DisableableActions
}

type SlotRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type SmallRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type SourceRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type SpanRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type StopRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type StrongRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type StyleElRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type SubRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type SummaryRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type SupRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type SvgRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type SvgTextRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type SvgUseRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type TSpanRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type TableRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type TbodyRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type TdRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type TemplateRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type TextareaRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
	*ValueActions
	*DisableableActions
	*SelectionActions
}

type TfootRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type ThRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type TheadRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type TimeRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type TitleElRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type TrRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type TrackRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type URef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type UlRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type VarRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

type VideoRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
	*MediaActions
}

type WbrRef struct {
	*ElementRef
	*ElementActions
	*ScrollActions
}

func UseA(ctx *Ctx) *ARef {
	ref := UseElement(ctx)
	return &ARef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseAbbr(ctx *Ctx) *AbbrRef {
	ref := UseElement(ctx)
	return &AbbrRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseAddress(ctx *Ctx) *AddressRef {
	ref := UseElement(ctx)
	return &AddressRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseArea(ctx *Ctx) *AreaRef {
	ref := UseElement(ctx)
	return &AreaRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseArticle(ctx *Ctx) *ArticleRef {
	ref := UseElement(ctx)
	return &ArticleRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseAside(ctx *Ctx) *AsideRef {
	ref := UseElement(ctx)
	return &AsideRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseAudio(ctx *Ctx) *AudioRef {
	ref := UseElement(ctx)
	return &AudioRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
		MediaActions:   NewMediaActions(ctx, ref),
	}
}

func UseB(ctx *Ctx) *BRef {
	ref := UseElement(ctx)
	return &BRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseBase(ctx *Ctx) *BaseRef {
	ref := UseElement(ctx)
	return &BaseRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseBdi(ctx *Ctx) *BdiRef {
	ref := UseElement(ctx)
	return &BdiRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseBdo(ctx *Ctx) *BdoRef {
	ref := UseElement(ctx)
	return &BdoRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseBlockquote(ctx *Ctx) *BlockquoteRef {
	ref := UseElement(ctx)
	return &BlockquoteRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseBody(ctx *Ctx) *BodyRef {
	ref := UseElement(ctx)
	return &BodyRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseBr(ctx *Ctx) *BrRef {
	ref := UseElement(ctx)
	return &BrRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseButton(ctx *Ctx) *ButtonRef {
	ref := UseElement(ctx)
	return &ButtonRef{
		ElementRef:         ref,
		ElementActions:     NewElementActions(ctx, ref),
		ScrollActions:      NewScrollActions(ctx, ref),
		DisableableActions: NewDisableableActions(ctx, ref),
	}
}

func UseCanvas(ctx *Ctx) *CanvasRef {
	ref := UseElement(ctx)
	return &CanvasRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
		CanvasActions:  NewCanvasActions(ctx, ref),
	}
}

func UseCaption(ctx *Ctx) *CaptionRef {
	ref := UseElement(ctx)
	return &CaptionRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseCircle(ctx *Ctx) *CircleRef {
	ref := UseElement(ctx)
	return &CircleRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseCite(ctx *Ctx) *CiteRef {
	ref := UseElement(ctx)
	return &CiteRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseClipPath(ctx *Ctx) *ClipPathRef {
	ref := UseElement(ctx)
	return &ClipPathRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseCode(ctx *Ctx) *CodeRef {
	ref := UseElement(ctx)
	return &CodeRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseCol(ctx *Ctx) *ColRef {
	ref := UseElement(ctx)
	return &ColRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseColgroup(ctx *Ctx) *ColgroupRef {
	ref := UseElement(ctx)
	return &ColgroupRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseDataEl(ctx *Ctx) *DataElRef {
	ref := UseElement(ctx)
	return &DataElRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseDatalist(ctx *Ctx) *DatalistRef {
	ref := UseElement(ctx)
	return &DatalistRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseDd(ctx *Ctx) *DdRef {
	ref := UseElement(ctx)
	return &DdRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseDefs(ctx *Ctx) *DefsRef {
	ref := UseElement(ctx)
	return &DefsRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseDelEl(ctx *Ctx) *DelElRef {
	ref := UseElement(ctx)
	return &DelElRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseDetails(ctx *Ctx) *DetailsRef {
	ref := UseElement(ctx)
	return &DetailsRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
		DetailsActions: NewDetailsActions(ctx, ref),
	}
}

func UseDfn(ctx *Ctx) *DfnRef {
	ref := UseElement(ctx)
	return &DfnRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseDialog(ctx *Ctx) *DialogRef {
	ref := UseElement(ctx)
	return &DialogRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
		DialogActions:  NewDialogActions(ctx, ref),
	}
}

func UseDiv(ctx *Ctx) *DivRef {
	ref := UseElement(ctx)
	return &DivRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseDl(ctx *Ctx) *DlRef {
	ref := UseElement(ctx)
	return &DlRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseDt(ctx *Ctx) *DtRef {
	ref := UseElement(ctx)
	return &DtRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseEllipse(ctx *Ctx) *EllipseRef {
	ref := UseElement(ctx)
	return &EllipseRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseEm(ctx *Ctx) *EmRef {
	ref := UseElement(ctx)
	return &EmRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseEmbed(ctx *Ctx) *EmbedRef {
	ref := UseElement(ctx)
	return &EmbedRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseFieldset(ctx *Ctx) *FieldsetRef {
	ref := UseElement(ctx)
	return &FieldsetRef{
		ElementRef:         ref,
		ElementActions:     NewElementActions(ctx, ref),
		ScrollActions:      NewScrollActions(ctx, ref),
		DisableableActions: NewDisableableActions(ctx, ref),
	}
}

func UseFigcaption(ctx *Ctx) *FigcaptionRef {
	ref := UseElement(ctx)
	return &FigcaptionRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseFigure(ctx *Ctx) *FigureRef {
	ref := UseElement(ctx)
	return &FigureRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseFooter(ctx *Ctx) *FooterRef {
	ref := UseElement(ctx)
	return &FooterRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseForeignObject(ctx *Ctx) *ForeignObjectRef {
	ref := UseElement(ctx)
	return &ForeignObjectRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseForm(ctx *Ctx) *FormRef {
	ref := UseElement(ctx)
	return &FormRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
		FormActions:    NewFormActions(ctx, ref),
	}
}

func UseG(ctx *Ctx) *GRef {
	ref := UseElement(ctx)
	return &GRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseH1(ctx *Ctx) *H1Ref {
	ref := UseElement(ctx)
	return &H1Ref{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseH2(ctx *Ctx) *H2Ref {
	ref := UseElement(ctx)
	return &H2Ref{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseH3(ctx *Ctx) *H3Ref {
	ref := UseElement(ctx)
	return &H3Ref{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseH4(ctx *Ctx) *H4Ref {
	ref := UseElement(ctx)
	return &H4Ref{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseH5(ctx *Ctx) *H5Ref {
	ref := UseElement(ctx)
	return &H5Ref{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseH6(ctx *Ctx) *H6Ref {
	ref := UseElement(ctx)
	return &H6Ref{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseHead(ctx *Ctx) *HeadRef {
	ref := UseElement(ctx)
	return &HeadRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseHeader(ctx *Ctx) *HeaderRef {
	ref := UseElement(ctx)
	return &HeaderRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseHgroup(ctx *Ctx) *HgroupRef {
	ref := UseElement(ctx)
	return &HgroupRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseHr(ctx *Ctx) *HrRef {
	ref := UseElement(ctx)
	return &HrRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseHtml(ctx *Ctx) *HtmlRef {
	ref := UseElement(ctx)
	return &HtmlRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseI(ctx *Ctx) *IRef {
	ref := UseElement(ctx)
	return &IRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseIframe(ctx *Ctx) *IframeRef {
	ref := UseElement(ctx)
	return &IframeRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseImage(ctx *Ctx) *ImageRef {
	ref := UseElement(ctx)
	return &ImageRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseImg(ctx *Ctx) *ImgRef {
	ref := UseElement(ctx)
	return &ImgRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseInput(ctx *Ctx) *InputRef {
	ref := UseElement(ctx)
	return &InputRef{
		ElementRef:         ref,
		ElementActions:     NewElementActions(ctx, ref),
		ScrollActions:      NewScrollActions(ctx, ref),
		ValueActions:       NewValueActions(ctx, ref),
		DisableableActions: NewDisableableActions(ctx, ref),
		SelectionActions:   NewSelectionActions(ctx, ref),
	}
}

func UseInsEl(ctx *Ctx) *InsElRef {
	ref := UseElement(ctx)
	return &InsElRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseKbd(ctx *Ctx) *KbdRef {
	ref := UseElement(ctx)
	return &KbdRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseLabel(ctx *Ctx) *LabelRef {
	ref := UseElement(ctx)
	return &LabelRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseLegend(ctx *Ctx) *LegendRef {
	ref := UseElement(ctx)
	return &LegendRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseLi(ctx *Ctx) *LiRef {
	ref := UseElement(ctx)
	return &LiRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseLine(ctx *Ctx) *LineRef {
	ref := UseElement(ctx)
	return &LineRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseLinearGradient(ctx *Ctx) *LinearGradientRef {
	ref := UseElement(ctx)
	return &LinearGradientRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseLinkEl(ctx *Ctx) *LinkElRef {
	ref := UseElement(ctx)
	return &LinkElRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseMain(ctx *Ctx) *MainRef {
	ref := UseElement(ctx)
	return &MainRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseMapEl(ctx *Ctx) *MapElRef {
	ref := UseElement(ctx)
	return &MapElRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseMark(ctx *Ctx) *MarkRef {
	ref := UseElement(ctx)
	return &MarkRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseMarker(ctx *Ctx) *MarkerRef {
	ref := UseElement(ctx)
	return &MarkerRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseMask(ctx *Ctx) *MaskRef {
	ref := UseElement(ctx)
	return &MaskRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseMenu(ctx *Ctx) *MenuRef {
	ref := UseElement(ctx)
	return &MenuRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseMenuItem(ctx *Ctx) *MenuItemRef {
	ref := UseElement(ctx)
	return &MenuItemRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseMetaEl(ctx *Ctx) *MetaElRef {
	ref := UseElement(ctx)
	return &MetaElRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseMeter(ctx *Ctx) *MeterRef {
	ref := UseElement(ctx)
	return &MeterRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
		ValueActions:   NewValueActions(ctx, ref),
	}
}

func UseNav(ctx *Ctx) *NavRef {
	ref := UseElement(ctx)
	return &NavRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseNoscript(ctx *Ctx) *NoscriptRef {
	ref := UseElement(ctx)
	return &NoscriptRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseObject(ctx *Ctx) *ObjectRef {
	ref := UseElement(ctx)
	return &ObjectRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseOl(ctx *Ctx) *OlRef {
	ref := UseElement(ctx)
	return &OlRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseOptgroup(ctx *Ctx) *OptgroupRef {
	ref := UseElement(ctx)
	return &OptgroupRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseOption(ctx *Ctx) *OptionRef {
	ref := UseElement(ctx)
	return &OptionRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseOutput(ctx *Ctx) *OutputRef {
	ref := UseElement(ctx)
	return &OutputRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseP(ctx *Ctx) *PRef {
	ref := UseElement(ctx)
	return &PRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseParam(ctx *Ctx) *ParamRef {
	ref := UseElement(ctx)
	return &ParamRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UsePath(ctx *Ctx) *PathRef {
	ref := UseElement(ctx)
	return &PathRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UsePattern(ctx *Ctx) *PatternRef {
	ref := UseElement(ctx)
	return &PatternRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UsePicture(ctx *Ctx) *PictureRef {
	ref := UseElement(ctx)
	return &PictureRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UsePolygon(ctx *Ctx) *PolygonRef {
	ref := UseElement(ctx)
	return &PolygonRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UsePolyline(ctx *Ctx) *PolylineRef {
	ref := UseElement(ctx)
	return &PolylineRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UsePortalEl(ctx *Ctx) *PortalElRef {
	ref := UseElement(ctx)
	return &PortalElRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UsePre(ctx *Ctx) *PreRef {
	ref := UseElement(ctx)
	return &PreRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseProgress(ctx *Ctx) *ProgressRef {
	ref := UseElement(ctx)
	return &ProgressRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
		ValueActions:   NewValueActions(ctx, ref),
	}
}

func UseQ(ctx *Ctx) *QRef {
	ref := UseElement(ctx)
	return &QRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseRadialGradient(ctx *Ctx) *RadialGradientRef {
	ref := UseElement(ctx)
	return &RadialGradientRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseRb(ctx *Ctx) *RbRef {
	ref := UseElement(ctx)
	return &RbRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseRect(ctx *Ctx) *RectRef {
	ref := UseElement(ctx)
	return &RectRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseRp(ctx *Ctx) *RpRef {
	ref := UseElement(ctx)
	return &RpRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseRt(ctx *Ctx) *RtRef {
	ref := UseElement(ctx)
	return &RtRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseRtc(ctx *Ctx) *RtcRef {
	ref := UseElement(ctx)
	return &RtcRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseRuby(ctx *Ctx) *RubyRef {
	ref := UseElement(ctx)
	return &RubyRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseS(ctx *Ctx) *SRef {
	ref := UseElement(ctx)
	return &SRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseSamp(ctx *Ctx) *SampRef {
	ref := UseElement(ctx)
	return &SampRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseScriptEl(ctx *Ctx) *ScriptElRef {
	ref := UseElement(ctx)
	return &ScriptElRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseSection(ctx *Ctx) *SectionRef {
	ref := UseElement(ctx)
	return &SectionRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseSelect(ctx *Ctx) *SelectRef {
	ref := UseElement(ctx)
	return &SelectRef{
		ElementRef:         ref,
		ElementActions:     NewElementActions(ctx, ref),
		ScrollActions:      NewScrollActions(ctx, ref),
		ValueActions:       NewValueActions(ctx, ref),
		DisableableActions: NewDisableableActions(ctx, ref),
	}
}

func UseSlot(ctx *Ctx) *SlotRef {
	ref := UseElement(ctx)
	return &SlotRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseSmall(ctx *Ctx) *SmallRef {
	ref := UseElement(ctx)
	return &SmallRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseSource(ctx *Ctx) *SourceRef {
	ref := UseElement(ctx)
	return &SourceRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseSpan(ctx *Ctx) *SpanRef {
	ref := UseElement(ctx)
	return &SpanRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseStop(ctx *Ctx) *StopRef {
	ref := UseElement(ctx)
	return &StopRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseStrong(ctx *Ctx) *StrongRef {
	ref := UseElement(ctx)
	return &StrongRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseStyleEl(ctx *Ctx) *StyleElRef {
	ref := UseElement(ctx)
	return &StyleElRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseSub(ctx *Ctx) *SubRef {
	ref := UseElement(ctx)
	return &SubRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseSummary(ctx *Ctx) *SummaryRef {
	ref := UseElement(ctx)
	return &SummaryRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseSup(ctx *Ctx) *SupRef {
	ref := UseElement(ctx)
	return &SupRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseSvg(ctx *Ctx) *SvgRef {
	ref := UseElement(ctx)
	return &SvgRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseSvgText(ctx *Ctx) *SvgTextRef {
	ref := UseElement(ctx)
	return &SvgTextRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseSvgUse(ctx *Ctx) *SvgUseRef {
	ref := UseElement(ctx)
	return &SvgUseRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseTSpan(ctx *Ctx) *TSpanRef {
	ref := UseElement(ctx)
	return &TSpanRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseTable(ctx *Ctx) *TableRef {
	ref := UseElement(ctx)
	return &TableRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseTbody(ctx *Ctx) *TbodyRef {
	ref := UseElement(ctx)
	return &TbodyRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseTd(ctx *Ctx) *TdRef {
	ref := UseElement(ctx)
	return &TdRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseTemplate(ctx *Ctx) *TemplateRef {
	ref := UseElement(ctx)
	return &TemplateRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseTextarea(ctx *Ctx) *TextareaRef {
	ref := UseElement(ctx)
	return &TextareaRef{
		ElementRef:         ref,
		ElementActions:     NewElementActions(ctx, ref),
		ScrollActions:      NewScrollActions(ctx, ref),
		ValueActions:       NewValueActions(ctx, ref),
		DisableableActions: NewDisableableActions(ctx, ref),
		SelectionActions:   NewSelectionActions(ctx, ref),
	}
}

func UseTfoot(ctx *Ctx) *TfootRef {
	ref := UseElement(ctx)
	return &TfootRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseTh(ctx *Ctx) *ThRef {
	ref := UseElement(ctx)
	return &ThRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseThead(ctx *Ctx) *TheadRef {
	ref := UseElement(ctx)
	return &TheadRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseTime(ctx *Ctx) *TimeRef {
	ref := UseElement(ctx)
	return &TimeRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseTitleEl(ctx *Ctx) *TitleElRef {
	ref := UseElement(ctx)
	return &TitleElRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseTr(ctx *Ctx) *TrRef {
	ref := UseElement(ctx)
	return &TrRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseTrack(ctx *Ctx) *TrackRef {
	ref := UseElement(ctx)
	return &TrackRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseU(ctx *Ctx) *URef {
	ref := UseElement(ctx)
	return &URef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseUl(ctx *Ctx) *UlRef {
	ref := UseElement(ctx)
	return &UlRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseVar(ctx *Ctx) *VarRef {
	ref := UseElement(ctx)
	return &VarRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}

func UseVideo(ctx *Ctx) *VideoRef {
	ref := UseElement(ctx)
	return &VideoRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
		MediaActions:   NewMediaActions(ctx, ref),
	}
}

func UseWbr(ctx *Ctx) *WbrRef {
	ref := UseElement(ctx)
	return &WbrRef{
		ElementRef:     ref,
		ElementActions: NewElementActions(ctx, ref),
		ScrollActions:  NewScrollActions(ctx, ref),
	}
}
